// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/digitalocean/digitaloceanspaceskey/v1alpha1/spec.proto

package digitaloceanspaceskeyv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DigitalOceanSpacesKeySpec models the full digitalocean_spaces_key resource
// surface: an access-key pair for Spaces (DigitalOcean's S3-compatible object
// storage), optionally scoped to specific buckets through per-bucket grants.
//
// Keys are managed through DigitalOcean's REST API (not the S3-compatible
// endpoint), so provisioning needs only the account API token. The SECRET KEY
// IS RETURNED EXACTLY ONCE -- in the create response -- and can never be
// retrieved again; rotating a key means destroying and recreating it. The
// key name and the grant list both update in place (the grant list is
// replaced wholesale on every update); only the key material itself is
// immutable.
type DigitalOceanSpacesKeySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name identifying the key in the DigitalOcean control
	// panel. Renames apply in place without touching the key material.
	KeyName string `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	// (Optional) Per-bucket access grants. When empty, DigitalOcean creates
	// the key with NO access to anything -- grants are the only thing that
	// authorizes it. Account-wide access is expressed as a single grant with
	// permission "fullaccess" and no bucket. Updates replace the whole grant
	// list in one call.
	Grants        []*DigitalOceanSpacesKeyGrant `protobuf:"bytes,2,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalOceanSpacesKeySpec) Reset() {
	*x = DigitalOceanSpacesKeySpec{}
	mi := &file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalOceanSpacesKeySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalOceanSpacesKeySpec) ProtoMessage() {}

func (x *DigitalOceanSpacesKeySpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalOceanSpacesKeySpec.ProtoReflect.Descriptor instead.
func (*DigitalOceanSpacesKeySpec) Descriptor() ([]byte, []int) {
	return file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *DigitalOceanSpacesKeySpec) GetKeyName() string {
	if x != nil {
		return x.KeyName
	}
	return ""
}

func (x *DigitalOceanSpacesKeySpec) GetGrants() []*DigitalOceanSpacesKeyGrant {
	if x != nil {
		return x.Grants
	}
	return nil
}

// One access grant on a Spaces key: a permission applied either to a single
// bucket or (for "fullaccess" only) to every bucket in the account.
type DigitalOceanSpacesKeyGrant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bucket this grant scopes to. Use a literal bucket name or a
	// reference to a DigitalOceanBucket resource. Leave unset only for a
	// "fullaccess" grant, which covers every bucket in the account.
	Bucket *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Access level granted: read, readwrite, or fullaccess. This wall exists
	// only here -- the provider has no validator and silently maps any other
	// value to an EMPTY permission, creating a grant that authorizes nothing.
	Permission    string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalOceanSpacesKeyGrant) Reset() {
	*x = DigitalOceanSpacesKeyGrant{}
	mi := &file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalOceanSpacesKeyGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalOceanSpacesKeyGrant) ProtoMessage() {}

func (x *DigitalOceanSpacesKeyGrant) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalOceanSpacesKeyGrant.ProtoReflect.Descriptor instead.
func (*DigitalOceanSpacesKeyGrant) Descriptor() ([]byte, []int) {
	return file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *DigitalOceanSpacesKeyGrant) GetBucket() *v1.StringValueOrRef {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *DigitalOceanSpacesKeyGrant) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

var File_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	">catalog/digitalocean/digitaloceanspaceskey/v1alpha1/spec.proto\x127dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\"\xaf\x01\n" +
	"\x19DigitalOceanSpacesKeySpec\x12%\n" +
	"\bkey_name\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\akeyName\x12k\n" +
	"\x06grants\x18\x02 \x03(\v2S.dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1.DigitalOceanSpacesKeyGrantR\x06grants\"\xc2\x03\n" +
	"\x1aDigitalOceanSpacesKeyGrant\x12m\n" +
	"\x06bucket\x18\x01 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB!\x88\xd4a\x89'\x92\xd4a\x18status.outputs.bucket_idR\x06bucket\x12E\n" +
	"\n" +
	"permission\x18\x02 \x01(\tB%\xbaH\"\xc8\x01\x01r\x1dR\x04readR\treadwriteR\n" +
	"fullaccessR\n" +
	"permission:\xed\x01\xbaH\xe9\x01\x1a\xe6\x01\n" +
	"\x1fgrant.bucket_matches_permission\x12Ra fullaccess grant must not name a bucket; read and readwrite grants must name one\x1ao(this.permission == 'fullaccess' && !has(this.bucket)) || (this.permission != 'fullaccess' && has(this.bucket))B\xb9\x03\n" +
	";com.dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1B\tSpecProtoP\x01Zngithub.com/plantonhq/planton/catalog/digitalocean/digitaloceanspaceskey/v1alpha1;digitaloceanspaceskeyv1alpha1\xa2\x02\x04DPDD\xaa\x027Dev.Planton.Digitalocean.Digitaloceanspaceskey.V1alpha1\xca\x027Dev\\Planton\\Digitalocean\\Digitaloceanspaceskey\\V1alpha1\xe2\x02CDev\\Planton\\Digitalocean\\Digitaloceanspaceskey\\V1alpha1\\GPBMetadata\xea\x02;Dev::Planton::Digitalocean::Digitaloceanspaceskey::V1alpha1b\x06proto3"

var (
	file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDesc), len(file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDescData
}

var file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_goTypes = []any{
	(*DigitalOceanSpacesKeySpec)(nil),  // 0: dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1.DigitalOceanSpacesKeySpec
	(*DigitalOceanSpacesKeyGrant)(nil), // 1: dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1.DigitalOceanSpacesKeyGrant
	(*v1.StringValueOrRef)(nil),        // 2: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_depIdxs = []int32{
	1, // 0: dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1.DigitalOceanSpacesKeySpec.grants:type_name -> dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1.DigitalOceanSpacesKeyGrant
	2, // 1: dev.planton.digitalocean.digitaloceanspaceskey.v1alpha1.DigitalOceanSpacesKeyGrant.bucket:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_init() }
func file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_init() {
	if File_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDesc), len(file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto = out.File
	file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_goTypes = nil
	file_catalog_digitalocean_digitaloceanspaceskey_v1alpha1_spec_proto_depIdxs = nil
}
