load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "module",
    srcs = [
        "loadbalancer.go",
        "locals.go",
        "main.go",
        "outputs.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/openstack/openstackloadbalancer/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/openstack",
        "//catalog/openstack/openstackloadbalancer/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/openstack/pulumiopenstackprovider",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_openstack_sdk_v5//go/openstack",
        "@com_github_pulumi_pulumi_openstack_sdk_v5//go/openstack/loadbalancer",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
