// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awsecrregistrysettings/v1alpha1/spec.proto

package awsecrregistrysettingsv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsEcrRegistrySettingsSpec defines the REGISTRY-level ECR
// configuration for one AWS region: the registry permissions policy,
// scanning configuration, cross-region/cross-account replication,
// pull-through cache rules, repository creation templates, account
// settings, and pull-time update exclusions. Individual repositories
// are the AwsEcrRepo kind; everything here governs the registry all
// repositories in the region share.
//
// This is a SETTINGS SINGLETON: AWS keeps exactly one private
// registry per account+region, and this component manages its
// registry-wide posture. Deploy at most one instance per region -
// two instances targeting the same region fight over the same
// registry objects. metadata.name never reaches AWS (identity tags
// aside) - it is Planton-side identity only.
//
// Destroy semantics DIFFER per arm (each taught on its arm below):
// the registry policy and the keyed collections (cache rules,
// creation templates, exclusions) genuinely delete; scanning and
// replication RESET to their empty defaults; account settings
// PERSIST at their last-applied values.
type AwsEcrRegistrySettingsSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The AWS region whose registry this instance manages. The region
	// IS the resource identity - one instance per region. Example:
	// "us-west-2".
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// The registry permissions policy (JSON) - the IAM resource policy
	// that grants OTHER accounts registry-level actions: replication
	// into this registry (ecr:ReplicateImage) and pull-through cache
	// sharing. Repository-level grants belong on AwsEcrRepo's
	// repository policy instead. Destroying this arm deletes the
	// policy.
	RegistryPolicy string `protobuf:"bytes,2,opt,name=registry_policy,json=registryPolicy,proto3" json:"registry_policy,omitempty"`
	// How images in this registry are scanned for vulnerabilities.
	// Destroying this arm RESETS the registry to BASIC scanning with
	// no rules (AWS has no delete - the modules put the empty default
	// back).
	Scanning *AwsEcrRegistryScanning `protobuf:"bytes,3,opt,name=scanning,proto3" json:"scanning,omitempty"`
	// Where this registry replicates images, evaluated in order.
	// Cross-account destinations also need the DESTINATION registry's
	// policy to allow ecr:ReplicateImage from this account. AWS caps
	// the rules at 10. Destroying this arm RESETS replication to none
	// (AWS has no delete - the modules put the empty rule set back).
	ReplicationRules []*AwsEcrReplicationRule `protobuf:"bytes,4,rep,name=replication_rules,json=replicationRules,proto3" json:"replication_rules,omitempty"`
	// Pull-through cache rules, keyed by ecr_repository_prefix: pulls
	// of "{prefix}/..." transparently fetch from the upstream registry
	// and cache the image here. Destroying an entry deletes the rule
	// (already-cached repositories and images remain).
	PullThroughCacheRules []*AwsEcrPullThroughCacheRule `protobuf:"bytes,5,rep,name=pull_through_cache_rules,json=pullThroughCacheRules,proto3" json:"pull_through_cache_rules,omitempty"`
	// Templates applied to repositories the registry creates on your
	// behalf (replication, pull-through cache, or create-on-push),
	// keyed by prefix. Without a matching template such repositories
	// are created with bare defaults. Destroying an entry deletes the
	// template (repositories it already stamped keep their settings).
	RepositoryCreationTemplates []*AwsEcrRepositoryCreationTemplate `protobuf:"bytes,6,rep,name=repository_creation_templates,json=repositoryCreationTemplates,proto3" json:"repository_creation_templates,omitempty"`
	// Account-level ECR feature toggles. These PERSIST after destroy at
	// their last-applied values (AWS has no delete or reset for them) -
	// to change a value back, apply the desired value before
	// destroying.
	AccountSettings *AwsEcrAccountSettings `protobuf:"bytes,7,opt,name=account_settings,json=accountSettings,proto3" json:"account_settings,omitempty"`
	// IAM principals whose image pushes do NOT refresh pull-time
	// metrics, keyed by principal ARN - keeps automation (CI/CD roles,
	// replication roles) from masking real image usage in lifecycle
	// policies that expire by days-since-last-pull. Reference
	// AwsIamRole role_arn outputs or pass literal principal ARNs.
	// Destroying an entry deregisters the exclusion.
	PullTimeUpdateExclusions []*v1.StringValueOrRef `protobuf:"bytes,8,rep,name=pull_time_update_exclusions,json=pullTimeUpdateExclusions,proto3" json:"pull_time_update_exclusions,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AwsEcrRegistrySettingsSpec) Reset() {
	*x = AwsEcrRegistrySettingsSpec{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrRegistrySettingsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrRegistrySettingsSpec) ProtoMessage() {}

func (x *AwsEcrRegistrySettingsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrRegistrySettingsSpec.ProtoReflect.Descriptor instead.
func (*AwsEcrRegistrySettingsSpec) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AwsEcrRegistrySettingsSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AwsEcrRegistrySettingsSpec) GetRegistryPolicy() string {
	if x != nil {
		return x.RegistryPolicy
	}
	return ""
}

func (x *AwsEcrRegistrySettingsSpec) GetScanning() *AwsEcrRegistryScanning {
	if x != nil {
		return x.Scanning
	}
	return nil
}

func (x *AwsEcrRegistrySettingsSpec) GetReplicationRules() []*AwsEcrReplicationRule {
	if x != nil {
		return x.ReplicationRules
	}
	return nil
}

func (x *AwsEcrRegistrySettingsSpec) GetPullThroughCacheRules() []*AwsEcrPullThroughCacheRule {
	if x != nil {
		return x.PullThroughCacheRules
	}
	return nil
}

func (x *AwsEcrRegistrySettingsSpec) GetRepositoryCreationTemplates() []*AwsEcrRepositoryCreationTemplate {
	if x != nil {
		return x.RepositoryCreationTemplates
	}
	return nil
}

func (x *AwsEcrRegistrySettingsSpec) GetAccountSettings() *AwsEcrAccountSettings {
	if x != nil {
		return x.AccountSettings
	}
	return nil
}

func (x *AwsEcrRegistrySettingsSpec) GetPullTimeUpdateExclusions() []*v1.StringValueOrRef {
	if x != nil {
		return x.PullTimeUpdateExclusions
	}
	return nil
}

// AwsEcrRegistryScanning configures vulnerability scanning for the
// whole registry.
type AwsEcrRegistryScanning struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scanning engine: "BASIC" (the built-in scanner, OS packages
	// only, free) or "ENHANCED" (Amazon Inspector - OS + language
	// packages, continuous re-scanning, Inspector pricing applies).
	ScanType string `protobuf:"bytes,1,opt,name=scan_type,json=scanType,proto3" json:"scan_type,omitempty"`
	// Which repositories are scanned, and when. No matching rule means
	// no automatic scanning for that repository. AWS caps the rules at
	// 100.
	Rules         []*AwsEcrRegistryScanningRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEcrRegistryScanning) Reset() {
	*x = AwsEcrRegistryScanning{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrRegistryScanning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrRegistryScanning) ProtoMessage() {}

func (x *AwsEcrRegistryScanning) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrRegistryScanning.ProtoReflect.Descriptor instead.
func (*AwsEcrRegistryScanning) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *AwsEcrRegistryScanning) GetScanType() string {
	if x != nil {
		return x.ScanType
	}
	return ""
}

func (x *AwsEcrRegistryScanning) GetRules() []*AwsEcrRegistryScanningRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// AwsEcrRegistryScanningRule scans the repositories matching its
// filters at the given frequency.
type AwsEcrRegistryScanningRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When matched repositories are scanned: "SCAN_ON_PUSH" (each
	// pushed image once), "CONTINUOUS_SCAN" (re-scan as new CVEs
	// publish; ENHANCED only), or "MANUAL" (only on demand).
	ScanFrequency string `protobuf:"bytes,1,opt,name=scan_frequency,json=scanFrequency,proto3" json:"scan_frequency,omitempty"`
	// Repository name patterns this rule matches - "*" for every
	// repository, "prod-*" for a prefix. (AWS wildcard filters:
	// lowercase letters, digits, dot, underscore, hyphen, slash, and
	// "*".)
	Filters       []string `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEcrRegistryScanningRule) Reset() {
	*x = AwsEcrRegistryScanningRule{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrRegistryScanningRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrRegistryScanningRule) ProtoMessage() {}

func (x *AwsEcrRegistryScanningRule) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrRegistryScanningRule.ProtoReflect.Descriptor instead.
func (*AwsEcrRegistryScanningRule) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *AwsEcrRegistryScanningRule) GetScanFrequency() string {
	if x != nil {
		return x.ScanFrequency
	}
	return ""
}

func (x *AwsEcrRegistryScanningRule) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

// AwsEcrReplicationRule replicates this registry's images to one or
// more destination registries.
type AwsEcrReplicationRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where matched images are copied. AWS caps a rule at 25
	// destinations.
	Destinations []*AwsEcrReplicationDestination `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	// Replicate only repositories whose names start with these
	// prefixes. Empty replicates EVERY repository in the registry. AWS
	// caps the filters at 100.
	RepositoryFilters []string `protobuf:"bytes,2,rep,name=repository_filters,json=repositoryFilters,proto3" json:"repository_filters,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AwsEcrReplicationRule) Reset() {
	*x = AwsEcrReplicationRule{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrReplicationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrReplicationRule) ProtoMessage() {}

func (x *AwsEcrReplicationRule) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrReplicationRule.ProtoReflect.Descriptor instead.
func (*AwsEcrReplicationRule) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *AwsEcrReplicationRule) GetDestinations() []*AwsEcrReplicationDestination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *AwsEcrReplicationRule) GetRepositoryFilters() []string {
	if x != nil {
		return x.RepositoryFilters
	}
	return nil
}

// AwsEcrReplicationDestination is one region+account a replication
// rule copies images to.
type AwsEcrReplicationDestination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The destination region ("us-east-1"). Same-account cross-region,
	// or cross-account with registry_id.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// The destination registry's AWS account id. Your own account id
	// for cross-region replication; another account for cross-account
	// (that registry's policy must allow it).
	RegistryId    string `protobuf:"bytes,2,opt,name=registry_id,json=registryId,proto3" json:"registry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEcrReplicationDestination) Reset() {
	*x = AwsEcrReplicationDestination{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrReplicationDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrReplicationDestination) ProtoMessage() {}

func (x *AwsEcrReplicationDestination) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrReplicationDestination.ProtoReflect.Descriptor instead.
func (*AwsEcrReplicationDestination) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{4}
}

func (x *AwsEcrReplicationDestination) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AwsEcrReplicationDestination) GetRegistryId() string {
	if x != nil {
		return x.RegistryId
	}
	return ""
}

// AwsEcrPullThroughCacheRule caches an upstream registry under one
// repository prefix.
type AwsEcrPullThroughCacheRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The prefix pulls are cached under - "docker.io/library/nginx"
	// pulled as "{prefix}/library/nginx". "ROOT" caches at the
	// registry root (no prefix). The for_each key on both engines and
	// the rule's import ID. Fixed for life.
	EcrRepositoryPrefix string `protobuf:"bytes,1,opt,name=ecr_repository_prefix,json=ecrRepositoryPrefix,proto3" json:"ecr_repository_prefix,omitempty"`
	// The upstream registry's URL, e.g.
	// "registry-1.docker.io" (Docker Hub), "public.ecr.aws",
	// "ghcr.io", "registry.k8s.io", "quay.io", or another account's
	// "<account>.dkr.ecr.<region>.amazonaws.com". Fixed for life.
	UpstreamRegistryUrl string `protobuf:"bytes,2,opt,name=upstream_registry_url,json=upstreamRegistryUrl,proto3" json:"upstream_registry_url,omitempty"`
	// Re-root the upstream namespace: cache
	// "{upstream_repository_prefix}/..." instead of mirroring the
	// upstream's full paths. AWS requires 2-30 characters. Fixed for
	// life. (No min_len here - a zero-length floor keeps the field
	// OPTIONAL for the variables generator; AWS enforces the 2-char
	// minimum server-side.)
	UpstreamRepositoryPrefix string `protobuf:"bytes,3,opt,name=upstream_repository_prefix,json=upstreamRepositoryPrefix,proto3" json:"upstream_repository_prefix,omitempty"`
	// The Secrets Manager secret holding the upstream's credentials
	// (for authenticated upstreams like Docker Hub; the secret name
	// must start with "ecr-pullthroughcache/"). Reference an
	// AwsSecretsManagerSecret secret_arn output or pass a literal ARN.
	// NOTE: once set, clearing this back to empty is not propagated by
	// the provider - replace the rule to drop credentials.
	CredentialArn *v1.StringValueOrRef `protobuf:"bytes,4,opt,name=credential_arn,json=credentialArn,proto3" json:"credential_arn,omitempty"`
	// The IAM role this registry assumes to pull from a cross-account
	// ECR upstream. Reference an AwsIamRole role_arn output or pass a
	// literal ARN. The same clearing caveat as credential_arn applies.
	CustomRoleArn *v1.StringValueOrRef `protobuf:"bytes,5,opt,name=custom_role_arn,json=customRoleArn,proto3" json:"custom_role_arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEcrPullThroughCacheRule) Reset() {
	*x = AwsEcrPullThroughCacheRule{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrPullThroughCacheRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrPullThroughCacheRule) ProtoMessage() {}

func (x *AwsEcrPullThroughCacheRule) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrPullThroughCacheRule.ProtoReflect.Descriptor instead.
func (*AwsEcrPullThroughCacheRule) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{5}
}

func (x *AwsEcrPullThroughCacheRule) GetEcrRepositoryPrefix() string {
	if x != nil {
		return x.EcrRepositoryPrefix
	}
	return ""
}

func (x *AwsEcrPullThroughCacheRule) GetUpstreamRegistryUrl() string {
	if x != nil {
		return x.UpstreamRegistryUrl
	}
	return ""
}

func (x *AwsEcrPullThroughCacheRule) GetUpstreamRepositoryPrefix() string {
	if x != nil {
		return x.UpstreamRepositoryPrefix
	}
	return ""
}

func (x *AwsEcrPullThroughCacheRule) GetCredentialArn() *v1.StringValueOrRef {
	if x != nil {
		return x.CredentialArn
	}
	return nil
}

func (x *AwsEcrPullThroughCacheRule) GetCustomRoleArn() *v1.StringValueOrRef {
	if x != nil {
		return x.CustomRoleArn
	}
	return nil
}

// AwsEcrRepositoryCreationTemplate stamps settings onto repositories
// the registry creates automatically under one prefix.
type AwsEcrRepositoryCreationTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The repository-name prefix this template stamps - "ROOT" applies
	// to every auto-created repository without a more specific match.
	// The for_each key on both engines and the template's import ID.
	// Fixed for life.
	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// What this template is for.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Which auto-creation paths use this template: "REPLICATION"
	// (repositories created to receive replicated images),
	// "PULL_THROUGH_CACHE" (repositories created by cache pulls), or
	// "CREATE_ON_PUSH" (repositories created by a first push).
	AppliedFor []string `protobuf:"bytes,3,rep,name=applied_for,json=appliedFor,proto3" json:"applied_for,omitempty"`
	// The IAM role ECR assumes when creating repositories from this
	// template. Reference an AwsIamRole role_arn output or pass a
	// literal ARN.
	CustomRoleArn *v1.StringValueOrRef `protobuf:"bytes,4,opt,name=custom_role_arn,json=customRoleArn,proto3" json:"custom_role_arn,omitempty"`
	// Tag mutability for stamped repositories: "MUTABLE" (AWS's
	// default), "IMMUTABLE", or the *_WITH_EXCLUSION modes that carry
	// per-filter exceptions.
	ImageTagMutability string `protobuf:"bytes,5,opt,name=image_tag_mutability,json=imageTagMutability,proto3" json:"image_tag_mutability,omitempty"`
	// Tag patterns exempted from the mutability mode (e.g. "latest",
	// "dev-*"). Wildcard patterns, at most 2 "*" each, AWS caps the
	// list at 5.
	ImageTagMutabilityExclusionFilters []string `protobuf:"bytes,6,rep,name=image_tag_mutability_exclusion_filters,json=imageTagMutabilityExclusionFilters,proto3" json:"image_tag_mutability_exclusion_filters,omitempty"`
	// How stamped repositories encrypt images at rest. Omit for AES256
	// (the AWS default).
	Encryption *AwsEcrTemplateEncryption `protobuf:"bytes,7,opt,name=encryption,proto3" json:"encryption,omitempty"`
	// The lifecycle policy (JSON) stamped onto created repositories -
	// image expiration rules.
	LifecyclePolicy string `protobuf:"bytes,8,opt,name=lifecycle_policy,json=lifecyclePolicy,proto3" json:"lifecycle_policy,omitempty"`
	// The repository permissions policy (JSON) stamped onto created
	// repositories.
	RepositoryPolicy string `protobuf:"bytes,9,opt,name=repository_policy,json=repositoryPolicy,proto3" json:"repository_policy,omitempty"`
	// AWS tags stamped onto created repositories (these are the
	// repositories' tags, not this template's).
	ResourceTags  map[string]string `protobuf:"bytes,10,rep,name=resource_tags,json=resourceTags,proto3" json:"resource_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEcrRepositoryCreationTemplate) Reset() {
	*x = AwsEcrRepositoryCreationTemplate{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrRepositoryCreationTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrRepositoryCreationTemplate) ProtoMessage() {}

func (x *AwsEcrRepositoryCreationTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrRepositoryCreationTemplate.ProtoReflect.Descriptor instead.
func (*AwsEcrRepositoryCreationTemplate) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{6}
}

func (x *AwsEcrRepositoryCreationTemplate) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AwsEcrRepositoryCreationTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AwsEcrRepositoryCreationTemplate) GetAppliedFor() []string {
	if x != nil {
		return x.AppliedFor
	}
	return nil
}

func (x *AwsEcrRepositoryCreationTemplate) GetCustomRoleArn() *v1.StringValueOrRef {
	if x != nil {
		return x.CustomRoleArn
	}
	return nil
}

func (x *AwsEcrRepositoryCreationTemplate) GetImageTagMutability() string {
	if x != nil {
		return x.ImageTagMutability
	}
	return ""
}

func (x *AwsEcrRepositoryCreationTemplate) GetImageTagMutabilityExclusionFilters() []string {
	if x != nil {
		return x.ImageTagMutabilityExclusionFilters
	}
	return nil
}

func (x *AwsEcrRepositoryCreationTemplate) GetEncryption() *AwsEcrTemplateEncryption {
	if x != nil {
		return x.Encryption
	}
	return nil
}

func (x *AwsEcrRepositoryCreationTemplate) GetLifecyclePolicy() string {
	if x != nil {
		return x.LifecyclePolicy
	}
	return ""
}

func (x *AwsEcrRepositoryCreationTemplate) GetRepositoryPolicy() string {
	if x != nil {
		return x.RepositoryPolicy
	}
	return ""
}

func (x *AwsEcrRepositoryCreationTemplate) GetResourceTags() map[string]string {
	if x != nil {
		return x.ResourceTags
	}
	return nil
}

// AwsEcrTemplateEncryption is the at-rest encryption stamped
// repositories use.
type AwsEcrTemplateEncryption struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The encryption mode: "AES256" (Amazon-managed, the default),
	// "KMS" (your key, single-layer), or "KMS_DSSE" (your key,
	// dual-layer).
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The KMS key for KMS/KMS_DSSE modes. Reference an AwsKmsKey
	// key_arn output or pass a literal key ARN. Empty with a KMS mode
	// uses the AWS-managed aws/ecr key.
	KmsKey        *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=kms_key,json=kmsKey,proto3" json:"kms_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEcrTemplateEncryption) Reset() {
	*x = AwsEcrTemplateEncryption{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrTemplateEncryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrTemplateEncryption) ProtoMessage() {}

func (x *AwsEcrTemplateEncryption) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrTemplateEncryption.ProtoReflect.Descriptor instead.
func (*AwsEcrTemplateEncryption) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{7}
}

func (x *AwsEcrTemplateEncryption) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AwsEcrTemplateEncryption) GetKmsKey() *v1.StringValueOrRef {
	if x != nil {
		return x.KmsKey
	}
	return nil
}

// AwsEcrAccountSettings are the account-level ECR feature toggles for
// the region.
type AwsEcrAccountSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which engine BASIC scanning uses: "AWS_NATIVE" (the current
	// Amazon scanner) or "CLAIR" (the legacy scanner, on its way out).
	// Unset leaves the account's current setting.
	BasicScanTypeVersion string `protobuf:"bytes,1,opt,name=basic_scan_type_version,json=basicScanTypeVersion,proto3" json:"basic_scan_type_version,omitempty"`
	// Whether layer blob mounting between repositories is enabled
	// (faster pushes of images sharing base layers). Unset leaves the
	// account's current setting.
	BlobMounting *bool `protobuf:"varint,2,opt,name=blob_mounting,json=blobMounting,proto3,oneof" json:"blob_mounting,omitempty"`
	// The registry policy permission scope: "V2" (current semantics -
	// registry policies grant only registry-level actions) or "V1"
	// (legacy). Unset leaves the account's current setting.
	RegistryPolicyScope string `protobuf:"bytes,3,opt,name=registry_policy_scope,json=registryPolicyScope,proto3" json:"registry_policy_scope,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AwsEcrAccountSettings) Reset() {
	*x = AwsEcrAccountSettings{}
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEcrAccountSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEcrAccountSettings) ProtoMessage() {}

func (x *AwsEcrAccountSettings) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEcrAccountSettings.ProtoReflect.Descriptor instead.
func (*AwsEcrAccountSettings) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP(), []int{8}
}

func (x *AwsEcrAccountSettings) GetBasicScanTypeVersion() string {
	if x != nil {
		return x.BasicScanTypeVersion
	}
	return ""
}

func (x *AwsEcrAccountSettings) GetBlobMounting() bool {
	if x != nil && x.BlobMounting != nil {
		return *x.BlobMounting
	}
	return false
}

func (x *AwsEcrAccountSettings) GetRegistryPolicyScope() string {
	if x != nil {
		return x.RegistryPolicyScope
	}
	return ""
}

var File_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"6catalog/aws/awsecrregistrysettings/v1alpha1/spec.proto\x12/dev.planton.aws.awsecrregistrysettings.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\"\xd6\x0f\n" +
	"\x1aAwsEcrRegistrySettingsSpec\x12\x1f\n" +
	"\x06region\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06region\x12\xc8\x01\n" +
	"\x0fregistry_policy\x18\x02 \x01(\tB\x9e\x01\xbaH\x9a\x01\xba\x01\x93\x01\n" +
	"\x1fspec.registry_policy_valid_json\x124registry_policy must be a valid JSON policy document\x1a:this == '' || (this.startsWith('{') && this.endsWith('}'))\xd8\x01\x01R\x0eregistryPolicy\x12c\n" +
	"\bscanning\x18\x03 \x01(\v2G.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistryScanningR\bscanning\x12}\n" +
	"\x11replication_rules\x18\x04 \x03(\v2F.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrReplicationRuleB\b\xbaH\x05\x92\x01\x02\x10\n" +
	"R\x10replicationRules\x12\x84\x01\n" +
	"\x18pull_through_cache_rules\x18\x05 \x03(\v2K.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrPullThroughCacheRuleR\x15pullThroughCacheRules\x12\x95\x01\n" +
	"\x1drepository_creation_templates\x18\x06 \x03(\v2Q.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplateR\x1brepositoryCreationTemplates\x12q\n" +
	"\x10account_settings\x18\a \x01(\v2F.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrAccountSettingsR\x0faccountSettings\x12\x93\x01\n" +
	"\x1bpull_time_update_exclusions\x18\b \x03(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB \x88\xd4a\xf0\a\x92\xd4a\x17status.outputs.role_arnR\x18pullTimeUpdateExclusions:\xbf\a\xbaH\xbb\a\x1a\x88\x04\n" +
	"\x15spec.at_least_one_arm\x12\xec\x01configure at least one arm (registry_policy / scanning / replication_rules / pull_through_cache_rules / repository_creation_templates / account_settings / pull_time_update_exclusions) - an instance managing nothing is dead configuration\x1a\xff\x01this.registry_policy != '' || has(this.scanning) || this.replication_rules.size() > 0 || this.pull_through_cache_rules.size() > 0 || this.repository_creation_templates.size() > 0 || has(this.account_settings) || this.pull_time_update_exclusions.size() > 0\x1a\xd2\x01\n" +
	"\x1fspec.cache_rule_prefixes_unique\x12gpull_through_cache_rules prefixes must be unique - each rule owns one repository prefix in the registry\x1aFthis.pull_through_cache_rules.map(r, r.ecr_repository_prefix).unique()\x1a\xd8\x01\n" +
	"&spec.creation_template_prefixes_unique\x12prepository_creation_templates prefixes must be unique - each template owns one repository prefix in the registry\x1a<this.repository_creation_templates.map(t, t.prefix).unique()\"\xb1\x03\n" +
	"\x16AwsEcrRegistryScanning\x123\n" +
	"\tscan_type\x18\x01 \x01(\tB\x16\xbaH\x13r\x11R\x05BASICR\bENHANCEDR\bscanType\x12k\n" +
	"\x05rules\x18\x02 \x03(\v2K.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistryScanningRuleB\b\xbaH\x05\x92\x01\x02\x10dR\x05rules:\xf4\x01\xbaH\xf0\x01\x1a\xed\x01\n" +
	"%scanning.continuous_requires_enhanced\x12jscan_frequency CONTINUOUS_SCAN requires scan_type ENHANCED - basic scanning only scans on push or manually\x1aXthis.scan_type == 'ENHANCED' || this.rules.all(r, r.scan_frequency != 'CONTINUOUS_SCAN')\"\xca\x01\n" +
	"\x1aAwsEcrRegistryScanningRule\x12S\n" +
	"\x0escan_frequency\x18\x01 \x01(\tB,\xbaH)r'R\fSCAN_ON_PUSHR\x0fCONTINUOUS_SCANR\x06MANUALR\rscanFrequency\x12W\n" +
	"\afilters\x18\x02 \x03(\tB=\xbaH:\x92\x017\b\x01\x18\x01\"1r/\x10\x01\x18\x80\x022(^[0-9a-z*](?:[0-9a-z_./*-]?[0-9a-z*]+)*$R\afilters\"\xda\x01\n" +
	"\x15AwsEcrReplicationRule\x12}\n" +
	"\fdestinations\x18\x01 \x03(\v2M.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrReplicationDestinationB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10\x19R\fdestinations\x12B\n" +
	"\x12repository_filters\x18\x02 \x03(\tB\x13\xbaH\x10\x92\x01\r\x10d\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\x11repositoryFilters\"\x8d\x01\n" +
	"\x1cAwsEcrReplicationDestination\x128\n" +
	"\x06region\x18\x01 \x01(\tB \xbaH\x1dr\x1b\x10\x012\x17^[a-z]{2}(-[a-z]+)+-\\d$R\x06region\x123\n" +
	"\vregistry_id\x18\x02 \x01(\tB\x12\xbaH\x0fr\r2\v^[0-9]{12}$R\n" +
	"registryId\"\xf3\x06\n" +
	"\x1aAwsEcrPullThroughCacheRule\x12\x88\x01\n" +
	"\x15ecr_repository_prefix\x18\x01 \x01(\tBT\xbaHQrO\x10\x02\x18\x1e2I^((?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*/?|ROOT)$R\x13ecrRepositoryPrefix\x12;\n" +
	"\x15upstream_registry_url\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x13upstreamRegistryUrl\x12\x93\x01\n" +
	"\x1aupstream_repository_prefix\x18\x03 \x01(\tBU\xbaHR\xd8\x01\x01rM\x18\x1e2I^((?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*/?|ROOT)$R\x18upstreamRepositoryPrefix\x12}\n" +
	"\x0ecredential_arn\x18\x04 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\"\x88\xd4a\x9c\t\x92\xd4a\x19status.outputs.secret_arnR\rcredentialArn\x12|\n" +
	"\x0fcustom_role_arn\x18\x05 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB \x88\xd4a\xf0\a\x92\xd4a\x17status.outputs.role_arnR\rcustomRoleArn:\xf9\x01\xbaH\xf5\x01\x1a\xf2\x01\n" +
	"%cache_rule.credential_xor_custom_role\x12\x8e\x01set at most one of credential_arn (external upstreams - Docker Hub, GitHub, Kubernetes, ...) and custom_role_arn (cross-account ECR upstreams)\x1a8!(has(this.credential_arn) && has(this.custom_role_arn))\"\xbb\x0f\n" +
	" AwsEcrRepositoryCreationTemplate\x12k\n" +
	"\x06prefix\x18\x01 \x01(\tBS\xbaHPrN\x10\x02\x18\x80\x022G^(ROOT|(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*)$R\x06prefix\x12-\n" +
	"\vdescription\x18\x02 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\x18\xff\x01R\vdescription\x12`\n" +
	"\vapplied_for\x18\x03 \x03(\tB?\xbaH<\x92\x019\b\x01\x18\x01\"3r1R\vREPLICATIONR\x12PULL_THROUGH_CACHER\x0eCREATE_ON_PUSHR\n" +
	"appliedFor\x12|\n" +
	"\x0fcustom_role_arn\x18\x04 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB \x88\xd4a\xf0\a\x92\xd4a\x17status.outputs.role_arnR\rcustomRoleArn\x12\x80\x01\n" +
	"\x14image_tag_mutability\x18\x05 \x01(\tBN\xbaHK\xd8\x01\x01rFR\aMUTABLER\tIMMUTABLER\x18IMMUTABLE_WITH_EXCLUSIONR\x16MUTABLE_WITH_EXCLUSIONR\x12imageTagMutability\x12{\n" +
	"&image_tag_mutability_exclusion_filters\x18\x06 \x03(\tB'\xbaH$\x92\x01!\x10\x05\x18\x01\"\x1br\x19\x10\x01\x18\x80\x012\x12^[a-zA-Z0-9._*-]+$R\"imageTagMutabilityExclusionFilters\x12i\n" +
	"\n" +
	"encryption\x18\a \x01(\v2I.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrTemplateEncryptionR\n" +
	"encryption\x12\xda\x01\n" +
	"\x10lifecycle_policy\x18\b \x01(\tB\xae\x01\xbaH\xaa\x01\xba\x01\xa3\x01\n" +
	"$template.lifecycle_policy_valid_json\x12?lifecycle_policy must be a valid JSON lifecycle policy document\x1a:this == '' || (this.startsWith('{') && this.endsWith('}'))\xd8\x01\x01R\x0flifecyclePolicy\x12\xd4\x01\n" +
	"\x11repository_policy\x18\t \x01(\tB\xa6\x01\xbaH\xa2\x01\xba\x01\x9b\x01\n" +
	"%template.repository_policy_valid_json\x126repository_policy must be a valid JSON policy document\x1a:this == '' || (this.startsWith('{') && this.endsWith('}'))\xd8\x01\x01R\x10repositoryPolicy\x12\xa0\x01\n" +
	"\rresource_tags\x18\n" +
	" \x03(\v2c.dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate.ResourceTagsEntryB\x16\xbaH\x13\x9a\x01\x10\"\ar\x05\x10\x01\x18\x80\x01*\x05r\x03\x18\x80\x02R\fresourceTags\x1a?\n" +
	"\x11ResourceTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x97\x04\xbaH\x93\x04\x1a\xc3\x02\n" +
	"7template.exclusion_filters_require_exclusion_mutability\x12wimage_tag_mutability_exclusion_filters requires image_tag_mutability IMMUTABLE_WITH_EXCLUSION or MUTABLE_WITH_EXCLUSION\x1a\x8e\x01this.image_tag_mutability_exclusion_filters.size() == 0 || this.image_tag_mutability in ['IMMUTABLE_WITH_EXCLUSION', 'MUTABLE_WITH_EXCLUSION']\x1a\xca\x01\n" +
	",template.exclusion_filters_max_two_wildcards\x12Lan image_tag_mutability exclusion filter can contain at most 2 wildcards (*)\x1aLthis.image_tag_mutability_exclusion_filters.all(f, f.split('*').size() <= 3)\"\xfc\x02\n" +
	"\x18AwsEcrTemplateEncryption\x123\n" +
	"\x04type\x18\x01 \x01(\tB\x1f\xbaH\x1c\xd8\x01\x01r\x17R\x06AES256R\x03KMSR\bKMS_DSSER\x04type\x12l\n" +
	"\akms_key\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x1f\x88\xd4a\xfb\a\x92\xd4a\x16status.outputs.key_arnR\x06kmsKey:\xbc\x01\xbaH\xb8\x01\x1a\xb5\x01\n" +
	"$encryption.kms_key_requires_kms_type\x12Ukms_key applies only when type is KMS or KMS_DSSE - AES256 uses an Amazon-managed key\x1a6!has(this.kms_key) || this.type in ['KMS', 'KMS_DSSE']\"\xed\x01\n" +
	"\x15AwsEcrAccountSettings\x12R\n" +
	"\x17basic_scan_type_version\x18\x01 \x01(\tB\x1b\xbaH\x18\xd8\x01\x01r\x13R\n" +
	"AWS_NATIVER\x05CLAIRR\x14basicScanTypeVersion\x12(\n" +
	"\rblob_mounting\x18\x02 \x01(\bH\x00R\fblobMounting\x88\x01\x01\x12D\n" +
	"\x15registry_policy_scope\x18\x03 \x01(\tB\x10\xbaH\r\xd8\x01\x01r\bR\x02V1R\x02V2R\x13registryPolicyScopeB\x10\n" +
	"\x0e_blob_mountingB\x8a\x03\n" +
	"3com.dev.planton.aws.awsecrregistrysettings.v1alpha1B\tSpecProtoP\x01Zggithub.com/plantonhq/planton/catalog/aws/awsecrregistrysettings/v1alpha1;awsecrregistrysettingsv1alpha1\xa2\x02\x04DPAA\xaa\x02/Dev.Planton.Aws.Awsecrregistrysettings.V1alpha1\xca\x02/Dev\\Planton\\Aws\\Awsecrregistrysettings\\V1alpha1\xe2\x02;Dev\\Planton\\Aws\\Awsecrregistrysettings\\V1alpha1\\GPBMetadata\xea\x023Dev::Planton::Aws::Awsecrregistrysettings::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDesc), len(file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDescData
}

var file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_goTypes = []any{
	(*AwsEcrRegistrySettingsSpec)(nil),       // 0: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistrySettingsSpec
	(*AwsEcrRegistryScanning)(nil),           // 1: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistryScanning
	(*AwsEcrRegistryScanningRule)(nil),       // 2: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistryScanningRule
	(*AwsEcrReplicationRule)(nil),            // 3: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrReplicationRule
	(*AwsEcrReplicationDestination)(nil),     // 4: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrReplicationDestination
	(*AwsEcrPullThroughCacheRule)(nil),       // 5: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrPullThroughCacheRule
	(*AwsEcrRepositoryCreationTemplate)(nil), // 6: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate
	(*AwsEcrTemplateEncryption)(nil),         // 7: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrTemplateEncryption
	(*AwsEcrAccountSettings)(nil),            // 8: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrAccountSettings
	nil,                                      // 9: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate.ResourceTagsEntry
	(*v1.StringValueOrRef)(nil),              // 10: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_depIdxs = []int32{
	1,  // 0: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistrySettingsSpec.scanning:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistryScanning
	3,  // 1: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistrySettingsSpec.replication_rules:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrReplicationRule
	5,  // 2: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistrySettingsSpec.pull_through_cache_rules:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrPullThroughCacheRule
	6,  // 3: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistrySettingsSpec.repository_creation_templates:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate
	8,  // 4: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistrySettingsSpec.account_settings:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrAccountSettings
	10, // 5: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistrySettingsSpec.pull_time_update_exclusions:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2,  // 6: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistryScanning.rules:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRegistryScanningRule
	4,  // 7: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrReplicationRule.destinations:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrReplicationDestination
	10, // 8: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrPullThroughCacheRule.credential_arn:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	10, // 9: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrPullThroughCacheRule.custom_role_arn:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	10, // 10: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate.custom_role_arn:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	7,  // 11: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate.encryption:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrTemplateEncryption
	9,  // 12: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate.resource_tags:type_name -> dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrRepositoryCreationTemplate.ResourceTagsEntry
	10, // 13: dev.planton.aws.awsecrregistrysettings.v1alpha1.AwsEcrTemplateEncryption.kms_key:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_init() }
func file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_init() {
	if File_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDesc), len(file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto = out.File
	file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_goTypes = nil
	file_catalog_aws_awsecrregistrysettings_v1alpha1_spec_proto_depIdxs = nil
}
