syntax = "proto3";

package dev.planton.alicloud.alicloudrdsinstance.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/alicloud/alicloudrdsinstance/v1alpha1/spec.proto";
import "catalog/alicloud/alicloudrdsinstance/v1alpha1/stack_outputs.proto";
import "shared/metadata.proto";

// alicloud-rds-instance
message AliCloudRdsInstance {
  // api-version
  string api_version = 1 [(buf.validate.field).string.const = 'alicloud.planton.dev/v1alpha1'];

  // resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AliCloudRdsInstance'];

  // metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  // spec
  AliCloudRdsInstanceSpec spec = 4 [(buf.validate.field).required = true];

  // status
  AliCloudRdsInstanceStatus status = 5;
}

// alicloud-rds-instance status
message AliCloudRdsInstanceStatus {
  // stack-outputs
  AliCloudRdsInstanceStackOutputs outputs = 1;
}
