apiVersion: kubernetes.planton.dev/v1alpha1
kind: KubernetesRequestAuthentication
metadata:
  name: jwt-auth
spec:
  namespace:
    value: <namespace>
  jwt_rules:
    - issuer: https://accounts.example.com
      jwks_uri: https://accounts.example.com/.well-known/jwks.json
