apiVersion: digital-ocean.planton.dev/v1alpha1
kind: DigitalOceanFunction
metadata:
  name: hello
spec:
  functionName: hello
  region: nyc3
  git:
    repoCloneUrl: https://github.com/digitalocean/sample-functions-nodejs-helloworld.git
    branch: master
  sourceDirectory: packages
  envs:
    - key: NODE_ENV
      plaintext: production
