syntax = "proto3";

package dev.planton.hetznercloud.hetznercloudfloatingip.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/hetznercloud/hetznercloudfloatingip/v1alpha1/spec.proto";
import "catalog/hetznercloud/hetznercloudfloatingip/v1alpha1/stack_outputs.proto";
import "shared/metadata.proto";

// hetznercloud-floating-ip
message HetznerCloudFloatingIp {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = "hetzner-cloud.planton.dev/v1alpha1"];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = "HetznerCloudFloatingIp"];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  HetznerCloudFloatingIpSpec spec = 4 [(buf.validate.field).required = true];

  //status
  HetznerCloudFloatingIpStatus status = 5;
}

// hetznercloud-floating-ip status
message HetznerCloudFloatingIpStatus {
  //stack-outputs
  //  hetznercloud-floating-ip stack-outputs
  HetznerCloudFloatingIpStackOutputs outputs = 1;
}
