syntax = "proto3";

package dev.planton.provider.azure.azuremonitoractiongroup.v1alpha1;

import "dev/planton/provider/azure/azuremonitoractiongroup/v1alpha1/api.proto";
import "dev/planton/provider/azure/provider.proto";

// AzureMonitorActionGroupStackInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureMonitorActionGroupStackInput {
  // target cloud-resource to be deployed
  AzureMonitorActionGroup target = 1;
  // provider-config for Azure authentication
  dev.planton.provider.azure.AzureProviderConfig provider_config = 2;
}
