apiVersion: azure.planton.dev/v1alpha1
kind: AzureVirtualHub
metadata:
  name: my-hub
spec:
  region: <azure-region>
  resourceGroup:
    value: "<your-resource-group-name>"
  name: my-hub
  virtualWanId:
    value: "<your-virtual-wan-arm-id>"
  addressPrefix: "10.100.0.0/23"
  routingIntent:
    name: hubRoutingIntent
    routingPolicies:
      - name: InternetTraffic
        destinations:
          - INTERNET
        nextHop:
          value: "<your-hub-firewall-arm-id>"
      - name: PrivateTrafficPolicy
        destinations:
          - PRIVATE_TRAFFIC
        nextHop:
          value: "<your-hub-firewall-arm-id>"
