// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/azure/azurestoragetable/v1/api.proto

package azurestoragetablev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/apis/dev/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureStorageTable is the top-level API resource for a Storage table --
// the serverless NoSQL key/value store of Azure storage, living inside
// an AzureStorageAccount (referenced via storage_account_id).
// Applications store schemaless entities by partition + row key; stored
// access policies are set per table.
type AzureStorageTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *AzureStorageTableSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *AzureStorageTableStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureStorageTable) Reset() {
	*x = AzureStorageTable{}
	mi := &file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureStorageTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureStorageTable) ProtoMessage() {}

func (x *AzureStorageTable) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureStorageTable.ProtoReflect.Descriptor instead.
func (*AzureStorageTable) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AzureStorageTable) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AzureStorageTable) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AzureStorageTable) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AzureStorageTable) GetSpec() *AzureStorageTableSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AzureStorageTable) GetStatus() *AzureStorageTableStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AzureStorageTableStatus holds the deployment status and outputs.
type AzureStorageTableStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *AzureStorageTableStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureStorageTableStatus) Reset() {
	*x = AzureStorageTableStatus{}
	mi := &file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureStorageTableStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureStorageTableStatus) ProtoMessage() {}

func (x *AzureStorageTableStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureStorageTableStatus.ProtoReflect.Descriptor instead.
func (*AzureStorageTableStatus) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AzureStorageTableStatus) GetOutputs() *AzureStorageTableStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_dev_planton_provider_azure_azurestoragetable_v1_api_proto protoreflect.FileDescriptor

const file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDesc = "" +
	"\n" +
	"9dev/planton/provider/azure/azurestoragetable/v1/api.proto\x12/dev.planton.provider.azure.azurestoragetable.v1\x1a\x1bbuf/validate/validate.proto\x1a:dev/planton/provider/azure/azurestoragetable/v1/spec.proto\x1aCdev/planton/provider/azure/azurestoragetable/v1/stack_outputs.proto\x1a!dev/planton/shared/metadata.proto\"\x94\x03\n" +
	"\x11AzureStorageTable\x12<\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\n" +
	"\x14azure.planton.dev/v1R\n" +
	"apiVersion\x12,\n" +
	"\x04kind\x18\x02 \x01(\tB\x18\xbaH\x15r\x13\n" +
	"\x11AzureStorageTableR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12b\n" +
	"\x04spec\x18\x04 \x01(\v2F.dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12`\n" +
	"\x06status\x18\x05 \x01(\v2H.dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableStatusR\x06status\"\x83\x01\n" +
	"\x17AzureStorageTableStatus\x12h\n" +
	"\aoutputs\x18\x01 \x01(\v2N.dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableStackOutputsR\aoutputsB\x89\x03\n" +
	"3com.dev.planton.provider.azure.azurestoragetable.v1B\bApiProtoP\x01Zegithub.com/plantonhq/planton/apis/dev/planton/provider/azure/azurestoragetable/v1;azurestoragetablev1\xa2\x02\x05DPPAA\xaa\x02/Dev.Planton.Provider.Azure.Azurestoragetable.V1\xca\x02/Dev\\Planton\\Provider\\Azure\\Azurestoragetable\\V1\xe2\x02;Dev\\Planton\\Provider\\Azure\\Azurestoragetable\\V1\\GPBMetadata\xea\x024Dev::Planton::Provider::Azure::Azurestoragetable::V1b\x06proto3"

var (
	file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescOnce sync.Once
	file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescData []byte
)

func file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDesc), len(file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDesc)))
	})
	return file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDescData
}

var file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_goTypes = []any{
	(*AzureStorageTable)(nil),             // 0: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTable
	(*AzureStorageTableStatus)(nil),       // 1: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableStatus
	(*shared.CloudResourceMetadata)(nil),  // 2: dev.planton.shared.CloudResourceMetadata
	(*AzureStorageTableSpec)(nil),         // 3: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableSpec
	(*AzureStorageTableStackOutputs)(nil), // 4: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableStackOutputs
}
var file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTable.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTable.spec:type_name -> dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableSpec
	1, // 2: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTable.status:type_name -> dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableStatus
	4, // 3: dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableStatus.outputs:type_name -> dev.planton.provider.azure.azurestoragetable.v1.AzureStorageTableStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_init() }
func file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_init() {
	if File_dev_planton_provider_azure_azurestoragetable_v1_api_proto != nil {
		return
	}
	file_dev_planton_provider_azure_azurestoragetable_v1_spec_proto_init()
	file_dev_planton_provider_azure_azurestoragetable_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDesc), len(file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_azure_azurestoragetable_v1_api_proto = out.File
	file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_goTypes = nil
	file_dev_planton_provider_azure_azurestoragetable_v1_api_proto_depIdxs = nil
}
