load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "karpenter",
    srcs = [
        "ec2nodeClass.go",
        "ec2nodeClassList.go",
        "ec2nodeClassPatch.go",
        "init.go",
        "nodePool.go",
        "nodePoolList.go",
        "nodePoolPatch.go",
        "pulumiTypes.go",
    ],
    importpath = "github.com/plantonhq/planton/pkg/kubernetes/kubernetestypes/karpenter/kubernetes/karpenter/v1",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_blang_semver//:semver",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/meta/v1:meta",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/utilities",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
