// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpspannerbackupschedule/v1alpha1/spec.proto

package gcpspannerbackupschedulev1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	_ "github.com/plantonhq/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GcpSpannerBackupScheduleEncryptionConfig controls how the backups created
// by this schedule are encrypted.
//
//   - USE_DATABASE_ENCRYPTION (the operational default): backups inherit
//     the database's own posture — CMEK databases get CMEK backups.
//   - GOOGLE_DEFAULT_ENCRYPTION: Google-managed keys regardless of the
//     database's posture.
//   - CUSTOMER_MANAGED_ENCRYPTION: explicit CMEK for the backups — set
//     exactly one of kms_key_name (regional instance configurations) or
//     kms_key_names (one key per region of a multi-region configuration).
type GcpSpannerBackupScheduleEncryptionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How backups are encrypted. Required when this message is present.
	EncryptionType string `protobuf:"bytes,1,opt,name=encryption_type,json=encryptionType,proto3" json:"encryption_type,omitempty"`
	// Fully qualified KMS key for single-region backup CMEK.
	// Format: projects/{project}/locations/{location}/keyRings/{ring}/cryptoKeys/{key}
	// Only valid with CUSTOMER_MANAGED_ENCRYPTION.
	KmsKeyName *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=kms_key_name,json=kmsKeyName,proto3" json:"kms_key_name,omitempty"`
	// Fully qualified KMS keys for multi-region backup CMEK — one key per
	// region of the instance's multi-region configuration.
	// Only valid with CUSTOMER_MANAGED_ENCRYPTION.
	KmsKeyNames   []*v1.StringValueOrRef `protobuf:"bytes,3,rep,name=kms_key_names,json=kmsKeyNames,proto3" json:"kms_key_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpSpannerBackupScheduleEncryptionConfig) Reset() {
	*x = GcpSpannerBackupScheduleEncryptionConfig{}
	mi := &file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpSpannerBackupScheduleEncryptionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpSpannerBackupScheduleEncryptionConfig) ProtoMessage() {}

func (x *GcpSpannerBackupScheduleEncryptionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpSpannerBackupScheduleEncryptionConfig.ProtoReflect.Descriptor instead.
func (*GcpSpannerBackupScheduleEncryptionConfig) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *GcpSpannerBackupScheduleEncryptionConfig) GetEncryptionType() string {
	if x != nil {
		return x.EncryptionType
	}
	return ""
}

func (x *GcpSpannerBackupScheduleEncryptionConfig) GetKmsKeyName() *v1.StringValueOrRef {
	if x != nil {
		return x.KmsKeyName
	}
	return nil
}

func (x *GcpSpannerBackupScheduleEncryptionConfig) GetKmsKeyNames() []*v1.StringValueOrRef {
	if x != nil {
		return x.KmsKeyNames
	}
	return nil
}

// GcpSpannerBackupScheduleSpec defines a backup schedule
// (`google_spanner_backup_schedule`) on a Cloud Spanner database.
//
// A backup schedule creates backups of one database on a cron cadence and
// retains each backup for retention_duration. Schedules are first-class,
// many-per-database resources: a database commonly carries a daily
// incremental schedule AND a weekly full schedule side by side.
//
// Important behavioral notes:
//
//   - The schedule is OWNED BY the database: deleting the database deletes
//     its schedules. The BACKUPS themselves survive — they live until
//     their retention expires and are what makes destroying the instance
//     fail unless GcpSpannerInstance.force_destroy is set.
//
//   - schedule_name, instance, database, and backup_type are immutable;
//     cron, retention, and encryption update in place.
//
//   - INCREMENTAL schedules build chains where each backup stores only
//     changes since the previous one (cheaper storage, same restore
//     semantics) and require the instance to be ENTERPRISE or
//     ENTERPRISE_PLUS edition.
type GcpSpannerBackupScheduleSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The GCP project that owns the parent Spanner instance. Accepts a
	// literal project ID or a reference to a GcpProject resource. If
	// omitted, the provider's default project is used.
	// Immutable: changing the project destroys and recreates the schedule.
	ProjectId *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The Spanner instance hosting the database. Immutable.
	Instance *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// The database this schedule backs up. Immutable.
	Database *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	// Unique name of the backup schedule within the database. Immutable.
	// If not specified, defaults to metadata.name. Must start with a
	// lowercase letter, contain lowercase letters, digits, and hyphens, and
	// end with a letter or digit.
	ScheduleName string `protobuf:"bytes,4,opt,name=schedule_name,json=scheduleName,proto3" json:"schedule_name,omitempty"`
	// Crontab expression for when backups are created, evaluated in UTC
	// (maps to the provider's spec.cron_spec.text). Spanner accepts a
	// bounded set of frequencies — every 12 hours, daily, weekly, or
	// monthly. Examples:
	//
	//	"0 2/12 * * *" — every 12 hours at 02:00 and 14:00 UTC
	//	"0 2 * * *"    — daily at 02:00 UTC
	//	"0 2 * * 0"    — weekly on Sunday at 02:00 UTC
	//	"0 2 8 * *"    — monthly on the 8th at 02:00 UTC
	//
	// Mutable — cadence changes apply in place.
	Cron string `protobuf:"bytes,5,opt,name=cron,proto3" json:"cron,omitempty"`
	// How long each backup is retained, as a seconds duration string ending
	// in 's' (e.g. "86400s" = 1 day, "2678400s" = 31 days). Maximum 366 days
	// ("31622400s"). Mutable — applies to backups created AFTER the change.
	RetentionDuration string `protobuf:"bytes,6,opt,name=retention_duration,json=retentionDuration,proto3" json:"retention_duration,omitempty"`
	// The kind of backups the schedule creates. Immutable.
	//
	// FULL (default): every backup is a complete, self-contained copy.
	//
	// INCREMENTAL: backups form chains storing only changes since the
	// previous backup — significantly cheaper storage at the same restore
	// semantics. Requires the instance to be ENTERPRISE or ENTERPRISE_PLUS
	// edition.
	BackupType *string `protobuf:"bytes,7,opt,name=backup_type,json=backupType,proto3,oneof" json:"backup_type,omitempty"`
	// How the backups are encrypted. If omitted, backups use
	// USE_DATABASE_ENCRYPTION (inherit the database's posture). Mutable.
	EncryptionConfig *GcpSpannerBackupScheduleEncryptionConfig `protobuf:"bytes,8,opt,name=encryption_config,json=encryptionConfig,proto3" json:"encryption_config,omitempty"`
	// Deletion policy for the schedule — what happens when this resource
	// is destroyed. The schedule is a control-plane object: none of these
	// values touches the BACKUPS it already created (those live until
	// their retention expires):
	//
	//	""        -- same as "DELETE" (provider default)
	//	"DELETE"  -- the schedule is deleted; no further backups are taken
	//	"PREVENT" -- destroy FAILS; protects the cadence a recovery
	//	             objective depends on from riding along with a
	//	             stack teardown
	//	"ABANDON" -- the schedule is removed from management but keeps
	//	             running (and creating backups) in GCP
	DeletionPolicy string `protobuf:"bytes,9,opt,name=deletion_policy,json=deletionPolicy,proto3" json:"deletion_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GcpSpannerBackupScheduleSpec) Reset() {
	*x = GcpSpannerBackupScheduleSpec{}
	mi := &file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpSpannerBackupScheduleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpSpannerBackupScheduleSpec) ProtoMessage() {}

func (x *GcpSpannerBackupScheduleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpSpannerBackupScheduleSpec.ProtoReflect.Descriptor instead.
func (*GcpSpannerBackupScheduleSpec) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *GcpSpannerBackupScheduleSpec) GetProjectId() *v1.StringValueOrRef {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *GcpSpannerBackupScheduleSpec) GetInstance() *v1.StringValueOrRef {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GcpSpannerBackupScheduleSpec) GetDatabase() *v1.StringValueOrRef {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *GcpSpannerBackupScheduleSpec) GetScheduleName() string {
	if x != nil {
		return x.ScheduleName
	}
	return ""
}

func (x *GcpSpannerBackupScheduleSpec) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *GcpSpannerBackupScheduleSpec) GetRetentionDuration() string {
	if x != nil {
		return x.RetentionDuration
	}
	return ""
}

func (x *GcpSpannerBackupScheduleSpec) GetBackupType() string {
	if x != nil && x.BackupType != nil {
		return *x.BackupType
	}
	return ""
}

func (x *GcpSpannerBackupScheduleSpec) GetEncryptionConfig() *GcpSpannerBackupScheduleEncryptionConfig {
	if x != nil {
		return x.EncryptionConfig
	}
	return nil
}

func (x *GcpSpannerBackupScheduleSpec) GetDeletionPolicy() string {
	if x != nil {
		return x.DeletionPolicy
	}
	return ""
}

var File_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"8catalog/gcp/gcpspannerbackupschedule/v1alpha1/spec.proto\x121dev.planton.gcp.gcpspannerbackupschedule.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\x1a\x1cshared/options/options.proto\"\x93\b\n" +
	"(GcpSpannerBackupScheduleEncryptionConfig\x12\x9f\x02\n" +
	"\x0fencryption_type\x18\x01 \x01(\tB\xf5\x01\xbaH\xf1\x01\xba\x01\xea\x01\n" +
	"\x1bencryption_type_valid_value\x12jencryption_type must be USE_DATABASE_ENCRYPTION, GOOGLE_DEFAULT_ENCRYPTION, or CUSTOMER_MANAGED_ENCRYPTION\x1a_this in ['USE_DATABASE_ENCRYPTION', 'GOOGLE_DEFAULT_ENCRYPTION', 'CUSTOMER_MANAGED_ENCRYPTION']\xc8\x01\x01R\x0eencryptionType\x12t\n" +
	"\fkms_key_name\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x1e\x88\xd4a\x93\x18\x92\xd4a\x15status.outputs.key_idR\n" +
	"kmsKeyName\x12v\n" +
	"\rkms_key_names\x18\x03 \x03(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x1e\x88\xd4a\x93\x18\x92\xd4a\x15status.outputs.key_idR\vkmsKeyNames:\xd6\x03\xbaH\xd2\x03\x1a\xee\x01\n" +
	"#cmek_requires_exactly_one_key_shape\x12QCUSTOMER_MANAGED_ENCRYPTION requires exactly one of kms_key_name or kms_key_names\x1atthis.encryption_type != 'CUSTOMER_MANAGED_ENCRYPTION' || (has(this.kms_key_name) != (this.kms_key_names.size() > 0))\x1a\xde\x01\n" +
	"\x1anon_cmek_must_not_set_keys\x12Jkms_key_name/kms_key_names are only valid with CUSTOMER_MANAGED_ENCRYPTION\x1atthis.encryption_type == 'CUSTOMER_MANAGED_ENCRYPTION' || (!has(this.kms_key_name) && this.kms_key_names.size() == 0)\"\xbd\b\n" +
	"\x1cGcpSpannerBackupScheduleSpec\x12u\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\"\x88\xd4a\xc1\x17\x92\xd4a\x19status.outputs.project_idR\tprojectId\x12{\n" +
	"\binstance\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB+\xbaH\x03\xc8\x01\x01\x88\xd4a\xd9\x17\x92\xd4a\x1cstatus.outputs.instance_nameR\binstance\x12{\n" +
	"\bdatabase\x18\x03 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB+\xbaH\x03\xc8\x01\x01\x88\xd4a\xda\x17\x92\xd4a\x1cstatus.outputs.database_nameR\bdatabase\x12J\n" +
	"\rschedule_name\x18\x04 \x01(\tB%\xbaH\"\xd8\x01\x01r\x1d\x18?2\x19^[a-z][-a-z0-9]*[a-z0-9]$R\fscheduleName\x12\x1a\n" +
	"\x04cron\x18\x05 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04cron\x12Q\n" +
	"\x12retention_duration\x18\x06 \x01(\tB\"\xbaH\x1f\xc8\x01\x01r\x1a2\x18^[0-9]+(\\.[0-9]{1,9})?s$R\x11retentionDuration\x12\x97\x01\n" +
	"\vbackup_type\x18\a \x01(\tBq\xbaHf\xba\x01c\n" +
	"\x17backup_type_valid_value\x12'backup_type must be FULL or INCREMENTAL\x1a\x1fthis in ['FULL', 'INCREMENTAL']\x8a\xa6\x1d\x04FULLH\x00R\n" +
	"backupType\x88\x01\x01\x12\x88\x01\n" +
	"\x11encryption_config\x18\b \x01(\v2[.dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleEncryptionConfigR\x10encryptionConfig\x12\xbb\x01\n" +
	"\x0fdeletion_policy\x18\t \x01(\tB\x91\x01\xbaH\x8d\x01\xba\x01\x89\x01\n" +
	"\x15valid_deletion_policy\x128deletion_policy must be one of: DELETE, PREVENT, ABANDON\x1a6this == '' || this in ['DELETE', 'PREVENT', 'ABANDON']R\x0edeletionPolicyB\x0e\n" +
	"\f_backup_typeB\x98\x03\n" +
	"5com.dev.planton.gcp.gcpspannerbackupschedule.v1alpha1B\tSpecProtoP\x01Zkgithub.com/plantonhq/planton/catalog/gcp/gcpspannerbackupschedule/v1alpha1;gcpspannerbackupschedulev1alpha1\xa2\x02\x04DPGG\xaa\x021Dev.Planton.Gcp.Gcpspannerbackupschedule.V1alpha1\xca\x021Dev\\Planton\\Gcp\\Gcpspannerbackupschedule\\V1alpha1\xe2\x02=Dev\\Planton\\Gcp\\Gcpspannerbackupschedule\\V1alpha1\\GPBMetadata\xea\x025Dev::Planton::Gcp::Gcpspannerbackupschedule::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDesc), len(file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDescData
}

var file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_goTypes = []any{
	(*GcpSpannerBackupScheduleEncryptionConfig)(nil), // 0: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleEncryptionConfig
	(*GcpSpannerBackupScheduleSpec)(nil),             // 1: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleSpec
	(*v1.StringValueOrRef)(nil),                      // 2: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_depIdxs = []int32{
	2, // 0: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleEncryptionConfig.kms_key_name:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // 1: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleEncryptionConfig.kms_key_names:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // 2: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleSpec.project_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // 3: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleSpec.instance:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // 4: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleSpec.database:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	0, // 5: dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleSpec.encryption_config:type_name -> dev.planton.gcp.gcpspannerbackupschedule.v1alpha1.GcpSpannerBackupScheduleEncryptionConfig
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_init() }
func file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_init() {
	if File_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDesc), len(file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto = out.File
	file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_goTypes = nil
	file_catalog_gcp_gcpspannerbackupschedule_v1alpha1_spec_proto_depIdxs = nil
}
