// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/oci/ocipostgresqldbsystem/v1alpha1/api.proto

package ocipostgresqldbsystemv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/apis/dev/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OciPostgresqlDbSystem is the top-level resource representing an Oracle Cloud
// Infrastructure PostgreSQL Database System -- a fully managed PostgreSQL
// service with configurable compute, storage, and backup policies.
type OciPostgresqlDbSystem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *OciPostgresqlDbSystemSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *OciPostgresqlDbSystemStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OciPostgresqlDbSystem) Reset() {
	*x = OciPostgresqlDbSystem{}
	mi := &file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OciPostgresqlDbSystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OciPostgresqlDbSystem) ProtoMessage() {}

func (x *OciPostgresqlDbSystem) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OciPostgresqlDbSystem.ProtoReflect.Descriptor instead.
func (*OciPostgresqlDbSystem) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *OciPostgresqlDbSystem) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *OciPostgresqlDbSystem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *OciPostgresqlDbSystem) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OciPostgresqlDbSystem) GetSpec() *OciPostgresqlDbSystemSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *OciPostgresqlDbSystem) GetStatus() *OciPostgresqlDbSystemStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// OciPostgresqlDbSystemStatus holds the outputs produced by deploying an
// OciPostgresqlDbSystem.
type OciPostgresqlDbSystemStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *OciPostgresqlDbSystemStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OciPostgresqlDbSystemStatus) Reset() {
	*x = OciPostgresqlDbSystemStatus{}
	mi := &file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OciPostgresqlDbSystemStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OciPostgresqlDbSystemStatus) ProtoMessage() {}

func (x *OciPostgresqlDbSystemStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OciPostgresqlDbSystemStatus.ProtoReflect.Descriptor instead.
func (*OciPostgresqlDbSystemStatus) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *OciPostgresqlDbSystemStatus) GetOutputs() *OciPostgresqlDbSystemStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto protoreflect.FileDescriptor

const file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"Adev/planton/provider/oci/ocipostgresqldbsystem/v1alpha1/api.proto\x127dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1aBdev/planton/provider/oci/ocipostgresqldbsystem/v1alpha1/spec.proto\x1aKdev/planton/provider/oci/ocipostgresqldbsystem/v1alpha1/stack_outputs.proto\x1a!dev/planton/shared/metadata.proto\"\xb8\x03\n" +
	"\x15OciPostgresqlDbSystem\x12@\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1f\xbaH\x1cr\x1a\n" +
	"\x18oci.planton.dev/v1alpha1R\n" +
	"apiVersion\x120\n" +
	"\x04kind\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\n" +
	"\x15OciPostgresqlDbSystemR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12n\n" +
	"\x04spec\x18\x04 \x01(\v2R.dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12l\n" +
	"\x06status\x18\x05 \x01(\v2T.dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemStatusR\x06status\"\x93\x01\n" +
	"\x1bOciPostgresqlDbSystemStatus\x12t\n" +
	"\aoutputs\x18\x01 \x01(\v2Z.dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemStackOutputsR\aoutputsB\xc3\x03\n" +
	";com.dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1B\bApiProtoP\x01Zwgithub.com/plantonhq/planton/apis/dev/planton/provider/oci/ocipostgresqldbsystem/v1alpha1;ocipostgresqldbsystemv1alpha1\xa2\x02\x05DPPOO\xaa\x027Dev.Planton.Provider.Oci.Ocipostgresqldbsystem.V1alpha1\xca\x027Dev\\Planton\\Provider\\Oci\\Ocipostgresqldbsystem\\V1alpha1\xe2\x02CDev\\Planton\\Provider\\Oci\\Ocipostgresqldbsystem\\V1alpha1\\GPBMetadata\xea\x02<Dev::Planton::Provider::Oci::Ocipostgresqldbsystem::V1alpha1b\x06proto3"

var (
	file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescOnce sync.Once
	file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescData []byte
)

func file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDesc), len(file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDesc)))
	})
	return file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDescData
}

var file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_goTypes = []any{
	(*OciPostgresqlDbSystem)(nil),             // 0: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystem
	(*OciPostgresqlDbSystemStatus)(nil),       // 1: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemStatus
	(*shared.CloudResourceMetadata)(nil),      // 2: dev.planton.shared.CloudResourceMetadata
	(*OciPostgresqlDbSystemSpec)(nil),         // 3: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemSpec
	(*OciPostgresqlDbSystemStackOutputs)(nil), // 4: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemStackOutputs
}
var file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystem.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystem.spec:type_name -> dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemSpec
	1, // 2: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystem.status:type_name -> dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemStatus
	4, // 3: dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemStatus.outputs:type_name -> dev.planton.provider.oci.ocipostgresqldbsystem.v1alpha1.OciPostgresqlDbSystemStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_init() }
func file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_init() {
	if File_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto != nil {
		return
	}
	file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_spec_proto_init()
	file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDesc), len(file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto = out.File
	file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_goTypes = nil
	file_dev_planton_provider_oci_ocipostgresqldbsystem_v1alpha1_api_proto_depIdxs = nil
}
