// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/azure/azurecosmosdbsqlroledefinition/v1/api.proto

package azurecosmosdbsqlroledefinitionv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/apis/dev/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureCosmosdbSqlRoleDefinition is the top-level API resource for a
// Cosmos DB SQL (NoSQL) API role definition inside a Cosmos DB account
// (referenced via cosmosdb_account_id) -- a named bundle of data-plane
// permissions that AzureCosmosdbSqlRoleAssignment resources bind to
// Microsoft Entra principals.
type AzureCosmosdbSqlRoleDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *AzureCosmosdbSqlRoleDefinitionSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *AzureCosmosdbSqlRoleDefinitionStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureCosmosdbSqlRoleDefinition) Reset() {
	*x = AzureCosmosdbSqlRoleDefinition{}
	mi := &file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureCosmosdbSqlRoleDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCosmosdbSqlRoleDefinition) ProtoMessage() {}

func (x *AzureCosmosdbSqlRoleDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureCosmosdbSqlRoleDefinition.ProtoReflect.Descriptor instead.
func (*AzureCosmosdbSqlRoleDefinition) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AzureCosmosdbSqlRoleDefinition) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AzureCosmosdbSqlRoleDefinition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AzureCosmosdbSqlRoleDefinition) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AzureCosmosdbSqlRoleDefinition) GetSpec() *AzureCosmosdbSqlRoleDefinitionSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AzureCosmosdbSqlRoleDefinition) GetStatus() *AzureCosmosdbSqlRoleDefinitionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AzureCosmosdbSqlRoleDefinitionStatus holds the deployment status and outputs.
type AzureCosmosdbSqlRoleDefinitionStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *AzureCosmosdbSqlRoleDefinitionStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureCosmosdbSqlRoleDefinitionStatus) Reset() {
	*x = AzureCosmosdbSqlRoleDefinitionStatus{}
	mi := &file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureCosmosdbSqlRoleDefinitionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCosmosdbSqlRoleDefinitionStatus) ProtoMessage() {}

func (x *AzureCosmosdbSqlRoleDefinitionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureCosmosdbSqlRoleDefinitionStatus.ProtoReflect.Descriptor instead.
func (*AzureCosmosdbSqlRoleDefinitionStatus) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AzureCosmosdbSqlRoleDefinitionStatus) GetOutputs() *AzureCosmosdbSqlRoleDefinitionStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto protoreflect.FileDescriptor

const file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDesc = "" +
	"\n" +
	"Fdev/planton/provider/azure/azurecosmosdbsqlroledefinition/v1/api.proto\x12<dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1\x1a\x1bbuf/validate/validate.proto\x1aGdev/planton/provider/azure/azurecosmosdbsqlroledefinition/v1/spec.proto\x1aPdev/planton/provider/azure/azurecosmosdbsqlroledefinition/v1/stack_outputs.proto\x1a!dev/planton/shared/metadata.proto\"\xe2\x03\n" +
	"\x1eAzureCosmosdbSqlRoleDefinition\x12<\n" +
	"\vapi_version\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\n" +
	"\x14azure.planton.dev/v1R\n" +
	"apiVersion\x129\n" +
	"\x04kind\x18\x02 \x01(\tB%\xbaH\"r \n" +
	"\x1eAzureCosmosdbSqlRoleDefinitionR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12|\n" +
	"\x04spec\x18\x04 \x01(\v2`.dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12z\n" +
	"\x06status\x18\x05 \x01(\v2b.dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionStatusR\x06status\"\xab\x01\n" +
	"$AzureCosmosdbSqlRoleDefinitionStatus\x12\x82\x01\n" +
	"\aoutputs\x18\x01 \x01(\v2h.dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionStackOutputsR\aoutputsB\xe4\x03\n" +
	"@com.dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1B\bApiProtoP\x01Z\x7fgithub.com/plantonhq/planton/apis/dev/planton/provider/azure/azurecosmosdbsqlroledefinition/v1;azurecosmosdbsqlroledefinitionv1\xa2\x02\x05DPPAA\xaa\x02<Dev.Planton.Provider.Azure.Azurecosmosdbsqlroledefinition.V1\xca\x02<Dev\\Planton\\Provider\\Azure\\Azurecosmosdbsqlroledefinition\\V1\xe2\x02HDev\\Planton\\Provider\\Azure\\Azurecosmosdbsqlroledefinition\\V1\\GPBMetadata\xea\x02ADev::Planton::Provider::Azure::Azurecosmosdbsqlroledefinition::V1b\x06proto3"

var (
	file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescOnce sync.Once
	file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescData []byte
)

func file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDesc), len(file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDesc)))
	})
	return file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDescData
}

var file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_goTypes = []any{
	(*AzureCosmosdbSqlRoleDefinition)(nil),             // 0: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinition
	(*AzureCosmosdbSqlRoleDefinitionStatus)(nil),       // 1: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionStatus
	(*shared.CloudResourceMetadata)(nil),               // 2: dev.planton.shared.CloudResourceMetadata
	(*AzureCosmosdbSqlRoleDefinitionSpec)(nil),         // 3: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionSpec
	(*AzureCosmosdbSqlRoleDefinitionStackOutputs)(nil), // 4: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionStackOutputs
}
var file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinition.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinition.spec:type_name -> dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionSpec
	1, // 2: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinition.status:type_name -> dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionStatus
	4, // 3: dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionStatus.outputs:type_name -> dev.planton.provider.azure.azurecosmosdbsqlroledefinition.v1.AzureCosmosdbSqlRoleDefinitionStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_init() }
func file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_init() {
	if File_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto != nil {
		return
	}
	file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_spec_proto_init()
	file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDesc), len(file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto = out.File
	file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_goTypes = nil
	file_dev_planton_provider_azure_azurecosmosdbsqlroledefinition_v1_api_proto_depIdxs = nil
}
