load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "kubeconfig",
    srcs = ["kubeconfig.go"],
    importpath = "github.com/plantonhq/planton/pkg/kubernetes/kubeconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//apis/dev/planton/provider/kubernetes",
        "//pkg/kubernetes/execcredential",
        "@com_github_pkg_errors//:errors",
        "@io_k8s_sigs_yaml//:yaml",
    ],
)

go_test(
    name = "kubeconfig_test",
    srcs = ["kubeconfig_test.go"],
    embed = [":kubeconfig"],
    deps = [
        "//apis/dev/planton/provider/kubernetes",
        "//pkg/kubernetes/execcredential",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_k8s_sigs_yaml//:yaml",
    ],
)
