version: 2

project_name: openmcf

before:
  hooks:
    - go mod tidy

builds:
  - id: openmcf
    main: .
    binary: openmcf
    ldflags:
      - -s -w -X github.com/plantonhq/openmcf/internal/cli/version.Version={{.Tag}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "cli_{{ .Version }}_checksums.txt"

release:
  github:
    owner: plantonhq
    name: openmcf
  header: |
    ## OpenMCF {{ .Tag }}

    This release includes the CLI, Docker images, website deployment, and pre-built Pulumi module binaries.

  footer: |
    ---

    ## CLI Installation

    ### macOS (Homebrew)

    ```bash
    brew tap plantonhq/tap
    brew install openmcf
    ```

    To upgrade:

    ```bash
    brew upgrade openmcf
    ```

    ### macOS (Manual)

    ```bash
    # Apple Silicon (M1/M2/M3)
    curl -LO https://github.com/plantonhq/openmcf/releases/download/{{ .Tag }}/cli_{{ .Version }}_darwin_arm64.tar.gz
    tar -xzf cli_{{ .Version }}_darwin_arm64.tar.gz
    chmod +x openmcf
    sudo mv openmcf /usr/local/bin/

    # Intel
    curl -LO https://github.com/plantonhq/openmcf/releases/download/{{ .Tag }}/cli_{{ .Version }}_darwin_amd64.tar.gz
    tar -xzf cli_{{ .Version }}_darwin_amd64.tar.gz
    chmod +x openmcf
    sudo mv openmcf /usr/local/bin/
    ```

    ### Linux

    ```bash
    # x86_64
    curl -LO https://github.com/plantonhq/openmcf/releases/download/{{ .Tag }}/cli_{{ .Version }}_linux_amd64.tar.gz
    tar -xzf cli_{{ .Version }}_linux_amd64.tar.gz
    chmod +x openmcf
    sudo mv openmcf /usr/local/bin/

    # ARM64
    curl -LO https://github.com/plantonhq/openmcf/releases/download/{{ .Tag }}/cli_{{ .Version }}_linux_arm64.tar.gz
    tar -xzf cli_{{ .Version }}_linux_arm64.tar.gz
    chmod +x openmcf
    sudo mv openmcf /usr/local/bin/
    ```

    ### Windows

    ```powershell
    # Download the ZIP file
    Invoke-WebRequest -Uri "https://github.com/plantonhq/openmcf/releases/download/{{ .Tag }}/cli_{{ .Version }}_windows_amd64.zip" -OutFile "cli.zip"

    # Extract
    Expand-Archive -Path "cli.zip" -DestinationPath "."

    # Add to PATH or move to a directory in PATH
    Move-Item -Path "openmcf.exe" -Destination "C:\Windows\System32\"
    ```

    ---

    ## Docker Images

    Docker images are published to GitHub Container Registry.

    ```bash
    # Pull the image
    docker pull ghcr.io/plantonhq/openmcf:{{ .Tag }}

    # Or use the latest tag
    docker pull ghcr.io/plantonhq/openmcf:latest
    ```

    ---

    ## Website

    The updated documentation website is available at:

    **https://openmcf.org**

    ---

    ## Pulumi Module Binaries

    Pre-built Pulumi module binaries are attached to this release for multiple platforms. Each binary is gzip-compressed.

    ### Available Platforms

    | Platform | Suffix | Example |
    |----------|--------|---------|
    | Linux x86-64 | `_linux_amd64.gz` | `pulumi-awsecsservice_linux_amd64.gz` |
    | macOS Apple Silicon | `_darwin_arm64.gz` | `pulumi-awsecsservice_darwin_arm64.gz` |
    | macOS Intel | `_darwin_amd64.gz` | `pulumi-awsecsservice_darwin_amd64.gz` |
    | Windows x86-64 | `_windows_amd64.exe.gz` | `pulumi-awsecsservice_windows_amd64.exe.gz` |

    ### Download and Extract

    ```bash
    # Example: Download the AWS ECS Service module for your platform

    # Linux x86-64
    curl -LO https://github.com/plantonhq/openmcf/releases/download/{{ .Tag }}/pulumi-awsecsservice_linux_amd64.gz
    gunzip pulumi-awsecsservice_linux_amd64.gz
    chmod +x pulumi-awsecsservice_linux_amd64
    ./pulumi-awsecsservice_linux_amd64

    # macOS Apple Silicon (M1/M2/M3)
    curl -LO https://github.com/plantonhq/openmcf/releases/download/{{ .Tag }}/pulumi-awsecsservice_darwin_arm64.gz
    gunzip pulumi-awsecsservice_darwin_arm64.gz
    chmod +x pulumi-awsecsservice_darwin_arm64
    ./pulumi-awsecsservice_darwin_arm64
    ```

    ### Available Modules

    All `pulumi-*_{platform}.gz` files attached to this release are pre-built deployment component binaries for the IaC Runner.

    ---

    ## Terraform Modules

    Terraform modules are available for all deployment components across all providers. Unlike Pulumi modules (which are pre-built binaries), Terraform modules are HCL files that you reference directly from this repository.

    ### Available Providers

    Terraform modules are available for: AWS, GCP, Azure, Kubernetes, DigitalOcean, Civo, Cloudflare, and more.

    ### Module Path Pattern

    All Terraform modules follow this path pattern:

    ```
    apis/org/openmcf/provider/{provider}/{component}/v1/iac/tf/
    ```

    ### Option 1: Clone and Checkout

    Clone the repository and checkout this release tag:

    ```bash
    # Clone the repository
    git clone https://github.com/plantonhq/openmcf.git
    cd openmcf

    # Checkout this release
    git checkout {{ .Tag }}

    # Navigate to a Terraform module
    # Example: AWS ECS Service
    cd apis/org/openmcf/provider/aws/awsecsservice/v1/iac/tf

    # Example: GCP GKE Cluster
    cd apis/org/openmcf/provider/gcp/gcpgkecluster/v1/iac/tf

    # Example: Kubernetes Deployment
    cd apis/org/openmcf/provider/kubernetes/kubernetesdeployment/v1/iac/tf

    # Initialize and apply
    terraform init
    terraform plan
    terraform apply
    ```

    ### Option 2: Git Source Reference

    Reference modules directly in your Terraform configuration:

    ```hcl
    # AWS ECS Service
    module "awsecsservice" {
      source = "git::https://github.com/plantonhq/openmcf.git//apis/org/openmcf/provider/aws/awsecsservice/v1/iac/tf?ref={{ .Tag }}"
    }

    # GCP GKE Cluster
    module "gcpgkecluster" {
      source = "git::https://github.com/plantonhq/openmcf.git//apis/org/openmcf/provider/gcp/gcpgkecluster/v1/iac/tf?ref={{ .Tag }}"
    }

    # Azure AKS Cluster
    module "azureakscluster" {
      source = "git::https://github.com/plantonhq/openmcf.git//apis/org/openmcf/provider/azure/azureakscluster/v1/iac/tf?ref={{ .Tag }}"
    }
    ```

    ---

    **Full Changelog**: https://github.com/plantonhq/openmcf/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

homebrew_casks:
  - name: openmcf
    repository:
      owner: plantonhq
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/plantonhq/openmcf
    description: "OpenMCF CLI - Infrastructure as Code made simple"
    binaries:
      - openmcf
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openmcf"]
          end
    caveats: |
      Installation Complete!

      OpenMCF CLI helps you manage infrastructure deployments.

      Quick Start

      1. Check the version:
         openmcf version

      2. Get help:
         openmcf --help

      Documentation: https://github.com/plantonhq/openmcf
