apiVersion: kubernetes.planton.dev/v1alpha1
kind: KubernetesRbac
metadata:
  name: monitoring-aggregate
spec:
  clusterScope: {}
  createRole:
    aggregationRule:
      clusterRoleSelectors:
        - matchLabels:
            rbac.example.com/aggregate-to-monitoring: "true"
