apiVersion: gcp.openmcf.org/v1
kind: GcpArtifactRegistryRepo
metadata:
  name: pp-test-gcpart
spec:
  repoFormat: DOCKER
  projectId:
    value: pc-artifact-registry
  region: asia-south1
  enablePublicAccess: false
