apiVersion: kubernetes.planton.dev/v1alpha1
kind: KubernetesMetricsServer
metadata:
  name: metrics-server
spec:
  namespace:
    value: metrics-server
  createNamespace: true
  kubeletInsecureTls: true
