// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/kubernetes/kuberneteskafkaconnector/v1alpha1/stack_input.proto

package kuberneteskafkaconnectorv1alpha1

import (
	kubernetes "github.com/plantonhq/planton/apis/dev/planton/provider/kubernetes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// kubernetes-kafka-connector stack-input
type KubernetesKafkaConnectorStackInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target cloud-resource
	Target *KubernetesKafkaConnector `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// provider-config
	ProviderConfig *kubernetes.KubernetesProviderConfig `protobuf:"bytes,2,opt,name=provider_config,json=providerConfig,proto3" json:"provider_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubernetesKafkaConnectorStackInput) Reset() {
	*x = KubernetesKafkaConnectorStackInput{}
	mi := &file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesKafkaConnectorStackInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesKafkaConnectorStackInput) ProtoMessage() {}

func (x *KubernetesKafkaConnectorStackInput) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesKafkaConnectorStackInput.ProtoReflect.Descriptor instead.
func (*KubernetesKafkaConnectorStackInput) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesKafkaConnectorStackInput) GetTarget() *KubernetesKafkaConnector {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *KubernetesKafkaConnectorStackInput) GetProviderConfig() *kubernetes.KubernetesProviderConfig {
	if x != nil {
		return x.ProviderConfig
	}
	return nil
}

var File_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto protoreflect.FileDescriptor

const file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDesc = "" +
	"\n" +
	"Sdev/planton/provider/kubernetes/kuberneteskafkaconnector/v1alpha1/stack_input.proto\x12Adev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1\x1aKdev/planton/provider/kubernetes/kuberneteskafkaconnector/v1alpha1/api.proto\x1a.dev/planton/provider/kubernetes/provider.proto\"\xfd\x01\n" +
	"\"KubernetesKafkaConnectorStackInput\x12s\n" +
	"\x06target\x18\x01 \x01(\v2[.dev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1.KubernetesKafkaConnectorR\x06target\x12b\n" +
	"\x0fprovider_config\x18\x02 \x01(\v29.dev.planton.provider.kubernetes.KubernetesProviderConfigR\x0eproviderConfigB\x8a\x04\n" +
	"Ecom.dev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1B\x0fStackInputProtoP\x01Z\x84\x01github.com/plantonhq/planton/apis/dev/planton/provider/kubernetes/kuberneteskafkaconnector/v1alpha1;kuberneteskafkaconnectorv1alpha1\xa2\x02\x05DPPKK\xaa\x02ADev.Planton.Provider.Kubernetes.Kuberneteskafkaconnector.V1alpha1\xca\x02ADev\\Planton\\Provider\\Kubernetes\\Kuberneteskafkaconnector\\V1alpha1\xe2\x02MDev\\Planton\\Provider\\Kubernetes\\Kuberneteskafkaconnector\\V1alpha1\\GPBMetadata\xea\x02FDev::Planton::Provider::Kubernetes::Kuberneteskafkaconnector::V1alpha1b\x06proto3"

var (
	file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDescOnce sync.Once
	file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDescData []byte
)

func file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDesc)))
	})
	return file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDescData
}

var file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_goTypes = []any{
	(*KubernetesKafkaConnectorStackInput)(nil),  // 0: dev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1.KubernetesKafkaConnectorStackInput
	(*KubernetesKafkaConnector)(nil),            // 1: dev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1.KubernetesKafkaConnector
	(*kubernetes.KubernetesProviderConfig)(nil), // 2: dev.planton.provider.kubernetes.KubernetesProviderConfig
}
var file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_depIdxs = []int32{
	1, // 0: dev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1.KubernetesKafkaConnectorStackInput.target:type_name -> dev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1.KubernetesKafkaConnector
	2, // 1: dev.planton.provider.kubernetes.kuberneteskafkaconnector.v1alpha1.KubernetesKafkaConnectorStackInput.provider_config:type_name -> dev.planton.provider.kubernetes.KubernetesProviderConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_init()
}
func file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_init() {
	if File_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto != nil {
		return
	}
	file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto = out.File
	file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_goTypes = nil
	file_dev_planton_provider_kubernetes_kuberneteskafkaconnector_v1alpha1_stack_input_proto_depIdxs = nil
}
