load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "verify",
    srcs = [
        "address.go",
        "backend_bucket.go",
        "backend_service.go",
        "cloud_sql_database.go",
        "cloud_sql_instance.go",
        "cloud_sql_user.go",
        "gcs_bucket.go",
        "global_address.go",
        "global_forwarding_rule.go",
        "health_check.go",
        "iam_custom_role.go",
        "managed_ssl_certificate.go",
        "project_iam_member.go",
        "region_network_endpoint_group.go",
        "service_account.go",
        "service_networking_connection.go",
        "ssl_certificate.go",
        "ssl_policy.go",
        "subnetwork.go",
        "target_http_proxy.go",
        "target_https_proxy.go",
        "url_map.go",
        "verifier.go",
        "vpc.go",
        "workload_identity_pool.go",
        "workload_identity_pool_provider.go",
    ],
    importpath = "github.com/plantonhq/planton/apis/dev/planton/provider/gcp/aa_e2e/verify",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_pkg_errors//:errors",
        "@org_golang_google_api//cloudresourcemanager/v1:cloudresourcemanager",
        "@org_golang_google_api//compute/v1:compute",
        "@org_golang_google_api//googleapi",
        "@org_golang_google_api//iam/v1:iam",
        "@org_golang_google_api//sqladmin/v1:sqladmin",
        "@org_golang_google_api//storage/v1:storage",
    ],
)
