syntax = "proto3";

package dev.planton.atlas.atlasmongodb.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/atlas/atlasmongodb/v1alpha1/outputs.proto";
import "catalog/atlas/atlasmongodb/v1alpha1/spec.proto";
import "shared/metadata.proto";

//atlas-mongodb
message AtlasMongodb {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'atlas.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AtlasMongodb'];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  AtlasMongodbSpec spec = 4 [(buf.validate.field).required = true];

  //status
  AtlasMongodbStatus status = 5;
}

//atlas-mongodb status
message AtlasMongodbStatus {
  //stack-outputs
  AtlasMongodbStackOutputs outputs = 1;
}
