apiVersion: aws.planton.dev/v1
kind: AwsLbTargetGroup
metadata:
  name: <service-name>
spec:
  region: <aws-region>
  vpcId:
    valueFrom:
      kind: AwsVpc
      name: <vpc-resource-name>
      fieldPath: status.outputs.vpc_id
  targetType: ip
  port: 8080
  protocol: HTTP
  deregistrationDelaySeconds: 60
  healthCheck:
    protocol: HTTP
    path: /healthz
    intervalSeconds: 15
    timeoutSeconds: 5
    healthyThreshold: 3
    unhealthyThreshold: 3
    matcher: "200"
