apiVersion: aws.planton.dev/v1alpha1
kind: AwsIamAccountSettings
metadata:
  name: iam-account-baseline
spec:
  region: us-east-1
  passwordPolicy:
    minimumPasswordLength: 14
    requireLowercaseCharacters: true
    requireNumbers: true
    requireSymbols: true
    requireUppercaseCharacters: true
    allowUsersToChangePassword: true
    maxPasswordAge: 90
    passwordReusePrevention: 24
  sts:
    globalEndpointTokenVersion: v2Token
