apiVersion: digital-ocean.planton.dev/v1alpha1
kind: DigitalOceanDatabaseDb
metadata:
  name: orders-database
spec:
  cluster:
    valueFrom:
      kind: DigitalOceanDatabaseCluster
      name: orders-postgres
      fieldPath: status.outputs.cluster_id
  databaseName: orders
