apiVersion: azure.planton.dev/v1alpha1
kind: AzureMonitorActivityLogAlert
metadata:
  name: my-resource-delete-alert
spec:
  resourceGroup:
    value: <resource-group-name>
  name: critical-delete-alert
  scopes:
    - valueFrom:
        name: <watched-resource-group>
  criteria:
    category: ADMINISTRATIVE
    levels:
      - CRITICAL
      - ERROR
    statuses:
      - Succeeded
  actions:
    - actionGroupId:
        valueFrom:
          name: <action-group>
  description: Notify on successful administrative operations at critical/error level
