// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/aws/awsekscluster/v1alpha1/spec.proto

package awseksclusterv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	_ "github.com/plantonhq/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AwsEksClusterSpec defines an EKS cluster CONTROL PLANE: the managed
// Kubernetes API server, etcd, and the cluster-level posture that everything
// else composes onto -- networking exposure, authentication mode, secrets
// encryption, control-plane logging, upgrade policy, and (optionally) EKS
// Auto Mode.
//
// The cluster is deliberately only the control plane. Compute attaches as
// separate, composable nodes: AwsEksNodeGroup references this cluster's
// status.outputs.name, and IAM trust for workloads flows through the
// cluster's status.outputs.oidc_issuer_url (point an AwsIamOidcProvider at
// it to enable IRSA with a single reference).
//
// The cluster name comes from metadata.name (AWS limit: 100 characters,
// alphanumeric start, then alphanumerics/underscores/hyphens). The name and
// the cluster IAM role are create-only in AWS; the immutable networking
// fields are called out on each field below.
type AwsEksClusterSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The AWS region the cluster control plane runs in. Must match the region
	// of the subnets it attaches to. Example: "us-west-2", "eu-west-1".
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// The subnets (at least two, in distinct availability zones) where EKS
	// places the control plane's elastic network interfaces. These decide
	// which zones the API server is reachable from inside the VPC; worker
	// subnets are chosen separately on each node group. Reference AwsSubnet
	// subnet_id outputs or pass literal subnet IDs. Create-only in AWS
	// (changing the set updates in place, but the VPC itself cannot change).
	SubnetIds []*v1.StringValueOrRef `protobuf:"bytes,2,rep,name=subnet_ids,json=subnetIds,proto3" json:"subnet_ids,omitempty"`
	// The IAM role the EKS control plane assumes to manage AWS resources on
	// your behalf (ENIs, security groups, logs). The role must trust
	// eks.amazonaws.com and carry the AmazonEKSClusterPolicy managed policy --
	// attach it on the AwsIamRole itself (managed_policy_arns); this component
	// never modifies a role it merely references. Reference an AwsIamRole's
	// role_arn output or pass a literal ARN. Create-only in AWS.
	ClusterRoleArn *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=cluster_role_arn,json=clusterRoleArn,proto3" json:"cluster_role_arn,omitempty"`
	// The Kubernetes minor version of the control plane, e.g. "1.31". Leave
	// empty to let AWS pick the current default version. EKS only ever
	// upgrades one minor at a time and never downgrades -- lowering this value
	// is rejected by AWS. Node groups pin their own version, so upgrade the
	// control plane first, then roll the node groups.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Additional security groups attached to the control plane's network
	// interfaces, on top of the cluster security group EKS always creates
	// (exported as cluster_security_group_id). Most clusters need none --
	// reach for this only for legacy rules that must ride along. Reference
	// AwsSecurityGroup security_group_id outputs or pass literal IDs.
	SecurityGroupIds []*v1.StringValueOrRef `protobuf:"bytes,5,rep,name=security_group_ids,json=securityGroupIds,proto3" json:"security_group_ids,omitempty"`
	// Whether the Kubernetes API server is reachable from the internet. AWS
	// defaults this to true; set false for a fully private cluster (pair with
	// endpoint_private_access = true or the API server becomes unreachable).
	// Scope a public endpoint down with public_access_cidrs.
	EndpointPublicAccess *bool `protobuf:"varint,6,opt,name=endpoint_public_access,json=endpointPublicAccess,proto3,oneof" json:"endpoint_public_access,omitempty"`
	// Whether the Kubernetes API server is reachable from within the VPC
	// through private ENIs. AWS defaults this to false, which is almost never
	// what a production cluster wants: without it, in-VPC clients (nodes,
	// CI runners) reach the API server over the public endpoint.
	EndpointPrivateAccess bool `protobuf:"varint,7,opt,name=endpoint_private_access,json=endpointPrivateAccess,proto3" json:"endpoint_private_access,omitempty"`
	// IPv4 CIDR blocks allowed to reach the PUBLIC API endpoint. Empty means
	// AWS's default of 0.0.0.0/0 (open to the internet -- rely on IAM/RBAC
	// only). Restricting this to office/VPN egress ranges is the single
	// cheapest hardening step for a public-endpoint cluster.
	PublicAccessCidrs []string `protobuf:"bytes,8,rep,name=public_access_cidrs,json=publicAccessCidrs,proto3" json:"public_access_cidrs,omitempty"`
	// How control-plane-initiated traffic egresses the VPC:
	//   - "AWS_MANAGED" (AWS default): EKS routes control-plane egress itself.
	//   - "CUSTOMER_ROUTED": egress follows your VPC route tables (inspection/
	//     egress-firewall architectures).
	//   - "CUSTOMER_ISOLATED": no control-plane egress through your VPC.
	//
	// Reverting CUSTOMER_ROUTED back to AWS_MANAGED is not supported in place
	// -- AWS forces cluster replacement.
	ControlPlaneEgressMode string `protobuf:"bytes,9,opt,name=control_plane_egress_mode,json=controlPlaneEgressMode,proto3" json:"control_plane_egress_mode,omitempty"`
	// The IP address family for pod and service networking: "ipv4" (AWS
	// default) or "ipv6". Create-only: changing it replaces the cluster. IPv6
	// clusters assign pod addresses from the VPC's IPv6 CIDR and require IPv6-
	// enabled subnets.
	IpFamily string `protobuf:"bytes,10,opt,name=ip_family,json=ipFamily,proto3" json:"ip_family,omitempty"`
	// The CIDR block Kubernetes assigns SERVICE addresses from (ipv4 clusters
	// only). Must be a /12 to /24 inside the private ranges (10/8,
	// 172.16/12, 192.168/16, 100.64/10) and must not overlap the VPC or any
	// peered/connected network -- overlap breaks routing in ways that only
	// surface later. Create-only. Empty keeps the AWS default
	// (10.100.0.0/16 or 172.20.0.0/16, whichever avoids the VPC).
	ServiceIpv4Cidr string `protobuf:"bytes,11,opt,name=service_ipv4_cidr,json=serviceIpv4Cidr,proto3" json:"service_ipv4_cidr,omitempty"`
	// Control-plane log types streamed to CloudWatch Logs: "api", "audit",
	// "authenticator", "controllerManager", "scheduler". Empty disables
	// control-plane logging. "audit" and "authenticator" are the two most
	// valuable in practice (who did what, and who got in); enabling all five
	// on a busy cluster carries real CloudWatch ingestion cost.
	EnabledClusterLogTypes []string `protobuf:"bytes,12,rep,name=enabled_cluster_log_types,json=enabledClusterLogTypes,proto3" json:"enabled_cluster_log_types,omitempty"`
	// Customer-managed KMS key for ENVELOPE ENCRYPTION of Kubernetes secrets
	// -- secrets in etcd are encrypted with a data key that this KMS key
	// wraps. Unset uses AWS-owned encryption only. One-way door: once enabled
	// it cannot be disabled or re-keyed on a live cluster (AWS forces
	// replacement). Reference an AwsKmsKey's key_arn output or pass a literal
	// ARN.
	KmsKeyArn *v1.StringValueOrRef `protobuf:"bytes,13,opt,name=kms_key_arn,json=kmsKeyArn,proto3" json:"kms_key_arn,omitempty"`
	// How identities are granted cluster access (access entries vs the legacy
	// aws-auth ConfigMap) and whether the creator gets admin. Unset keeps
	// AWS defaults (API_AND_CONFIG_MAP + creator-admin).
	AccessConfig *AwsEksClusterAccessConfig `protobuf:"bytes,14,opt,name=access_config,json=accessConfig,proto3" json:"access_config,omitempty"`
	// EKS Auto Mode: AWS provisions and manages compute, block storage, and
	// load balancing for the cluster itself -- no node groups to operate.
	// The alternative to (not a companion of) explicit AwsEksNodeGroup
	// compute; in practice a cluster uses one model or the other.
	AutoMode *AwsEksClusterAutoMode `protobuf:"bytes,15,opt,name=auto_mode,json=autoMode,proto3" json:"auto_mode,omitempty"`
	// The upgrade support tier once this cluster's Kubernetes version leaves
	// standard support: "STANDARD" (upgrade on schedule, no surcharge) or
	// "EXTENDED" (AWS default -- stay on the version up to ~26 months at a
	// significant hourly surcharge). Choose STANDARD when you upgrade
	// promptly and want the surcharge risk gone.
	UpgradeSupportType string `protobuf:"bytes,16,opt,name=upgrade_support_type,json=upgradeSupportType,proto3" json:"upgrade_support_type,omitempty"`
	// Allows Amazon Application Recovery Controller to shift in-cluster
	// east-west traffic away from an impaired availability zone.
	ZonalShiftEnabled bool `protobuf:"varint,17,opt,name=zonal_shift_enabled,json=zonalShiftEnabled,proto3" json:"zonal_shift_enabled,omitempty"`
	// Blocks cluster deletion at the EKS API until explicitly disabled --
	// the guard rail for shared/production control planes.
	DeletionProtection bool `protobuf:"varint,18,opt,name=deletion_protection,json=deletionProtection,proto3" json:"deletion_protection,omitempty"`
	// Whether EKS installs the default self-managed add-ons (vpc-cni,
	// kube-proxy, CoreDNS) at creation. AWS defaults this to true; set false
	// for a "bring your own add-ons" cluster that manages every add-on
	// explicitly (the GitOps-friendly posture). Create-only.
	BootstrapSelfManagedAddons *bool `protobuf:"varint,19,opt,name=bootstrap_self_managed_addons,json=bootstrapSelfManagedAddons,proto3,oneof" json:"bootstrap_self_managed_addons,omitempty"`
	// Force the Kubernetes version update even if pods cannot be safely
	// drained onto the new version (pod disruption budgets that can never be
	// satisfied). Only consulted while `version` changes.
	ForceUpdateVersion bool `protobuf:"varint,20,opt,name=force_update_version,json=forceUpdateVersion,proto3" json:"force_update_version,omitempty"`
	// EKS Provisioned Control Plane: pre-provisions control-plane capacity
	// for very large or bursty clusters instead of relying on EKS's
	// reactive scaling (which can lag sudden API-server load, e.g. mass
	// node joins or operator storms). "standard" (AWS default -- reactive
	// scaling, no surcharge) or a provisioned tier of increasing capacity:
	// "tier-xl", "tier-2xl", "tier-4xl", "tier-8xl" -- each billed hourly
	// ON TOP of the cluster fee. Updates in place; empty keeps standard.
	ControlPlaneScalingTier string `protobuf:"bytes,21,opt,name=control_plane_scaling_tier,json=controlPlaneScalingTier,proto3" json:"control_plane_scaling_tier,omitempty"`
	// EKS Hybrid Nodes: the on-premises/edge networks whose nodes and pods
	// join this cluster over your VPN or Direct Connect. Declaring the
	// ranges is free -- billing starts only when hybrid nodes register.
	// Updates in place on a live cluster.
	RemoteNetworks *AwsEksClusterRemoteNetworks `protobuf:"bytes,22,opt,name=remote_networks,json=remoteNetworks,proto3" json:"remote_networks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AwsEksClusterSpec) Reset() {
	*x = AwsEksClusterSpec{}
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEksClusterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEksClusterSpec) ProtoMessage() {}

func (x *AwsEksClusterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEksClusterSpec.ProtoReflect.Descriptor instead.
func (*AwsEksClusterSpec) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AwsEksClusterSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AwsEksClusterSpec) GetSubnetIds() []*v1.StringValueOrRef {
	if x != nil {
		return x.SubnetIds
	}
	return nil
}

func (x *AwsEksClusterSpec) GetClusterRoleArn() *v1.StringValueOrRef {
	if x != nil {
		return x.ClusterRoleArn
	}
	return nil
}

func (x *AwsEksClusterSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AwsEksClusterSpec) GetSecurityGroupIds() []*v1.StringValueOrRef {
	if x != nil {
		return x.SecurityGroupIds
	}
	return nil
}

func (x *AwsEksClusterSpec) GetEndpointPublicAccess() bool {
	if x != nil && x.EndpointPublicAccess != nil {
		return *x.EndpointPublicAccess
	}
	return false
}

func (x *AwsEksClusterSpec) GetEndpointPrivateAccess() bool {
	if x != nil {
		return x.EndpointPrivateAccess
	}
	return false
}

func (x *AwsEksClusterSpec) GetPublicAccessCidrs() []string {
	if x != nil {
		return x.PublicAccessCidrs
	}
	return nil
}

func (x *AwsEksClusterSpec) GetControlPlaneEgressMode() string {
	if x != nil {
		return x.ControlPlaneEgressMode
	}
	return ""
}

func (x *AwsEksClusterSpec) GetIpFamily() string {
	if x != nil {
		return x.IpFamily
	}
	return ""
}

func (x *AwsEksClusterSpec) GetServiceIpv4Cidr() string {
	if x != nil {
		return x.ServiceIpv4Cidr
	}
	return ""
}

func (x *AwsEksClusterSpec) GetEnabledClusterLogTypes() []string {
	if x != nil {
		return x.EnabledClusterLogTypes
	}
	return nil
}

func (x *AwsEksClusterSpec) GetKmsKeyArn() *v1.StringValueOrRef {
	if x != nil {
		return x.KmsKeyArn
	}
	return nil
}

func (x *AwsEksClusterSpec) GetAccessConfig() *AwsEksClusterAccessConfig {
	if x != nil {
		return x.AccessConfig
	}
	return nil
}

func (x *AwsEksClusterSpec) GetAutoMode() *AwsEksClusterAutoMode {
	if x != nil {
		return x.AutoMode
	}
	return nil
}

func (x *AwsEksClusterSpec) GetUpgradeSupportType() string {
	if x != nil {
		return x.UpgradeSupportType
	}
	return ""
}

func (x *AwsEksClusterSpec) GetZonalShiftEnabled() bool {
	if x != nil {
		return x.ZonalShiftEnabled
	}
	return false
}

func (x *AwsEksClusterSpec) GetDeletionProtection() bool {
	if x != nil {
		return x.DeletionProtection
	}
	return false
}

func (x *AwsEksClusterSpec) GetBootstrapSelfManagedAddons() bool {
	if x != nil && x.BootstrapSelfManagedAddons != nil {
		return *x.BootstrapSelfManagedAddons
	}
	return false
}

func (x *AwsEksClusterSpec) GetForceUpdateVersion() bool {
	if x != nil {
		return x.ForceUpdateVersion
	}
	return false
}

func (x *AwsEksClusterSpec) GetControlPlaneScalingTier() string {
	if x != nil {
		return x.ControlPlaneScalingTier
	}
	return ""
}

func (x *AwsEksClusterSpec) GetRemoteNetworks() *AwsEksClusterRemoteNetworks {
	if x != nil {
		return x.RemoteNetworks
	}
	return nil
}

// AwsEksClusterAccessConfig controls how AWS identities are granted access
// to the Kubernetes API.
type AwsEksClusterAccessConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source of truth for cluster access:
	//   - "API": EKS access entries only -- the modern model; IAM principals
	//     are granted access as first-class EKS resources.
	//   - "API_AND_CONFIG_MAP" (AWS default): access entries plus the legacy
	//     aws-auth ConfigMap, for migration.
	//   - "CONFIG_MAP": legacy aws-auth ConfigMap only.
	//
	// Moving toward "API" is one-way on a live cluster: AWS allows
	// CONFIG_MAP -> API_AND_CONFIG_MAP -> API but never back.
	AuthenticationMode string `protobuf:"bytes,1,opt,name=authentication_mode,json=authenticationMode,proto3" json:"authentication_mode,omitempty"`
	// Whether the identity creating the cluster is automatically granted
	// cluster-admin. AWS defaults this to true. Set false for clusters
	// whose admins are managed explicitly through access entries -- with no
	// other admin configured, false can lock everyone out of a fresh
	// cluster. Create-only.
	BootstrapClusterCreatorAdminPermissions *bool `protobuf:"varint,2,opt,name=bootstrap_cluster_creator_admin_permissions,json=bootstrapClusterCreatorAdminPermissions,proto3,oneof" json:"bootstrap_cluster_creator_admin_permissions,omitempty"`
	unknownFields                           protoimpl.UnknownFields
	sizeCache                               protoimpl.SizeCache
}

func (x *AwsEksClusterAccessConfig) Reset() {
	*x = AwsEksClusterAccessConfig{}
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEksClusterAccessConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEksClusterAccessConfig) ProtoMessage() {}

func (x *AwsEksClusterAccessConfig) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEksClusterAccessConfig.ProtoReflect.Descriptor instead.
func (*AwsEksClusterAccessConfig) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *AwsEksClusterAccessConfig) GetAuthenticationMode() string {
	if x != nil {
		return x.AuthenticationMode
	}
	return ""
}

func (x *AwsEksClusterAccessConfig) GetBootstrapClusterCreatorAdminPermissions() bool {
	if x != nil && x.BootstrapClusterCreatorAdminPermissions != nil {
		return *x.BootstrapClusterCreatorAdminPermissions
	}
	return false
}

// AwsEksClusterAutoMode enables EKS Auto Mode, where AWS manages the
// cluster's compute, block storage, and load balancing. AWS models this as
// three separate blocks (compute, block storage, and elastic load
// balancing) that its API requires to be enabled or disabled TOGETHER;
// this message is that all-or-nothing switch expressed honestly as one
// toggle -- both IaC engines expand it to the three AWS settings.
type AwsEksClusterAutoMode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Turn Auto Mode on. AWS then provisions and scales EC2 capacity,
	// provisions EBS volumes, and manages load balancers for the cluster's
	// workloads without any node group.
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// The built-in node pools Auto Mode may launch capacity from:
	// "general-purpose" (workloads) and/or "system" (cluster-critical pods
	// on dedicated capacity). Empty enables Auto Mode with no built-in
	// pools -- capacity then comes only from custom NodePool resources
	// defined in-cluster.
	NodePools []string `protobuf:"bytes,2,rep,name=node_pools,json=nodePools,proto3" json:"node_pools,omitempty"`
	// The IAM role Auto Mode nodes assume (the node identity for launched
	// capacity). Required by AWS when node_pools is non-empty. Reference an
	// AwsIamRole's role_arn output or pass a literal ARN.
	NodeRoleArn   *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=node_role_arn,json=nodeRoleArn,proto3" json:"node_role_arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEksClusterAutoMode) Reset() {
	*x = AwsEksClusterAutoMode{}
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEksClusterAutoMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEksClusterAutoMode) ProtoMessage() {}

func (x *AwsEksClusterAutoMode) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEksClusterAutoMode.ProtoReflect.Descriptor instead.
func (*AwsEksClusterAutoMode) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *AwsEksClusterAutoMode) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AwsEksClusterAutoMode) GetNodePools() []string {
	if x != nil {
		return x.NodePools
	}
	return nil
}

func (x *AwsEksClusterAutoMode) GetNodeRoleArn() *v1.StringValueOrRef {
	if x != nil {
		return x.NodeRoleArn
	}
	return nil
}

// AwsEksClusterRemoteNetworks declares the on-premises networks EKS Hybrid
// Nodes join from. AWS models this as two nested single-list blocks
// (remote node networks and remote pod networks); this message flattens
// them to the two CIDR lists. Every CIDR must be an IPv4 NETWORK address
// (host bits zero) inside the private ranges AWS accepts here: 10.0.0.0/8,
// 172.16.0.0/12, 192.168.0.0/16, or carrier-grade NAT 100.64.0.0/10.
// The ranges must be reachable from the VPC (VPN or Direct Connect) and
// must not overlap the VPC, the service CIDR, or each other.
type AwsEksClusterRemoteNetworks struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CIDR blocks of the on-premises network the hybrid NODES have their
	// addresses in. This is the range the control plane accepts kubelet
	// registrations from -- without a node's address inside one of these
	// blocks, it cannot join.
	NodeCidrs []string `protobuf:"bytes,1,rep,name=node_cidrs,json=nodeCidrs,proto3" json:"node_cidrs,omitempty"`
	// CIDR blocks the on-premises PODS have their addresses in (the CNI's
	// pod network on the hybrid nodes). Optional: needed when pods must be
	// directly routable from the cluster (e.g. webhooks running on hybrid
	// nodes); node-only setups can omit it.
	PodCidrs      []string `protobuf:"bytes,2,rep,name=pod_cidrs,json=podCidrs,proto3" json:"pod_cidrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwsEksClusterRemoteNetworks) Reset() {
	*x = AwsEksClusterRemoteNetworks{}
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsEksClusterRemoteNetworks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsEksClusterRemoteNetworks) ProtoMessage() {}

func (x *AwsEksClusterRemoteNetworks) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsEksClusterRemoteNetworks.ProtoReflect.Descriptor instead.
func (*AwsEksClusterRemoteNetworks) Descriptor() ([]byte, []int) {
	return file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *AwsEksClusterRemoteNetworks) GetNodeCidrs() []string {
	if x != nil {
		return x.NodeCidrs
	}
	return nil
}

func (x *AwsEksClusterRemoteNetworks) GetPodCidrs() []string {
	if x != nil {
		return x.PodCidrs
	}
	return nil
}

var File_catalog_aws_awsekscluster_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"-catalog/aws/awsekscluster/v1alpha1/spec.proto\x12&dev.planton.aws.awsekscluster.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\x1a\x1cshared/options/options.proto\"\xbf\x1b\n" +
	"\x11AwsEksClusterSpec\x12\x1f\n" +
	"\x06region\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06region\x12\x90\x01\n" +
	"\n" +
	"subnet_ids\x18\x02 \x03(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB=\xbaH\b\xc8\x01\x01\x92\x01\x02\b\x02\xb2\xa6\x1d\rspans subnets\x88\xd4a\xbc\b\x92\xd4a\x18status.outputs.subnet_idR\tsubnetIds\x12\x9c\x01\n" +
	"\x10cluster_role_arn\x18\x03 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB>\xbaH\x03\xc8\x01\x01\xb2\xa6\x1d\x14assumes cluster role\x88\xd4a\xf0\a\x92\xd4a\x17status.outputs.role_arnR\x0eclusterRoleArn\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x8b\x01\n" +
	"\x12security_group_ids\x18\x05 \x03(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB)\x88\xd4a\xf7\a\x92\xd4a status.outputs.security_group_idR\x10securityGroupIds\x129\n" +
	"\x16endpoint_public_access\x18\x06 \x01(\bH\x00R\x14endpointPublicAccess\x88\x01\x01\x126\n" +
	"\x17endpoint_private_access\x18\a \x01(\bR\x15endpointPrivateAccess\x12\x9f\x01\n" +
	"\x13public_access_cidrs\x18\b \x03(\tBo\xbaHl\x92\x01i\"gre2c^(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}/(?:[0-9]|[12]\\d|3[0-2])$R\x11publicAccessCidrs\x129\n" +
	"\x19control_plane_egress_mode\x18\t \x01(\tR\x16controlPlaneEgressMode\x12\x1b\n" +
	"\tip_family\x18\n" +
	" \x01(\tR\bipFamily\x12*\n" +
	"\x11service_ipv4_cidr\x18\v \x01(\tR\x0fserviceIpv4Cidr\x12C\n" +
	"\x19enabled_cluster_log_types\x18\f \x03(\tB\b\xbaH\x05\x92\x01\x02\x18\x01R\x16enabledClusterLogTypes\x12\x8d\x01\n" +
	"\vkms_key_arn\x18\r \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB9\xb2\xa6\x1d\x16secrets encrypted with\x88\xd4a\xfb\a\x92\xd4a\x16status.outputs.key_arnR\tkmsKeyArn\x12f\n" +
	"\raccess_config\x18\x0e \x01(\v2A.dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterAccessConfigR\faccessConfig\x12Z\n" +
	"\tauto_mode\x18\x0f \x01(\v2=.dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterAutoModeR\bautoMode\x120\n" +
	"\x14upgrade_support_type\x18\x10 \x01(\tR\x12upgradeSupportType\x12.\n" +
	"\x13zonal_shift_enabled\x18\x11 \x01(\bR\x11zonalShiftEnabled\x12/\n" +
	"\x13deletion_protection\x18\x12 \x01(\bR\x12deletionProtection\x12F\n" +
	"\x1dbootstrap_self_managed_addons\x18\x13 \x01(\bH\x01R\x1abootstrapSelfManagedAddons\x88\x01\x01\x120\n" +
	"\x14force_update_version\x18\x14 \x01(\bR\x12forceUpdateVersion\x12;\n" +
	"\x1acontrol_plane_scaling_tier\x18\x15 \x01(\tR\x17controlPlaneScalingTier\x12l\n" +
	"\x0fremote_networks\x18\x16 \x01(\v2C.dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterRemoteNetworksR\x0eremoteNetworks:\x87\r\xbaH\x83\r\x1a\xa3\x01\n" +
	"\x0eversion_format\x12Hversion must be a Kubernetes minor version of 1.24 or later, e.g. '1.31'\x1aGthis.version == '' || this.version.matches('^1\\\\.(2[4-9]|[3-9][0-9])$')\x1a\x8a\x02\n" +
	"\x1fcontrol_plane_egress_mode_valid\x12ccontrol_plane_egress_mode must be 'AWS_MANAGED', 'CUSTOMER_ROUTED', or 'CUSTOMER_ISOLATED' when set\x1a\x81\x01this.control_plane_egress_mode == '' || this.control_plane_egress_mode in ['AWS_MANAGED', 'CUSTOMER_ROUTED', 'CUSTOMER_ISOLATED']\x1az\n" +
	"\x0fip_family_valid\x12+ip_family must be 'ipv4' or 'ipv6' when set\x1a:this.ip_family == '' || this.ip_family in ['ipv4', 'ipv6']\x1a\x90\x02\n" +
	"\x18service_ipv4_cidr_format\x12?service_ipv4_cidr must be an IPv4 CIDR with a /12 to /24 prefix\x1a\xb2\x01this.service_ipv4_cidr == '' || this.service_ipv4_cidr.matches('^(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]?[0-9])(?:\\\\.(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]?[0-9])){3}/(?:1[2-9]|2[0-4])$')\x1a\x90\x01\n" +
	"\x1bservice_ipv4_cidr_ipv4_only\x127service_ipv4_cidr only applies when ip_family is 'ipv4'\x1a8this.service_ipv4_cidr == '' || this.ip_family != 'ipv6'\x1a\xd9\x01\n" +
	"\x0flog_types_valid\x12Ueach log type must be one of: api, audit, authenticator, controllerManager, scheduler\x1aothis.enabled_cluster_log_types.all(t, t in ['api', 'audit', 'authenticator', 'controllerManager', 'scheduler'])\x1a\xb6\x01\n" +
	"\x1aupgrade_support_type_valid\x12>upgrade_support_type must be 'STANDARD' or 'EXTENDED' when set\x1aXthis.upgrade_support_type == '' || this.upgrade_support_type in ['STANDARD', 'EXTENDED']\x1a\x96\x02\n" +
	" control_plane_scaling_tier_valid\x12hcontrol_plane_scaling_tier must be 'standard', 'tier-xl', 'tier-2xl', 'tier-4xl', or 'tier-8xl' when set\x1a\x87\x01this.control_plane_scaling_tier == '' || this.control_plane_scaling_tier in ['standard', 'tier-xl', 'tier-2xl', 'tier-4xl', 'tier-8xl']B\x19\n" +
	"\x17_endpoint_public_accessB \n" +
	"\x1e_bootstrap_self_managed_addons\"\xc2\x03\n" +
	"\x19AwsEksClusterAccessConfig\x12/\n" +
	"\x13authentication_mode\x18\x01 \x01(\tR\x12authenticationMode\x12a\n" +
	"+bootstrap_cluster_creator_admin_permissions\x18\x02 \x01(\bH\x00R'bootstrapClusterCreatorAdminPermissions\x88\x01\x01:\xe0\x01\xbaH\xdc\x01\x1a\xd9\x01\n" +
	"\x19authentication_mode_valid\x12Qauthentication_mode must be 'API', 'API_AND_CONFIG_MAP', or 'CONFIG_MAP' when set\x1aithis.authentication_mode == '' || this.authentication_mode in ['API', 'API_AND_CONFIG_MAP', 'CONFIG_MAP']B.\n" +
	",_bootstrap_cluster_creator_admin_permissions\"\xeb\x04\n" +
	"\x15AwsEksClusterAutoMode\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12'\n" +
	"\n" +
	"node_pools\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\x18\x01R\tnodePools\x12x\n" +
	"\rnode_role_arn\x18\x03 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB \x88\xd4a\xf0\a\x92\xd4a\x17status.outputs.role_arnR\vnodeRoleArn:\x94\x03\xbaH\x90\x03\x1a\x84\x01\n" +
	"\x10node_pools_valid\x124each node pool must be 'general-purpose' or 'system'\x1a:this.node_pools.all(p, p in ['general-purpose', 'system'])\x1a{\n" +
	"\x1anode_pools_require_enabled\x121node_pools only applies when auto mode is enabled\x1a*this.enabled || size(this.node_pools) == 0\x1a\x89\x01\n" +
	"\x18node_role_requires_pools\x126node_role_arn is required when node_pools is non-empty\x1a5size(this.node_pools) == 0 || has(this.node_role_arn)\"\xcd\a\n" +
	"\x1bAwsEksClusterRemoteNetworks\x12\x8e\x01\n" +
	"\n" +
	"node_cidrs\x18\x01 \x03(\tBo\xbaHl\x92\x01i\"gre2c^(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}/(?:[0-9]|[12]\\d|3[0-2])$R\tnodeCidrs\x12\x8c\x01\n" +
	"\tpod_cidrs\x18\x02 \x03(\tBo\xbaHl\x92\x01i\"gre2c^(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(?:\\.(?:25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}/(?:[0-9]|[12]\\d|3[0-2])$R\bpodCidrs:\x8d\x05\xbaH\x89\x05\x1a\x8f\x01\n" +
	"\x14at_least_one_network\x12@remote_networks requires at least one of node_cidrs or pod_cidrs\x1a5size(this.node_cidrs) > 0 || size(this.pod_cidrs) > 0\x1a\xfa\x01\n" +
	"\x18node_cidrs_private_range\x12Yeach node CIDR must be within 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, or 100.64.0.0/10\x1a\x82\x01this.node_cidrs.all(c, c.matches('^(10|172\\\\.(1[6-9]|2[0-9]|3[0-1])|192\\\\.168|100\\\\.(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-7]))\\\\.'))\x1a\xf7\x01\n" +
	"\x17pod_cidrs_private_range\x12Xeach pod CIDR must be within 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, or 100.64.0.0/10\x1a\x81\x01this.pod_cidrs.all(c, c.matches('^(10|172\\\\.(1[6-9]|2[0-9]|3[0-1])|192\\\\.168|100\\\\.(6[4-9]|[7-9][0-9]|1[0-1][0-9]|12[0-7]))\\\\.'))B\xcb\x02\n" +
	"*com.dev.planton.aws.awsekscluster.v1alpha1B\tSpecProtoP\x01ZUgithub.com/plantonhq/planton/catalog/aws/awsekscluster/v1alpha1;awseksclusterv1alpha1\xa2\x02\x04DPAA\xaa\x02&Dev.Planton.Aws.Awsekscluster.V1alpha1\xca\x02&Dev\\Planton\\Aws\\Awsekscluster\\V1alpha1\xe2\x022Dev\\Planton\\Aws\\Awsekscluster\\V1alpha1\\GPBMetadata\xea\x02*Dev::Planton::Aws::Awsekscluster::V1alpha1b\x06proto3"

var (
	file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDesc), len(file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDescData
}

var file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_catalog_aws_awsekscluster_v1alpha1_spec_proto_goTypes = []any{
	(*AwsEksClusterSpec)(nil),           // 0: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec
	(*AwsEksClusterAccessConfig)(nil),   // 1: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterAccessConfig
	(*AwsEksClusterAutoMode)(nil),       // 2: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterAutoMode
	(*AwsEksClusterRemoteNetworks)(nil), // 3: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterRemoteNetworks
	(*v1.StringValueOrRef)(nil),         // 4: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_aws_awsekscluster_v1alpha1_spec_proto_depIdxs = []int32{
	4, // 0: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec.subnet_ids:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	4, // 1: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec.cluster_role_arn:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	4, // 2: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec.security_group_ids:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	4, // 3: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec.kms_key_arn:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 4: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec.access_config:type_name -> dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterAccessConfig
	2, // 5: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec.auto_mode:type_name -> dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterAutoMode
	3, // 6: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterSpec.remote_networks:type_name -> dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterRemoteNetworks
	4, // 7: dev.planton.aws.awsekscluster.v1alpha1.AwsEksClusterAutoMode.node_role_arn:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_catalog_aws_awsekscluster_v1alpha1_spec_proto_init() }
func file_catalog_aws_awsekscluster_v1alpha1_spec_proto_init() {
	if File_catalog_aws_awsekscluster_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDesc), len(file_catalog_aws_awsekscluster_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_aws_awsekscluster_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_aws_awsekscluster_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_aws_awsekscluster_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_aws_awsekscluster_v1alpha1_spec_proto = out.File
	file_catalog_aws_awsekscluster_v1alpha1_spec_proto_goTypes = nil
	file_catalog_aws_awsekscluster_v1alpha1_spec_proto_depIdxs = nil
}
