apiVersion: azure.project-planton.org/v1
kind: AzureStorageAccount
metadata:
  name: test-storage
  org: test-org
  env: dev
spec:
  region: eastus
  resource_group: test-rg
  account_kind: STORAGE_V2
  account_tier: STANDARD
  replication_type: LRS
  access_tier: HOT
  enable_https_traffic_only: true
  min_tls_version: TLS1_2
  network_rules:
    default_action: DENY
    bypass_azure_services: true
    ip_rules:
      - "203.0.113.0/24"
  blob_properties:
    enable_versioning: false
    soft_delete_retention_days: 7
    container_soft_delete_retention_days: 7
  containers:
    - name: data
      access_type: PRIVATE
    - name: logs
      access_type: PRIVATE
    - name: backups
      access_type: PRIVATE
