apiVersion: aws.planton.dev/v1alpha1
kind: AwsLambda
metadata:
  name: my-container-lambda
spec:
  region: <aws-region>
  role_arn:
    valueFrom:
      kind: AwsIamRole
      name: <execution-role-name>
      fieldPath: status.outputs.role_arn
  image_uri: <ecr-image-uri>
  memory_size_mb: 512
  timeout_seconds: 60
  architecture: arm64
