apiVersion: aws.planton.dev/v1alpha1
kind: AwsLambdaEventSourceMapping
metadata:
  name: analytics-consumer
spec:
  region: us-west-2
  functionArn:
    valueFrom:
      kind: AwsLambda
      name: stream-processor
      fieldPath: status.outputs.function_arn
  eventSourceArn:
    valueFrom:
      kind: AwsKinesisStream
      name: clickstream
      fieldPath: status.outputs.stream_arn
  startingPosition: TRIM_HORIZON
  functionResponseTypes:
    - ReportBatchItemFailures
  parallelizationFactor: 2
