syntax = "proto3";

package dev.planton.provider.kubernetes.kubernetesopensearchoperator.v1alpha1;

import "dev/planton/provider/kubernetes/kubernetesopensearchoperator/v1alpha1/api.proto";
import "dev/planton/provider/kubernetes/provider.proto";

//kubernetes-open-search-operator stack-input
message KubernetesOpenSearchOperatorStackInput {
  //target cloud-resource
  KubernetesOpenSearchOperator target = 1;
  //provider-config
  dev.planton.provider.kubernetes.KubernetesProviderConfig provider_config = 2;
}
