syntax = "proto3";

package dev.planton.openstack.openstackloadbalancerpool.v1alpha1;

import "catalog/openstack/openstackloadbalancerpool/v1alpha1/api.proto";
import "catalog/openstack/provider.proto";

// OpenStackLoadBalancerPoolStackInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message OpenStackLoadBalancerPoolStackInput {
  // target cloud-resource to be deployed
  OpenStackLoadBalancerPool target = 1;
  // provider-config for OpenStack authentication
  dev.planton.openstack.OpenStackProviderConfig provider_config = 2;
}
