// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azuremssqlserver/v1alpha1/spec.proto

package azuremssqlserverv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	_ "github.com/plantonhq/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How clients establish connections to the server.
type AzureMssqlServerConnectionPolicy int32

const (
	// Not specified: Azure's Default policy (Redirect for Azure-internal
	// clients, Proxy for external ones).
	AzureMssqlServerConnectionPolicy_azure_mssql_server_connection_policy_unspecified AzureMssqlServerConnectionPolicy = 0
	// Redirect inside Azure, Proxy from outside -- Azure's default.
	AzureMssqlServerConnectionPolicy_DEFAULT AzureMssqlServerConnectionPolicy = 1
	// All connections funnel through the regional gateway on port 1433.
	// Simplest firewalling, highest latency.
	AzureMssqlServerConnectionPolicy_PROXY AzureMssqlServerConnectionPolicy = 2
	// Clients are redirected to the database node after login -- the
	// lowest latency, but requires ports 11000-11999 open alongside 1433.
	AzureMssqlServerConnectionPolicy_REDIRECT AzureMssqlServerConnectionPolicy = 3
)

// Enum value maps for AzureMssqlServerConnectionPolicy.
var (
	AzureMssqlServerConnectionPolicy_name = map[int32]string{
		0: "azure_mssql_server_connection_policy_unspecified",
		1: "DEFAULT",
		2: "PROXY",
		3: "REDIRECT",
	}
	AzureMssqlServerConnectionPolicy_value = map[string]int32{
		"azure_mssql_server_connection_policy_unspecified": 0,
		"DEFAULT":  1,
		"PROXY":    2,
		"REDIRECT": 3,
	}
)

func (x AzureMssqlServerConnectionPolicy) Enum() *AzureMssqlServerConnectionPolicy {
	p := new(AzureMssqlServerConnectionPolicy)
	*p = x
	return p
}

func (x AzureMssqlServerConnectionPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AzureMssqlServerConnectionPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[0].Descriptor()
}

func (AzureMssqlServerConnectionPolicy) Type() protoreflect.EnumType {
	return &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[0]
}

func (x AzureMssqlServerConnectionPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AzureMssqlServerConnectionPolicy.Descriptor instead.
func (AzureMssqlServerConnectionPolicy) EnumDescriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

// The server's managed-identity flavor.
type AzureMssqlServerIdentityType int32

const (
	// Not specified -- invalid; choose an explicit type when the identity
	// block is present.
	AzureMssqlServerIdentityType_azure_mssql_server_identity_type_unspecified AzureMssqlServerIdentityType = 0
	// Azure creates and rotates an identity tied to the server's
	// lifecycle.
	AzureMssqlServerIdentityType_SYSTEM_ASSIGNED AzureMssqlServerIdentityType = 1
	// Attach pre-existing user-assigned identities (identity_ids).
	AzureMssqlServerIdentityType_USER_ASSIGNED AzureMssqlServerIdentityType = 2
	// Both a system-assigned identity and the attached user-assigned
	// identities.
	AzureMssqlServerIdentityType_SYSTEM_AND_USER_ASSIGNED AzureMssqlServerIdentityType = 3
)

// Enum value maps for AzureMssqlServerIdentityType.
var (
	AzureMssqlServerIdentityType_name = map[int32]string{
		0: "azure_mssql_server_identity_type_unspecified",
		1: "SYSTEM_ASSIGNED",
		2: "USER_ASSIGNED",
		3: "SYSTEM_AND_USER_ASSIGNED",
	}
	AzureMssqlServerIdentityType_value = map[string]int32{
		"azure_mssql_server_identity_type_unspecified": 0,
		"SYSTEM_ASSIGNED":          1,
		"USER_ASSIGNED":            2,
		"SYSTEM_AND_USER_ASSIGNED": 3,
	}
)

func (x AzureMssqlServerIdentityType) Enum() *AzureMssqlServerIdentityType {
	p := new(AzureMssqlServerIdentityType)
	*p = x
	return p
}

func (x AzureMssqlServerIdentityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AzureMssqlServerIdentityType) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[1].Descriptor()
}

func (AzureMssqlServerIdentityType) Type() protoreflect.EnumType {
	return &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[1]
}

func (x AzureMssqlServerIdentityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AzureMssqlServerIdentityType.Descriptor instead.
func (AzureMssqlServerIdentityType) EnumDescriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

// Whether the Defender security-alert policy is enforced.
type AzureMssqlServerSecurityAlertPolicyState int32

const (
	// Not specified -- invalid; choose an explicit state when the policy
	// block is present.
	AzureMssqlServerSecurityAlertPolicyState_azure_mssql_server_security_alert_policy_state_unspecified AzureMssqlServerSecurityAlertPolicyState = 0
	// Threat detection is on.
	AzureMssqlServerSecurityAlertPolicyState_ENABLED AzureMssqlServerSecurityAlertPolicyState = 1
	// Threat detection is configured but off.
	AzureMssqlServerSecurityAlertPolicyState_DISABLED AzureMssqlServerSecurityAlertPolicyState = 2
)

// Enum value maps for AzureMssqlServerSecurityAlertPolicyState.
var (
	AzureMssqlServerSecurityAlertPolicyState_name = map[int32]string{
		0: "azure_mssql_server_security_alert_policy_state_unspecified",
		1: "ENABLED",
		2: "DISABLED",
	}
	AzureMssqlServerSecurityAlertPolicyState_value = map[string]int32{
		"azure_mssql_server_security_alert_policy_state_unspecified": 0,
		"ENABLED":  1,
		"DISABLED": 2,
	}
)

func (x AzureMssqlServerSecurityAlertPolicyState) Enum() *AzureMssqlServerSecurityAlertPolicyState {
	p := new(AzureMssqlServerSecurityAlertPolicyState)
	*p = x
	return p
}

func (x AzureMssqlServerSecurityAlertPolicyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AzureMssqlServerSecurityAlertPolicyState) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[2].Descriptor()
}

func (AzureMssqlServerSecurityAlertPolicyState) Type() protoreflect.EnumType {
	return &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[2]
}

func (x AzureMssqlServerSecurityAlertPolicyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AzureMssqlServerSecurityAlertPolicyState.Descriptor instead.
func (AzureMssqlServerSecurityAlertPolicyState) EnumDescriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{2}
}

// The alert classes Microsoft Defender for SQL can raise.
type AzureMssqlServerSecurityAlertType int32

const (
	// Not specified -- invalid as a disabled_alerts entry.
	AzureMssqlServerSecurityAlertType_azure_mssql_server_security_alert_type_unspecified AzureMssqlServerSecurityAlertType = 0
	// Potential SQL injection attacks.
	AzureMssqlServerSecurityAlertType_SQL_INJECTION AzureMssqlServerSecurityAlertType = 1
	// Application code vulnerable to SQL injection.
	AzureMssqlServerSecurityAlertType_SQL_INJECTION_VULNERABILITY AzureMssqlServerSecurityAlertType = 2
	// Logins from unusual locations, principals, or applications.
	AzureMssqlServerSecurityAlertType_ACCESS_ANOMALY AzureMssqlServerSecurityAlertType = 3
	// Unusually large result sets or data movement.
	AzureMssqlServerSecurityAlertType_DATA_EXFILTRATION AzureMssqlServerSecurityAlertType = 4
	// High-privilege or destructive statements.
	AzureMssqlServerSecurityAlertType_UNSAFE_ACTION AzureMssqlServerSecurityAlertType = 5
)

// Enum value maps for AzureMssqlServerSecurityAlertType.
var (
	AzureMssqlServerSecurityAlertType_name = map[int32]string{
		0: "azure_mssql_server_security_alert_type_unspecified",
		1: "SQL_INJECTION",
		2: "SQL_INJECTION_VULNERABILITY",
		3: "ACCESS_ANOMALY",
		4: "DATA_EXFILTRATION",
		5: "UNSAFE_ACTION",
	}
	AzureMssqlServerSecurityAlertType_value = map[string]int32{
		"azure_mssql_server_security_alert_type_unspecified": 0,
		"SQL_INJECTION":               1,
		"SQL_INJECTION_VULNERABILITY": 2,
		"ACCESS_ANOMALY":              3,
		"DATA_EXFILTRATION":           4,
		"UNSAFE_ACTION":               5,
	}
)

func (x AzureMssqlServerSecurityAlertType) Enum() *AzureMssqlServerSecurityAlertType {
	p := new(AzureMssqlServerSecurityAlertType)
	*p = x
	return p
}

func (x AzureMssqlServerSecurityAlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AzureMssqlServerSecurityAlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[3].Descriptor()
}

func (AzureMssqlServerSecurityAlertType) Type() protoreflect.EnumType {
	return &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes[3]
}

func (x AzureMssqlServerSecurityAlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AzureMssqlServerSecurityAlertType.Descriptor instead.
func (AzureMssqlServerSecurityAlertType) EnumDescriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{3}
}

// **AzureMssqlServerSpec** defines the configuration for creating an Azure
// SQL Database logical server: the administrative container that carries
// the login endpoint, authentication (SQL and/or Microsoft Entra),
// networking posture, transparent-data-encryption key, auditing, and
// Microsoft Defender settings for every database and elastic pool created
// on it.
//
// **Architecture**: unlike PostgreSQL and MySQL Flexible Servers (physical
// servers with compute and storage), Azure SQL uses a **logical server +
// database** model. The server has no compute of its own -- each
// AzureMssqlDatabase carries its own SKU and storage and each
// AzureMssqlElasticPool carries shared compute, so databases and pools are
// first-class kinds referencing this server's `server_id` output rather
// than fields folded into this spec.
//
// **Network access**: Azure SQL does not support VNet delegation. Public
// reachability is `public_network_access_enabled` with `firewall_rules`
// (IPv4 allowlist) and `virtual_network_rules` (subnet service-endpoint
// allowlist); private connectivity is exclusively AzurePrivateEndpoint.
// Outbound restriction (`outbound_network_restriction_enabled` +
// `outbound_firewall_rules`) governs where the server may reach OUT to,
// e.g. for elastic queries.
//
// **Authentication** is SQL logins, Microsoft Entra, or both -- matching
// ARM's real contract: at least one of `administrator_login` or an
// `azuread_administrator` with `azuread_authentication_only` must be
// configured. With Entra-only auth the SQL credentials are omitted
// entirely.
//
// **Fixed at creation** (changing replaces the server): `server_name`,
// `region`, `resource_group`, `version`, and `administrator_login` once
// set. Two update-time contracts ARM enforces that validation cannot
// express: `minimum_tls_version` cannot be removed once set, and the
// administrator password cannot change while
// `azuread_authentication_only` is true.
type AzureMssqlServerSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Azure region where the logical server is created (e.g. "eastus",
	// "westeurope"). Changing the region replaces the server.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// The Azure resource group the server is created in. Can be a literal
	// resource-group name or a reference to an AzureResourceGroup's name
	// output. Changing it replaces the server.
	ResourceGroup *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"`
	// The server's name: 1-63 lowercase letters, digits, and hyphens, not
	// starting or ending with a hyphen -- and GLOBALLY unique across Azure,
	// because it becomes the server's DNS name
	// ({name}.database.windows.net, the fqdn output). Changing the name
	// replaces the server.
	ServerName string `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// The SQL Server version identifier. Unspecified applies "12.0" -- the
	// only version real deployments use (it tracks the current Azure SQL
	// engine; "2.0" is the SQL Server 2005-era legacy identifier kept for
	// API completeness). Fixed at creation.
	Version *string `protobuf:"bytes,4,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// The administrator login for SQL authentication. Required unless the
	// server is Entra-only (azuread_administrator.azuread_authentication_only
	// = true). Azure reserves names like "admin", "administrator", "sa",
	// "root", "dbmanager", "loginmanager", "dbo", "guest", and "public".
	// The login is fixed once set.
	AdministratorLogin string `protobuf:"bytes,5,opt,name=administrator_login,json=administratorLogin,proto3" json:"administrator_login,omitempty"`
	// The administrator password for SQL authentication (8-128 characters
	// from at least three of: uppercase, lowercase, digits, special
	// characters). Can be a literal value or a reference to another
	// resource's output. Required with administrator_login; rotates in
	// place -- but ARM rejects a password change while
	// azuread_authentication_only is true. The provider's write-only
	// variant (administrator_login_password_wo + its version counter) is
	// deliberately not modeled: it is an ephemeral input that duplicates
	// this field, and secret values here are already reference-resolved
	// at deploy time rather than stored in the manifest.
	AdministratorPassword *v1.StringValueOrRef `protobuf:"bytes,6,opt,name=administrator_password,json=administratorPassword,proto3" json:"administrator_password,omitempty"`
	// The server's Microsoft Entra (Azure AD) administrator -- the
	// principal (use a group to admit a team) that can administer the
	// server with directory tokens. Enables Entra authentication; with
	// azuread_authentication_only it becomes the ONLY authentication
	// mechanism and the SQL credentials must be omitted.
	AzureadAdministrator *AzureMssqlServerAzureadAdministrator `protobuf:"bytes,7,opt,name=azuread_administrator,json=azureadAdministrator,proto3" json:"azuread_administrator,omitempty"`
	// The server's managed identity. Required for the
	// transparent-data-encryption customer-managed key (the identity
	// unwraps the key) and usable by databases for their own CMK.
	Identity *AzureMssqlServerIdentity `protobuf:"bytes,8,opt,name=identity,proto3" json:"identity,omitempty"`
	// Which user-assigned identity (by ARM ID) is the server's PRIMARY
	// identity -- the one ARM uses for Key Vault access when several are
	// attached. Must be one of identity.identity_ids. Required when the
	// identity type includes USER_ASSIGNED.
	PrimaryUserAssignedIdentityId *v1.StringValueOrRef `protobuf:"bytes,9,opt,name=primary_user_assigned_identity_id,json=primaryUserAssignedIdentityId,proto3" json:"primary_user_assigned_identity_id,omitempty"`
	// Server-level transparent-data-encryption customer-managed key: every
	// database's TDE protector defaults to this Key Vault key instead of a
	// service-managed key. Takes a VERSIONED key ID (ARM pins the exact
	// version at the server level), so the default reference points at an
	// AzureKeyVaultKey's key_id output. Requires an identity with
	// wrap/unwrap access on the key's vault.
	TransparentDataEncryptionKeyVaultKeyId *v1.StringValueOrRef `protobuf:"bytes,10,opt,name=transparent_data_encryption_key_vault_key_id,json=transparentDataEncryptionKeyVaultKeyId,proto3" json:"transparent_data_encryption_key_vault_key_id,omitempty"`
	// How clients establish connections. Unspecified applies Azure's
	// Default policy (Redirect inside Azure, Proxy from outside). REDIRECT
	// gives the lowest latency but needs ports 11000-11999 open in
	// addition to 1433; PROXY funnels everything through the gateway on
	// 1433.
	ConnectionPolicy AzureMssqlServerConnectionPolicy `protobuf:"varint,11,opt,name=connection_policy,json=connectionPolicy,proto3,enum=dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerConnectionPolicy" json:"connection_policy,omitempty"`
	// The minimum TLS version for client connections. Azure requires
	// "1.2" (the only accepted value on current API versions -- older
	// protocol floors are retired). Unspecified applies "1.2". ARM rejects
	// removing the floor once set.
	MinimumTlsVersion *string `protobuf:"bytes,12,opt,name=minimum_tls_version,json=minimumTlsVersion,proto3,oneof" json:"minimum_tls_version,omitempty"`
	// Whether the server is reachable over the public internet. When true,
	// firewall_rules and virtual_network_rules control who connects; when
	// false, only private endpoints reach the server. Unspecified applies
	// Azure's default of true.
	PublicNetworkAccessEnabled *bool `protobuf:"varint,13,opt,name=public_network_access_enabled,json=publicNetworkAccessEnabled,proto3,oneof" json:"public_network_access_enabled,omitempty"`
	// Whether OUTBOUND connections from the server (elastic queries,
	// linked external tables) are restricted to the FQDNs in
	// outbound_firewall_rules. Azure's default is false (unrestricted).
	OutboundNetworkRestrictionEnabled bool `protobuf:"varint,14,opt,name=outbound_network_restriction_enabled,json=outboundNetworkRestrictionEnabled,proto3" json:"outbound_network_restriction_enabled,omitempty"`
	// The FQDNs the server may reach out to while outbound restriction is
	// enabled. Each entry is its own ARM outbound-firewall-rule
	// sub-resource.
	OutboundFirewallRules []string `protobuf:"bytes,15,rep,name=outbound_firewall_rules,json=outboundFirewallRules,proto3" json:"outbound_firewall_rules,omitempty"`
	// Whether Microsoft Defender's express vulnerability assessment runs
	// on the server (agentless SQL scanning without a storage account).
	// Azure's default is false.
	ExpressVulnerabilityAssessmentEnabled bool `protobuf:"varint,16,opt,name=express_vulnerability_assessment_enabled,json=expressVulnerabilityAssessmentEnabled,proto3" json:"express_vulnerability_assessment_enabled,omitempty"`
	// Public-endpoint firewall allowlist: each rule admits a contiguous
	// IPv4 range. Only meaningful while public network access is enabled.
	// The special rule 0.0.0.0-0.0.0.0 admits Azure-internal services only
	// (not the internet).
	FirewallRules []*AzureMssqlServerFirewallRule `protobuf:"bytes,17,rep,name=firewall_rules,json=firewallRules,proto3" json:"firewall_rules,omitempty"`
	// Subnet allowlist: each rule admits one subnet through its
	// Microsoft.Sql service endpoint -- the classic (non-Private-Link) way
	// to keep traffic on the Azure backbone. Only meaningful while public
	// network access is enabled.
	VirtualNetworkRules []*AzureMssqlServerVirtualNetworkRule `protobuf:"bytes,18,rep,name=virtual_network_rules,json=virtualNetworkRules,proto3" json:"virtual_network_rules,omitempty"`
	// Server-level SQL auditing: writes audit events for every database on
	// the server to blob storage and/or Azure Monitor. Presence enables
	// auditing; omit the block to leave auditing off.
	ExtendedAuditing *AzureMssqlServerExtendedAuditing `protobuf:"bytes,19,opt,name=extended_auditing,json=extendedAuditing,proto3" json:"extended_auditing,omitempty"`
	// Microsoft Defender for SQL threat detection at the server scope:
	// alerting on SQL injection, anomalous access, data exfiltration, and
	// unsafe actions. Presence configures the policy; omit the block to
	// leave Defender's advanced threat protection unconfigured.
	SecurityAlertPolicy *AzureMssqlServerSecurityAlertPolicy `protobuf:"bytes,20,opt,name=security_alert_policy,json=securityAlertPolicy,proto3" json:"security_alert_policy,omitempty"`
	// Free-form tags applied to the server, merged over the
	// Planton-derived resource tags (organization, environment, resource
	// id); a user tag with the same key wins. Tags are Azure's governance
	// surface -- Azure Policy enforces them and Microsoft Cost Management
	// groups by them.
	Tags          map[string]string `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureMssqlServerSpec) Reset() {
	*x = AzureMssqlServerSpec{}
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMssqlServerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMssqlServerSpec) ProtoMessage() {}

func (x *AzureMssqlServerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMssqlServerSpec.ProtoReflect.Descriptor instead.
func (*AzureMssqlServerSpec) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AzureMssqlServerSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AzureMssqlServerSpec) GetResourceGroup() *v1.StringValueOrRef {
	if x != nil {
		return x.ResourceGroup
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *AzureMssqlServerSpec) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *AzureMssqlServerSpec) GetAdministratorLogin() string {
	if x != nil {
		return x.AdministratorLogin
	}
	return ""
}

func (x *AzureMssqlServerSpec) GetAdministratorPassword() *v1.StringValueOrRef {
	if x != nil {
		return x.AdministratorPassword
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetAzureadAdministrator() *AzureMssqlServerAzureadAdministrator {
	if x != nil {
		return x.AzureadAdministrator
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetIdentity() *AzureMssqlServerIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetPrimaryUserAssignedIdentityId() *v1.StringValueOrRef {
	if x != nil {
		return x.PrimaryUserAssignedIdentityId
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetTransparentDataEncryptionKeyVaultKeyId() *v1.StringValueOrRef {
	if x != nil {
		return x.TransparentDataEncryptionKeyVaultKeyId
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetConnectionPolicy() AzureMssqlServerConnectionPolicy {
	if x != nil {
		return x.ConnectionPolicy
	}
	return AzureMssqlServerConnectionPolicy_azure_mssql_server_connection_policy_unspecified
}

func (x *AzureMssqlServerSpec) GetMinimumTlsVersion() string {
	if x != nil && x.MinimumTlsVersion != nil {
		return *x.MinimumTlsVersion
	}
	return ""
}

func (x *AzureMssqlServerSpec) GetPublicNetworkAccessEnabled() bool {
	if x != nil && x.PublicNetworkAccessEnabled != nil {
		return *x.PublicNetworkAccessEnabled
	}
	return false
}

func (x *AzureMssqlServerSpec) GetOutboundNetworkRestrictionEnabled() bool {
	if x != nil {
		return x.OutboundNetworkRestrictionEnabled
	}
	return false
}

func (x *AzureMssqlServerSpec) GetOutboundFirewallRules() []string {
	if x != nil {
		return x.OutboundFirewallRules
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetExpressVulnerabilityAssessmentEnabled() bool {
	if x != nil {
		return x.ExpressVulnerabilityAssessmentEnabled
	}
	return false
}

func (x *AzureMssqlServerSpec) GetFirewallRules() []*AzureMssqlServerFirewallRule {
	if x != nil {
		return x.FirewallRules
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetVirtualNetworkRules() []*AzureMssqlServerVirtualNetworkRule {
	if x != nil {
		return x.VirtualNetworkRules
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetExtendedAuditing() *AzureMssqlServerExtendedAuditing {
	if x != nil {
		return x.ExtendedAuditing
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetSecurityAlertPolicy() *AzureMssqlServerSecurityAlertPolicy {
	if x != nil {
		return x.SecurityAlertPolicy
	}
	return nil
}

func (x *AzureMssqlServerSpec) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// The server's Microsoft Entra administrator grant.
type AzureMssqlServerAzureadAdministrator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The administrator principal's display name as it appears in Entra
	// (e.g. "dba-team@contoso.com" for a user, the group name for a
	// group). Used as the login name for Entra connections.
	LoginUsername string `protobuf:"bytes,1,opt,name=login_username,json=loginUsername,proto3" json:"login_username,omitempty"`
	// The directory object ID of the Entra principal being granted the
	// administrator role. The default reference points at an
	// AzureUserAssignedIdentity's principal_id output so a deployment
	// identity can administer the server; for a user or group supply the
	// directory object ID literally.
	ObjectId *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// The Entra tenant of the administrator principal. Leave unset to use
	// the deploying credential's tenant -- the correct value for virtually
	// every deployment.
	TenantId *string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// When true, Entra becomes the ONLY authentication mechanism: SQL
	// logins are disabled server-wide and the SQL admin credentials must
	// be omitted from the spec. Azure's recommended posture for
	// passwordless estates.
	AzureadAuthenticationOnly bool `protobuf:"varint,4,opt,name=azuread_authentication_only,json=azureadAuthenticationOnly,proto3" json:"azuread_authentication_only,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AzureMssqlServerAzureadAdministrator) Reset() {
	*x = AzureMssqlServerAzureadAdministrator{}
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMssqlServerAzureadAdministrator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMssqlServerAzureadAdministrator) ProtoMessage() {}

func (x *AzureMssqlServerAzureadAdministrator) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMssqlServerAzureadAdministrator.ProtoReflect.Descriptor instead.
func (*AzureMssqlServerAzureadAdministrator) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *AzureMssqlServerAzureadAdministrator) GetLoginUsername() string {
	if x != nil {
		return x.LoginUsername
	}
	return ""
}

func (x *AzureMssqlServerAzureadAdministrator) GetObjectId() *v1.StringValueOrRef {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

func (x *AzureMssqlServerAzureadAdministrator) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *AzureMssqlServerAzureadAdministrator) GetAzureadAuthenticationOnly() bool {
	if x != nil {
		return x.AzureadAuthenticationOnly
	}
	return false
}

// The server's managed identity.
type AzureMssqlServerIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identity flavor. SYSTEM_ASSIGNED is created and rotated by
	// Azure with the server's lifecycle; USER_ASSIGNED attaches
	// pre-existing identities (required when Key Vault grants must exist
	// BEFORE the server does, e.g. for TDE CMK).
	Type AzureMssqlServerIdentityType `protobuf:"varint,1,opt,name=type,proto3,enum=dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentityType" json:"type,omitempty"`
	// The user-assigned identities to attach, by ARM ID. Required (and
	// only allowed) when the type includes USER_ASSIGNED.
	IdentityIds   []*v1.StringValueOrRef `protobuf:"bytes,2,rep,name=identity_ids,json=identityIds,proto3" json:"identity_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureMssqlServerIdentity) Reset() {
	*x = AzureMssqlServerIdentity{}
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMssqlServerIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMssqlServerIdentity) ProtoMessage() {}

func (x *AzureMssqlServerIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMssqlServerIdentity.ProtoReflect.Descriptor instead.
func (*AzureMssqlServerIdentity) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{2}
}

func (x *AzureMssqlServerIdentity) GetType() AzureMssqlServerIdentityType {
	if x != nil {
		return x.Type
	}
	return AzureMssqlServerIdentityType_azure_mssql_server_identity_type_unspecified
}

func (x *AzureMssqlServerIdentity) GetIdentityIds() []*v1.StringValueOrRef {
	if x != nil {
		return x.IdentityIds
	}
	return nil
}

// One public-endpoint firewall rule admitting a contiguous IPv4 range.
type AzureMssqlServerFirewallRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rule's name, unique within the server. E.g. "allow-office",
	// "allow-azure-services".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The first IPv4 address of the admitted range (inclusive). Use
	// 0.0.0.0 for both start and end to admit Azure-internal services.
	StartIpAddress string `protobuf:"bytes,2,opt,name=start_ip_address,json=startIpAddress,proto3" json:"start_ip_address,omitempty"`
	// The last IPv4 address of the admitted range (inclusive). Equal to
	// start_ip_address for a single-address rule.
	EndIpAddress  string `protobuf:"bytes,3,opt,name=end_ip_address,json=endIpAddress,proto3" json:"end_ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureMssqlServerFirewallRule) Reset() {
	*x = AzureMssqlServerFirewallRule{}
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMssqlServerFirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMssqlServerFirewallRule) ProtoMessage() {}

func (x *AzureMssqlServerFirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMssqlServerFirewallRule.ProtoReflect.Descriptor instead.
func (*AzureMssqlServerFirewallRule) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{3}
}

func (x *AzureMssqlServerFirewallRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AzureMssqlServerFirewallRule) GetStartIpAddress() string {
	if x != nil {
		return x.StartIpAddress
	}
	return ""
}

func (x *AzureMssqlServerFirewallRule) GetEndIpAddress() string {
	if x != nil {
		return x.EndIpAddress
	}
	return ""
}

// One subnet admitted through its Microsoft.Sql service endpoint.
type AzureMssqlServerVirtualNetworkRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rule's name, unique within the server. E.g. "allow-app-subnet".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The subnet to admit, by ARM ID. The subnet needs the Microsoft.Sql
	// service endpoint enabled (see AzureSubnet.service_endpoints) unless
	// ignore_missing_vnet_service_endpoint is set.
	SubnetId *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// Create the rule even while the subnet's Microsoft.Sql service
	// endpoint is not yet enabled (traffic flows once it is). Azure's
	// default is false.
	IgnoreMissingVnetServiceEndpoint bool `protobuf:"varint,3,opt,name=ignore_missing_vnet_service_endpoint,json=ignoreMissingVnetServiceEndpoint,proto3" json:"ignore_missing_vnet_service_endpoint,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *AzureMssqlServerVirtualNetworkRule) Reset() {
	*x = AzureMssqlServerVirtualNetworkRule{}
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMssqlServerVirtualNetworkRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMssqlServerVirtualNetworkRule) ProtoMessage() {}

func (x *AzureMssqlServerVirtualNetworkRule) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMssqlServerVirtualNetworkRule.ProtoReflect.Descriptor instead.
func (*AzureMssqlServerVirtualNetworkRule) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{4}
}

func (x *AzureMssqlServerVirtualNetworkRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AzureMssqlServerVirtualNetworkRule) GetSubnetId() *v1.StringValueOrRef {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

func (x *AzureMssqlServerVirtualNetworkRule) GetIgnoreMissingVnetServiceEndpoint() bool {
	if x != nil {
		return x.IgnoreMissingVnetServiceEndpoint
	}
	return false
}

// Server-level SQL auditing configuration (Azure's extended auditing
// policy). Events go to blob storage (storage_endpoint + access key)
// and/or Azure Monitor (log_monitoring_enabled -- consumed through
// diagnostic settings).
type AzureMssqlServerExtendedAuditing struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blob-storage endpoint audit logs are written to (e.g.
	// https://<account>.blob.core.windows.net). Omit for
	// Azure-Monitor-only auditing.
	StorageEndpoint string `protobuf:"bytes,1,opt,name=storage_endpoint,json=storageEndpoint,proto3" json:"storage_endpoint,omitempty"`
	// The storage account's access key for the audit-log container.
	// Required with storage_endpoint unless the server's managed identity
	// holds the Storage Blob Data Contributor role on the account.
	StorageAccountAccessKey *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=storage_account_access_key,json=storageAccountAccessKey,proto3" json:"storage_account_access_key,omitempty"`
	// Whether the access key belongs to the storage account's secondary
	// key slot (documents which key rotates). Azure's default is false.
	StorageAccountAccessKeyIsSecondary bool `protobuf:"varint,3,opt,name=storage_account_access_key_is_secondary,json=storageAccountAccessKeyIsSecondary,proto3" json:"storage_account_access_key_is_secondary,omitempty"`
	// How many days audit logs are retained in blob storage. 0 (Azure's
	// default) retains them indefinitely.
	RetentionInDays *int32 `protobuf:"varint,4,opt,name=retention_in_days,json=retentionInDays,proto3,oneof" json:"retention_in_days,omitempty"`
	// Whether audit events are also sent to Azure Monitor (surfaced
	// through the server's diagnostic settings as SQLSecurityAuditEvents).
	// Azure's default is true.
	LogMonitoringEnabled *bool `protobuf:"varint,5,opt,name=log_monitoring_enabled,json=logMonitoringEnabled,proto3,oneof" json:"log_monitoring_enabled,omitempty"`
	// The subscription of the audit storage account, when it lives in a
	// different subscription than the server.
	StorageAccountSubscriptionId *string `protobuf:"bytes,6,opt,name=storage_account_subscription_id,json=storageAccountSubscriptionId,proto3,oneof" json:"storage_account_subscription_id,omitempty"`
	// A T-SQL predicate that filters which audit records are captured
	// (e.g. "statement <> 'select 1'"). Omit to capture everything the
	// action groups select.
	PredicateExpression string `protobuf:"bytes,7,opt,name=predicate_expression,json=predicateExpression,proto3" json:"predicate_expression,omitempty"`
	// The audit action groups (and actions) to capture. Omit for Azure's
	// default set: SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP,
	// FAILED_DATABASE_AUTHENTICATION_GROUP, BATCH_COMPLETED_GROUP.
	AuditActionsAndGroups []string `protobuf:"bytes,8,rep,name=audit_actions_and_groups,json=auditActionsAndGroups,proto3" json:"audit_actions_and_groups,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AzureMssqlServerExtendedAuditing) Reset() {
	*x = AzureMssqlServerExtendedAuditing{}
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMssqlServerExtendedAuditing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMssqlServerExtendedAuditing) ProtoMessage() {}

func (x *AzureMssqlServerExtendedAuditing) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMssqlServerExtendedAuditing.ProtoReflect.Descriptor instead.
func (*AzureMssqlServerExtendedAuditing) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{5}
}

func (x *AzureMssqlServerExtendedAuditing) GetStorageEndpoint() string {
	if x != nil {
		return x.StorageEndpoint
	}
	return ""
}

func (x *AzureMssqlServerExtendedAuditing) GetStorageAccountAccessKey() *v1.StringValueOrRef {
	if x != nil {
		return x.StorageAccountAccessKey
	}
	return nil
}

func (x *AzureMssqlServerExtendedAuditing) GetStorageAccountAccessKeyIsSecondary() bool {
	if x != nil {
		return x.StorageAccountAccessKeyIsSecondary
	}
	return false
}

func (x *AzureMssqlServerExtendedAuditing) GetRetentionInDays() int32 {
	if x != nil && x.RetentionInDays != nil {
		return *x.RetentionInDays
	}
	return 0
}

func (x *AzureMssqlServerExtendedAuditing) GetLogMonitoringEnabled() bool {
	if x != nil && x.LogMonitoringEnabled != nil {
		return *x.LogMonitoringEnabled
	}
	return false
}

func (x *AzureMssqlServerExtendedAuditing) GetStorageAccountSubscriptionId() string {
	if x != nil && x.StorageAccountSubscriptionId != nil {
		return *x.StorageAccountSubscriptionId
	}
	return ""
}

func (x *AzureMssqlServerExtendedAuditing) GetPredicateExpression() string {
	if x != nil {
		return x.PredicateExpression
	}
	return ""
}

func (x *AzureMssqlServerExtendedAuditing) GetAuditActionsAndGroups() []string {
	if x != nil {
		return x.AuditActionsAndGroups
	}
	return nil
}

// Microsoft Defender for SQL server-scope threat detection.
type AzureMssqlServerSecurityAlertPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the policy is enforced. ENABLED turns Defender's advanced
	// threat protection on for every database on the server.
	State AzureMssqlServerSecurityAlertPolicyState `protobuf:"varint,1,opt,name=state,proto3,enum=dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicyState" json:"state,omitempty"`
	// Alert classes to suppress. Each entry disables one detector.
	DisabledAlerts []AzureMssqlServerSecurityAlertType `protobuf:"varint,2,rep,packed,name=disabled_alerts,json=disabledAlerts,proto3,enum=dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertType" json:"disabled_alerts,omitempty"`
	// Whether alert emails also go to the subscription administrators.
	// Azure's default is false.
	EmailAccountAdmins bool `protobuf:"varint,3,opt,name=email_account_admins,json=emailAccountAdmins,proto3" json:"email_account_admins,omitempty"`
	// Additional email addresses that receive alerts.
	EmailAddresses []string `protobuf:"bytes,4,rep,name=email_addresses,json=emailAddresses,proto3" json:"email_addresses,omitempty"`
	// How many days threat-detection audit records are retained in the
	// export storage account. 0 (Azure's default) retains indefinitely.
	RetentionDays *int32 `protobuf:"varint,5,opt,name=retention_days,json=retentionDays,proto3,oneof" json:"retention_days,omitempty"`
	// The blob-storage endpoint threat-detection audit records are
	// exported to. Set together with storage_account_access_key; omit both
	// to keep alerts without a storage export.
	StorageEndpoint string `protobuf:"bytes,6,opt,name=storage_endpoint,json=storageEndpoint,proto3" json:"storage_endpoint,omitempty"`
	// The access key of the export storage account. Required with
	// storage_endpoint.
	StorageAccountAccessKey *v1.StringValueOrRef `protobuf:"bytes,7,opt,name=storage_account_access_key,json=storageAccountAccessKey,proto3" json:"storage_account_access_key,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AzureMssqlServerSecurityAlertPolicy) Reset() {
	*x = AzureMssqlServerSecurityAlertPolicy{}
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureMssqlServerSecurityAlertPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureMssqlServerSecurityAlertPolicy) ProtoMessage() {}

func (x *AzureMssqlServerSecurityAlertPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureMssqlServerSecurityAlertPolicy.ProtoReflect.Descriptor instead.
func (*AzureMssqlServerSecurityAlertPolicy) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP(), []int{6}
}

func (x *AzureMssqlServerSecurityAlertPolicy) GetState() AzureMssqlServerSecurityAlertPolicyState {
	if x != nil {
		return x.State
	}
	return AzureMssqlServerSecurityAlertPolicyState_azure_mssql_server_security_alert_policy_state_unspecified
}

func (x *AzureMssqlServerSecurityAlertPolicy) GetDisabledAlerts() []AzureMssqlServerSecurityAlertType {
	if x != nil {
		return x.DisabledAlerts
	}
	return nil
}

func (x *AzureMssqlServerSecurityAlertPolicy) GetEmailAccountAdmins() bool {
	if x != nil {
		return x.EmailAccountAdmins
	}
	return false
}

func (x *AzureMssqlServerSecurityAlertPolicy) GetEmailAddresses() []string {
	if x != nil {
		return x.EmailAddresses
	}
	return nil
}

func (x *AzureMssqlServerSecurityAlertPolicy) GetRetentionDays() int32 {
	if x != nil && x.RetentionDays != nil {
		return *x.RetentionDays
	}
	return 0
}

func (x *AzureMssqlServerSecurityAlertPolicy) GetStorageEndpoint() string {
	if x != nil {
		return x.StorageEndpoint
	}
	return ""
}

func (x *AzureMssqlServerSecurityAlertPolicy) GetStorageAccountAccessKey() *v1.StringValueOrRef {
	if x != nil {
		return x.StorageAccountAccessKey
	}
	return nil
}

var File_catalog_azure_azuremssqlserver_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"2catalog/azure/azuremssqlserver/v1alpha1/spec.proto\x12+dev.planton.azure.azuremssqlserver.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\x1a\x1cshared/options/options.proto\"\xe7 \n" +
	"\x14AzureMssqlServerSpec\x12\"\n" +
	"\x06region\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06region\x12\x8c\x01\n" +
	"\x0eresource_group\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB1\xbaH\x03\xc8\x01\x01\x88\xd4a\xd0\x0f\x92\xd4a\"status.outputs.resource_group_nameR\rresourceGroup\x12N\n" +
	"\vserver_name\x18\x03 \x01(\tB-\xbaH*\xc8\x01\x01r%\x10\x01\x18?2\x1f^[0-9a-z]([-0-9a-z]*[0-9a-z])?$R\n" +
	"serverName\x12~\n" +
	"\aversion\x18\x04 \x01(\tB_\xbaHT\xba\x01Q\n" +
	"\x13mssql_version_valid\x12!version must be one of: 2.0, 12.0\x1a\x17this in ['2.0', '12.0']\x8a\xa6\x1d\x0412.0H\x00R\aversion\x88\x01\x01\x12\xc3\x02\n" +
	"\x13administrator_login\x18\x05 \x01(\tB\x91\x02\xbaH\x8d\x02\xba\x01\x89\x02\n" +
	"\x1emssql_admin_login_not_reserved\x12{administrator_login cannot be a reserved name (admin, administrator, sa, root, dbmanager, loginmanager, dbo, guest, public)\x1ajthis == '' || !this.matches('^(?i)(admin|administrator|sa|root|dbmanager|loginmanager|dbo|guest|public)$')R\x12administratorLogin\x12o\n" +
	"\x16administrator_password\x18\x06 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x04\xa0\xa6\x1d\x01R\x15administratorPassword\x12\x86\x01\n" +
	"\x15azuread_administrator\x18\a \x01(\v2Q.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerAzureadAdministratorR\x14azureadAdministrator\x12a\n" +
	"\bidentity\x18\b \x01(\v2E.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentityR\bidentity\x12\xa1\x01\n" +
	"!primary_user_assigned_identity_id\x18\t \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB#\x88\xd4a\x8c\x10\x92\xd4a\x1astatus.outputs.identity_idR\x1dprimaryUserAssignedIdentityId\x12\xb0\x01\n" +
	",transparent_data_encryption_key_vault_key_id\x18\n" +
	" \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x1e\x88\xd4a\xe9\x0f\x92\xd4a\x15status.outputs.key_idR&transparentDataEncryptionKeyVaultKeyId\x12z\n" +
	"\x11connection_policy\x18\v \x01(\x0e2M.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerConnectionPolicyR\x10connectionPolicy\x12\xb6\x01\n" +
	"\x13minimum_tls_version\x18\f \x01(\tB\x80\x01\xbaHv\xba\x01s\n" +
	"\x17mssql_tls_version_valid\x12Gminimum_tls_version must be 1.2 (older TLS floors are retired by Azure)\x1a\x0fthis in ['1.2']\x8a\xa6\x1d\x031.2H\x01R\x11minimumTlsVersion\x88\x01\x01\x12P\n" +
	"\x1dpublic_network_access_enabled\x18\r \x01(\bB\b\x8a\xa6\x1d\x04trueH\x02R\x1apublicNetworkAccessEnabled\x88\x01\x01\x12O\n" +
	"$outbound_network_restriction_enabled\x18\x0e \x01(\bR!outboundNetworkRestrictionEnabled\x12D\n" +
	"\x17outbound_firewall_rules\x18\x0f \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\x15outboundFirewallRules\x12W\n" +
	"(express_vulnerability_assessment_enabled\x18\x10 \x01(\bR%expressVulnerabilityAssessmentEnabled\x12p\n" +
	"\x0efirewall_rules\x18\x11 \x03(\v2I.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerFirewallRuleR\rfirewallRules\x12\x83\x01\n" +
	"\x15virtual_network_rules\x18\x12 \x03(\v2O.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerVirtualNetworkRuleR\x13virtualNetworkRules\x12z\n" +
	"\x11extended_auditing\x18\x13 \x01(\v2M.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerExtendedAuditingR\x10extendedAuditing\x12\x84\x01\n" +
	"\x15security_alert_policy\x18\x14 \x01(\v2P.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicyR\x13securityAlertPolicy\x12_\n" +
	"\x04tags\x18\x15 \x03(\v2K.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xff\n" +
	"\xbaH\xfb\n" +
	"\x1a\x95\x02\n" +
	"\x17mssql_at_least_one_auth\x12{configure administrator_login (SQL auth) and/or an azuread_administrator with azuread_authentication_only (Entra-only auth)\x1a}this.administrator_login != '' || (has(this.azuread_administrator) && this.azuread_administrator.azuread_authentication_only)\x1a\xac\x01\n" +
	"\x1fmssql_sql_auth_credentials_pair\x12Cadministrator_login and administrator_password must be set together\x1aD(this.administrator_login != '') == has(this.administrator_password)\x1a\x9c\x02\n" +
	"&mssql_aad_only_forbids_sql_credentials\x12ran Entra-only server (azuread_authentication_only = true) must omit administrator_login and administrator_password\x1a~!(has(this.azuread_administrator) && this.azuread_administrator.azuread_authentication_only) || this.administrator_login == ''\x1a\xe6\x01\n" +
	"#mssql_primary_uai_requires_identity\x12^primary_user_assigned_identity_id requires an identity block whose type includes USER_ASSIGNED\x1a_!has(this.primary_user_assigned_identity_id) || (has(this.identity) && this.identity.type >= 2)\x1a\xd8\x01\n" +
	"\x1fmssql_tde_cmk_requires_identity\x12ftransparent_data_encryption_key_vault_key_id requires an identity block (the identity unwraps the key)\x1aM!has(this.transparent_data_encryption_key_vault_key_id) || has(this.identity)\x1a\xce\x01\n" +
	"(mssql_outbound_rules_require_restriction\x12Koutbound_firewall_rules require outbound_network_restriction_enabled = true\x1aUthis.outbound_firewall_rules.size() == 0 || this.outbound_network_restriction_enabledB\n" +
	"\n" +
	"\b_versionB\x16\n" +
	"\x14_minimum_tls_versionB \n" +
	"\x1e_public_network_access_enabled\"\xd0\x02\n" +
	"$AzureMssqlServerAzureadAdministrator\x121\n" +
	"\x0elogin_username\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\rloginUsername\x12{\n" +
	"\tobject_id\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB*\xbaH\x03\xc8\x01\x01\x88\xd4a\x8c\x10\x92\xd4a\x1bstatus.outputs.principal_idR\bobjectId\x12*\n" +
	"\ttenant_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x00R\btenantId\x88\x01\x01\x12>\n" +
	"\x1bazuread_authentication_only\x18\x04 \x01(\bR\x19azureadAuthenticationOnlyB\f\n" +
	"\n" +
	"_tenant_id\"\xc8\x03\n" +
	"\x18AzureMssqlServerIdentity\x12e\n" +
	"\x04type\x18\x01 \x01(\x0e2I.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentityTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12z\n" +
	"\fidentity_ids\x18\x02 \x03(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB#\x88\xd4a\x8c\x10\x92\xd4a\x1astatus.outputs.identity_idR\videntityIds:\xc8\x01\xbaH\xc4\x01\x1a\xc1\x01\n" +
	"\x1dmssql_identity_ids_match_type\x12lidentity_ids are required for USER_ASSIGNED / SYSTEM_AND_USER_ASSIGNED and must be empty for SYSTEM_ASSIGNED\x1a2(this.type >= 2) == (this.identity_ids.size() > 0)\"\xa9\x01\n" +
	"\x1cAzureMssqlServerFirewallRule\x12!\n" +
	"\x04name\x18\x01 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x01R\x04name\x124\n" +
	"\x10start_ip_address\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02x\x01R\x0estartIpAddress\x120\n" +
	"\x0eend_ip_address\x18\x03 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02x\x01R\fendIpAddress\"\x95\x02\n" +
	"\"AzureMssqlServerVirtualNetworkRule\x12!\n" +
	"\x04name\x18\x01 \x01(\tB\r\xbaH\n" +
	"\xc8\x01\x01r\x05\x10\x01\x18\x80\x01R\x04name\x12|\n" +
	"\tsubnet_id\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB+\xbaH\x03\xc8\x01\x01\x88\xd4a\xdb\x0f\x92\xd4a\x18status.outputs.subnet_id\x98\xd4a\x01R\bsubnetId\x12N\n" +
	"$ignore_missing_vnet_service_endpoint\x18\x03 \x01(\bR ignoreMissingVnetServiceEndpoint\"\xeb\a\n" +
	" AzureMssqlServerExtendedAuditing\x12\xaa\x01\n" +
	"\x10storage_endpoint\x18\x01 \x01(\tB\x7f\xbaH|\xba\x01y\n" +
	"\"mssql_audit_storage_endpoint_https\x12(storage_endpoint must be an https:// URL\x1a)this == '' || this.startsWith('https://')R\x0fstorageEndpoint\x12u\n" +
	"\x1astorage_account_access_key\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x04\xa0\xa6\x1d\x01R\x17storageAccountAccessKey\x12S\n" +
	"'storage_account_access_key_is_secondary\x18\x03 \x01(\bR\"storageAccountAccessKeyIsSecondary\x12;\n" +
	"\x11retention_in_days\x18\x04 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xd5\x19(\x00H\x00R\x0fretentionInDays\x88\x01\x01\x12C\n" +
	"\x16log_monitoring_enabled\x18\x05 \x01(\bB\b\x8a\xa6\x1d\x04trueH\x01R\x14logMonitoringEnabled\x88\x01\x01\x12T\n" +
	"\x1fstorage_account_subscription_id\x18\x06 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x02R\x1cstorageAccountSubscriptionId\x88\x01\x01\x121\n" +
	"\x14predicate_expression\x18\a \x01(\tR\x13predicateExpression\x12E\n" +
	"\x18audit_actions_and_groups\x18\b \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\x15auditActionsAndGroups:\xa6\x01\xbaH\xa2\x01\x1a\x9f\x01\n" +
	"!mssql_audit_key_requires_endpoint\x124storage_account_access_key requires storage_endpoint\x1aD!has(this.storage_account_access_key) || this.storage_endpoint != ''B\x14\n" +
	"\x12_retention_in_daysB\x19\n" +
	"\x17_log_monitoring_enabledB\"\n" +
	" _storage_account_subscription_id\"\xa9\x06\n" +
	"#AzureMssqlServerSecurityAlertPolicy\x12s\n" +
	"\x05state\x18\x01 \x01(\x0e2U.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicyStateB\x06\xbaH\x03\xc8\x01\x01R\x05state\x12\x88\x01\n" +
	"\x0fdisabled_alerts\x18\x02 \x03(\x0e2N.dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertTypeB\x0f\xbaH\f\x92\x01\t\"\a\x82\x01\x04\x10\x01 \x00R\x0edisabledAlerts\x120\n" +
	"\x14email_account_admins\x18\x03 \x01(\bR\x12emailAccountAdmins\x125\n" +
	"\x0femail_addresses\x18\x04 \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x03R\x0eemailAddresses\x123\n" +
	"\x0eretention_days\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00H\x00R\rretentionDays\x88\x01\x01\x12)\n" +
	"\x10storage_endpoint\x18\x06 \x01(\tR\x0fstorageEndpoint\x12u\n" +
	"\x1astorage_account_access_key\x18\a \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\x04\xa0\xa6\x1d\x01R\x17storageAccountAccessKey:\xae\x01\xbaH\xaa\x01\x1a\xa7\x01\n" +
	"\x18mssql_alert_storage_pair\x12Dstorage_endpoint and storage_account_access_key must be set together\x1aE(this.storage_endpoint != '') == has(this.storage_account_access_key)B\x11\n" +
	"\x0f_retention_days*~\n" +
	" AzureMssqlServerConnectionPolicy\x124\n" +
	"0azure_mssql_server_connection_policy_unspecified\x10\x00\x12\v\n" +
	"\aDEFAULT\x10\x01\x12\t\n" +
	"\x05PROXY\x10\x02\x12\f\n" +
	"\bREDIRECT\x10\x03*\x96\x01\n" +
	"\x1cAzureMssqlServerIdentityType\x120\n" +
	",azure_mssql_server_identity_type_unspecified\x10\x00\x12\x13\n" +
	"\x0fSYSTEM_ASSIGNED\x10\x01\x12\x11\n" +
	"\rUSER_ASSIGNED\x10\x02\x12\x1c\n" +
	"\x18SYSTEM_AND_USER_ASSIGNED\x10\x03*\x85\x01\n" +
	"(AzureMssqlServerSecurityAlertPolicyState\x12>\n" +
	":azure_mssql_server_security_alert_policy_state_unspecified\x10\x00\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02*\xcd\x01\n" +
	"!AzureMssqlServerSecurityAlertType\x126\n" +
	"2azure_mssql_server_security_alert_type_unspecified\x10\x00\x12\x11\n" +
	"\rSQL_INJECTION\x10\x01\x12\x1f\n" +
	"\x1bSQL_INJECTION_VULNERABILITY\x10\x02\x12\x12\n" +
	"\x0eACCESS_ANOMALY\x10\x03\x12\x15\n" +
	"\x11DATA_EXFILTRATION\x10\x04\x12\x11\n" +
	"\rUNSAFE_ACTION\x10\x05B\xec\x02\n" +
	"/com.dev.planton.azure.azuremssqlserver.v1alpha1B\tSpecProtoP\x01Z]github.com/plantonhq/planton/catalog/azure/azuremssqlserver/v1alpha1;azuremssqlserverv1alpha1\xa2\x02\x04DPAA\xaa\x02+Dev.Planton.Azure.Azuremssqlserver.V1alpha1\xca\x02+Dev\\Planton\\Azure\\Azuremssqlserver\\V1alpha1\xe2\x027Dev\\Planton\\Azure\\Azuremssqlserver\\V1alpha1\\GPBMetadata\xea\x02/Dev::Planton::Azure::Azuremssqlserver::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDesc), len(file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDescData
}

var file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_goTypes = []any{
	(AzureMssqlServerConnectionPolicy)(0),         // 0: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerConnectionPolicy
	(AzureMssqlServerIdentityType)(0),             // 1: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentityType
	(AzureMssqlServerSecurityAlertPolicyState)(0), // 2: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicyState
	(AzureMssqlServerSecurityAlertType)(0),        // 3: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertType
	(*AzureMssqlServerSpec)(nil),                  // 4: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec
	(*AzureMssqlServerAzureadAdministrator)(nil),  // 5: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerAzureadAdministrator
	(*AzureMssqlServerIdentity)(nil),              // 6: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentity
	(*AzureMssqlServerFirewallRule)(nil),          // 7: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerFirewallRule
	(*AzureMssqlServerVirtualNetworkRule)(nil),    // 8: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerVirtualNetworkRule
	(*AzureMssqlServerExtendedAuditing)(nil),      // 9: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerExtendedAuditing
	(*AzureMssqlServerSecurityAlertPolicy)(nil),   // 10: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicy
	nil,                         // 11: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.TagsEntry
	(*v1.StringValueOrRef)(nil), // 12: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_depIdxs = []int32{
	12, // 0: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.resource_group:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	12, // 1: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.administrator_password:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	5,  // 2: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.azuread_administrator:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerAzureadAdministrator
	6,  // 3: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.identity:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentity
	12, // 4: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.primary_user_assigned_identity_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	12, // 5: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.transparent_data_encryption_key_vault_key_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	0,  // 6: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.connection_policy:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerConnectionPolicy
	7,  // 7: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.firewall_rules:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerFirewallRule
	8,  // 8: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.virtual_network_rules:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerVirtualNetworkRule
	9,  // 9: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.extended_auditing:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerExtendedAuditing
	10, // 10: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.security_alert_policy:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicy
	11, // 11: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.tags:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSpec.TagsEntry
	12, // 12: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerAzureadAdministrator.object_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1,  // 13: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentity.type:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentityType
	12, // 14: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerIdentity.identity_ids:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	12, // 15: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerVirtualNetworkRule.subnet_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	12, // 16: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerExtendedAuditing.storage_account_access_key:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2,  // 17: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicy.state:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicyState
	3,  // 18: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicy.disabled_alerts:type_name -> dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertType
	12, // 19: dev.planton.azure.azuremssqlserver.v1alpha1.AzureMssqlServerSecurityAlertPolicy.storage_account_access_key:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_init() }
func file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_init() {
	if File_catalog_azure_azuremssqlserver_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[1].OneofWrappers = []any{}
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[5].OneofWrappers = []any{}
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDesc), len(file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_depIdxs,
		EnumInfos:         file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_enumTypes,
		MessageInfos:      file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_azure_azuremssqlserver_v1alpha1_spec_proto = out.File
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_goTypes = nil
	file_catalog_azure_azuremssqlserver_v1alpha1_spec_proto_depIdxs = nil
}
