syntax = "proto3";

package dev.planton.provider.azure.azurecontainerappjob.v1;

import "dev/planton/provider/azure/azurecontainerappjob/v1/api.proto";
import "dev/planton/provider/azure/provider.proto";

// AzureContainerAppJobStackInput is the input to the IaC module.
// It contains the target resource and provider configuration.
message AzureContainerAppJobStackInput {
  // target cloud-resource to be deployed
  AzureContainerAppJob target = 1;
  // provider-config for Azure authentication
  dev.planton.provider.azure.AzureProviderConfig provider_config = 2;
}
