apiVersion: aws.planton.dev/v1alpha1
kind: AwsAlb
metadata:
  name: <alb-name>
spec:
  region: <aws-region>
  subnets:
    - value: <public-subnet-id-az1>
    - value: <public-subnet-id-az2>
  securityGroups:
    - value: <alb-security-group-id>
  deleteProtectionEnabled: true
  minimumLoadBalancerCapacityUnits: 500
  ipv4IpamPoolId:
    value: <ipam-pool-id>
