apiVersion: gcp.planton.dev/v1alpha1
kind: GcpSecretManagerSecret
metadata:
  name: residency-secret
spec:
  region: europe-west3
  customerManagedEncryption:
    kmsKey:
      value: projects/my-project/locations/europe-west3/keyRings/residency/cryptoKeys/secrets
  initialVersion:
    data:
      value: replace-with-real-secret
  deletionProtection: true
  deletionPolicy: PREVENT
