apiVersion: aws.planton.dev/v1alpha1
kind: AwsApiGatewayAccountSettings
metadata:
  name: apigw-account-settings
spec:
  region: <aws-region>
  cloudwatchRoleArn:
    valueFrom:
      kind: AwsIamRole
      name: <apigw-logging-role>
      fieldPath: status.outputs.role_arn
