load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "v1alpha1",
    srcs = [
        "acraccessToken.go",
        "acraccessTokenList.go",
        "acraccessTokenPatch.go",
        "beyondtrustWorkloadCredentialsDynamicSecret.go",
        "beyondtrustWorkloadCredentialsDynamicSecretList.go",
        "beyondtrustWorkloadCredentialsDynamicSecretPatch.go",
        "cloudsmithAccessToken.go",
        "cloudsmithAccessTokenList.go",
        "cloudsmithAccessTokenPatch.go",
        "clusterGenerator.go",
        "clusterGeneratorList.go",
        "clusterGeneratorPatch.go",
        "ecrauthorizationToken.go",
        "ecrauthorizationTokenList.go",
        "ecrauthorizationTokenPatch.go",
        "fake.go",
        "fakeList.go",
        "fakePatch.go",
        "gcraccessToken.go",
        "gcraccessTokenList.go",
        "gcraccessTokenPatch.go",
        "generatorState.go",
        "generatorStateList.go",
        "generatorStatePatch.go",
        "githubAccessToken.go",
        "githubAccessTokenList.go",
        "githubAccessTokenPatch.go",
        "gitlabDeployToken.go",
        "gitlabDeployTokenList.go",
        "gitlabDeployTokenPatch.go",
        "grafana.go",
        "grafanaList.go",
        "grafanaPatch.go",
        "init.go",
        "mfa.go",
        "mfalist.go",
        "mfapatch.go",
        "password.go",
        "passwordList.go",
        "passwordPatch.go",
        "pulumiTypes.go",
        "pulumiTypes1.go",
        "quayAccessToken.go",
        "quayAccessTokenList.go",
        "quayAccessTokenPatch.go",
        "sshkey.go",
        "sshkeyList.go",
        "sshkeyPatch.go",
        "stssessionToken.go",
        "stssessionTokenList.go",
        "stssessionTokenPatch.go",
        "uuid.go",
        "uuidlist.go",
        "uuidpatch.go",
        "vaultDynamicSecret.go",
        "vaultDynamicSecretList.go",
        "vaultDynamicSecretPatch.go",
        "webhook.go",
        "webhookList.go",
        "webhookPatch.go",
    ],
    importpath = "github.com/plantonhq/planton/pkg/kubernetes/kubernetestypes/externalsecrets/kubernetes/generators/v1alpha1",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_blang_semver//:semver",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/meta/v1:meta",
        "@com_github_pulumi_pulumi_kubernetes_sdk_v4//go/kubernetes/utilities",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
