// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/azure/azureroleassignment/v1alpha1/api.proto

package azureroleassignmentv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/apis/dev/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AzureRoleAssignment is the top-level API resource for an Azure RBAC role
// assignment -- the grant of a role to a principal at a scope. It is the
// atomic unit of Azure authorization, modeled as a first-class composable
// resource so identities, grants, and the resources they protect are
// independent nodes in an environment's graph.
type AzureRoleAssignment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *AzureRoleAssignmentSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *AzureRoleAssignmentStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureRoleAssignment) Reset() {
	*x = AzureRoleAssignment{}
	mi := &file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureRoleAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureRoleAssignment) ProtoMessage() {}

func (x *AzureRoleAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureRoleAssignment.ProtoReflect.Descriptor instead.
func (*AzureRoleAssignment) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *AzureRoleAssignment) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *AzureRoleAssignment) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *AzureRoleAssignment) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AzureRoleAssignment) GetSpec() *AzureRoleAssignmentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AzureRoleAssignment) GetStatus() *AzureRoleAssignmentStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// AzureRoleAssignmentStatus holds the deployment status and outputs.
type AzureRoleAssignmentStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	Outputs       *AzureRoleAssignmentStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureRoleAssignmentStatus) Reset() {
	*x = AzureRoleAssignmentStatus{}
	mi := &file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureRoleAssignmentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureRoleAssignmentStatus) ProtoMessage() {}

func (x *AzureRoleAssignmentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureRoleAssignmentStatus.ProtoReflect.Descriptor instead.
func (*AzureRoleAssignmentStatus) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *AzureRoleAssignmentStatus) GetOutputs() *AzureRoleAssignmentStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto protoreflect.FileDescriptor

const file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"Adev/planton/provider/azure/azureroleassignment/v1alpha1/api.proto\x127dev.planton.provider.azure.azureroleassignment.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1aBdev/planton/provider/azure/azureroleassignment/v1alpha1/spec.proto\x1aKdev/planton/provider/azure/azureroleassignment/v1alpha1/stack_outputs.proto\x1a!dev/planton/shared/metadata.proto\"\xb2\x03\n" +
	"\x13AzureRoleAssignment\x12B\n" +
	"\vapi_version\x18\x01 \x01(\tB!\xbaH\x1er\x1c\n" +
	"\x1aazure.planton.dev/v1alpha1R\n" +
	"apiVersion\x12.\n" +
	"\x04kind\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\n" +
	"\x13AzureRoleAssignmentR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12l\n" +
	"\x04spec\x18\x04 \x01(\v2P.dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12j\n" +
	"\x06status\x18\x05 \x01(\v2R.dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentStatusR\x06status\"\x8f\x01\n" +
	"\x19AzureRoleAssignmentStatus\x12r\n" +
	"\aoutputs\x18\x01 \x01(\v2X.dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentStackOutputsR\aoutputsB\xc1\x03\n" +
	";com.dev.planton.provider.azure.azureroleassignment.v1alpha1B\bApiProtoP\x01Zugithub.com/plantonhq/planton/apis/dev/planton/provider/azure/azureroleassignment/v1alpha1;azureroleassignmentv1alpha1\xa2\x02\x05DPPAA\xaa\x027Dev.Planton.Provider.Azure.Azureroleassignment.V1alpha1\xca\x027Dev\\Planton\\Provider\\Azure\\Azureroleassignment\\V1alpha1\xe2\x02CDev\\Planton\\Provider\\Azure\\Azureroleassignment\\V1alpha1\\GPBMetadata\xea\x02<Dev::Planton::Provider::Azure::Azureroleassignment::V1alpha1b\x06proto3"

var (
	file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescOnce sync.Once
	file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescData []byte
)

func file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDesc), len(file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDesc)))
	})
	return file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDescData
}

var file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_goTypes = []any{
	(*AzureRoleAssignment)(nil),             // 0: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignment
	(*AzureRoleAssignmentStatus)(nil),       // 1: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentStatus
	(*shared.CloudResourceMetadata)(nil),    // 2: dev.planton.shared.CloudResourceMetadata
	(*AzureRoleAssignmentSpec)(nil),         // 3: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentSpec
	(*AzureRoleAssignmentStackOutputs)(nil), // 4: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentStackOutputs
}
var file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignment.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignment.spec:type_name -> dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentSpec
	1, // 2: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignment.status:type_name -> dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentStatus
	4, // 3: dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentStatus.outputs:type_name -> dev.planton.provider.azure.azureroleassignment.v1alpha1.AzureRoleAssignmentStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_init() }
func file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_init() {
	if File_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto != nil {
		return
	}
	file_dev_planton_provider_azure_azureroleassignment_v1alpha1_spec_proto_init()
	file_dev_planton_provider_azure_azureroleassignment_v1alpha1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDesc), len(file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto = out.File
	file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_goTypes = nil
	file_dev_planton_provider_azure_azureroleassignment_v1alpha1_api_proto_depIdxs = nil
}
