apiVersion: azure.planton.dev/v1alpha1
kind: AzureIpGroup
metadata:
  name: branch-offices
spec:
  region: eastus
  resourceGroup:
    valueFrom:
      name: <resource-group-name>
  name: branch-offices
  cidrs:
    - "198.51.100.0/24"
    - "203.0.113.0/24"
  tags:
    cost-center: <cost-center>
