apiVersion: azure.planton.dev/v1alpha1
kind: AzureVirtualWan
metadata:
  name: my-isolated-wan
spec:
  region: <azure-region>
  resourceGroup:
    value: "<your-resource-group-name>"
  name: my-isolated-wan
  allowBranchToBranchTraffic: false
  office365LocalBreakoutCategory: OPTIMIZE
