# Enable the Identity Toolkit API — a no-op on projects the config kind
# already initialized, and what makes this kind self-sufficient on projects
# configured outside Planton. disable_on_destroy is false: tearing down one
# tenant must never disable authentication for everything else in the
# project.
resource "google_project_service" "identitytoolkit_api" {
  project = local.project_id
  service = "identitytoolkit.googleapis.com"

  disable_dependent_services = true
  disable_on_destroy         = false
}

# An Identity Platform TENANT — an isolated user pool inside a project
# whose Identity Platform config enables multi_tenant.allow_tenants. The
# tenant's resource ID is generated by GCP at create time (display_name is
# the only naming input) and flows to the IdP configs below through the
# created resource's name, never from the spec.
#
# The spec's ONE deletion_policy fans out to the tenant AND every composed
# IdP config — the IdP configs have no life apart from the tenant, so one
# switch governs all of them.
resource "google_identity_platform_tenant" "this" {
  project = local.project_id

  display_name = var.spec.display_name

  allow_password_signup    = var.spec.allow_password_signup ? true : null
  enable_email_link_signin = var.spec.enable_email_link_signin ? true : null
  disable_auth             = var.spec.disable_auth ? true : null

  dynamic "client" {
    for_each = var.spec.client_permissions != null ? [var.spec.client_permissions] : []
    content {
      permissions {
        disabled_user_signup   = client.value.disabled_user_signup
        disabled_user_deletion = client.value.disabled_user_deletion
      }
    }
  }

  deletion_policy = var.spec.deletion_policy != "" ? var.spec.deletion_policy : null

  depends_on = [google_project_service.identitytoolkit_api]
}

# The composed tenant-scoped IdP configs. A disabled IdP is sent explicitly
# — coalesce defaults an unset `enabled` to true, the posture users expect
# when adding a provider.
resource "google_identity_platform_tenant_default_supported_idp_config" "this" {
  for_each = local.default_supported_idps

  project = local.project_id
  tenant  = google_identity_platform_tenant.this.name

  idp_id        = each.value.idp_id
  client_id     = each.value.client_id
  client_secret = each.value.client_secret
  enabled       = coalesce(each.value.enabled, true)

  deletion_policy = var.spec.deletion_policy != "" ? var.spec.deletion_policy : null
}

resource "google_identity_platform_tenant_oauth_idp_config" "this" {
  for_each = local.oauth_idp_configs

  project = local.project_id
  tenant  = google_identity_platform_tenant.this.name

  name          = each.value.name
  display_name  = each.value.display_name
  issuer        = each.value.issuer
  client_id     = each.value.client_id
  client_secret = each.value.client_secret != "" ? each.value.client_secret : null
  enabled       = coalesce(each.value.enabled, true)

  deletion_policy = var.spec.deletion_policy != "" ? var.spec.deletion_policy : null
}

resource "google_identity_platform_tenant_inbound_saml_config" "this" {
  for_each = local.inbound_saml_configs

  project = local.project_id
  tenant  = google_identity_platform_tenant.this.name

  name         = each.value.name
  display_name = each.value.display_name
  enabled      = coalesce(each.value.enabled, true)

  idp_config {
    idp_entity_id = each.value.idp_config.idp_entity_id
    sso_url       = each.value.idp_config.sso_url
    sign_request  = each.value.idp_config.sign_request

    dynamic "idp_certificates" {
      for_each = each.value.idp_config.idp_certificates
      content {
        x509_certificate = idp_certificates.value.x509_certificate != "" ? idp_certificates.value.x509_certificate : null
      }
    }
  }

  # Required at tenant level — the API's own rule, enforced by the spec's
  # CEL before the module ever runs.
  sp_config {
    callback_uri = each.value.sp_config.callback_uri
    sp_entity_id = each.value.sp_config.sp_entity_id
  }

  deletion_policy = var.spec.deletion_policy != "" ? var.spec.deletion_policy : null
}
