apiVersion: digital-ocean.planton.dev/v1alpha1
kind: DigitalOceanBucket
metadata:
  name: app-data
spec:
  bucketName: app-data
  region: nyc3
  accessControl: PRIVATE
  versioningEnabled: true
  lifecycleRules:
    - id: cleanup
      enabled: true
      abortIncompleteMultipartUploadDays: 7
      noncurrentVersionExpiration:
        days: 90
