// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azurebastionhost/v1alpha1/spec.proto

package azurebastionhostv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	_ "github.com/plantonhq/planton/shared/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Bastion host SKU. Upgrades are in-place; downgrades replace the
// host.
type AzureBastionHostSku int32

const (
	// Not specified -- deploys BASIC, the provider's default.
	AzureBastionHostSku_azure_bastion_host_sku_unspecified AzureBastionHostSku = 0
	// Shared Azure-hosted infrastructure: free, no dedicated subnet or
	// public IP, one connection per user, no feature knobs. Offered in a
	// limited set of regions. Dev/test only.
	AzureBastionHostSku_DEVELOPER AzureBastionHostSku = 1
	// Dedicated infrastructure at fixed capacity (2 scale units).
	// Browser sessions with copy/paste; no scaling or feature knobs.
	AzureBastionHostSku_BASIC AzureBastionHostSku = 2
	// Dedicated infrastructure with scaling (2-50 units) and the feature
	// set: file copy, native-client tunneling, IP connect, shareable
	// links, Kerberos.
	AzureBastionHostSku_STANDARD AzureBastionHostSku = 3
	// Everything in STANDARD plus session recording and private-only
	// deployment (omit ip_configuration's public IP).
	AzureBastionHostSku_PREMIUM AzureBastionHostSku = 4
)

// Enum value maps for AzureBastionHostSku.
var (
	AzureBastionHostSku_name = map[int32]string{
		0: "azure_bastion_host_sku_unspecified",
		1: "DEVELOPER",
		2: "BASIC",
		3: "STANDARD",
		4: "PREMIUM",
	}
	AzureBastionHostSku_value = map[string]int32{
		"azure_bastion_host_sku_unspecified": 0,
		"DEVELOPER":                          1,
		"BASIC":                              2,
		"STANDARD":                           3,
		"PREMIUM":                            4,
	}
)

func (x AzureBastionHostSku) Enum() *AzureBastionHostSku {
	p := new(AzureBastionHostSku)
	*p = x
	return p
}

func (x AzureBastionHostSku) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AzureBastionHostSku) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_enumTypes[0].Descriptor()
}

func (AzureBastionHostSku) Type() protoreflect.EnumType {
	return &file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_enumTypes[0]
}

func (x AzureBastionHostSku) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AzureBastionHostSku.Descriptor instead.
func (AzureBastionHostSku) EnumDescriptor() ([]byte, []int) {
	return file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

// **AzureBastionHostSpec** defines an Azure Bastion host -- the managed
// jump service that opens browser-based (and, on higher SKUs,
// native-client) RDP/SSH sessions to virtual machines over their
// PRIVATE addresses, so the machines themselves never expose a public
// IP or an inbound NSG rule.
//
// **Four SKUs, two deployment shapes**:
//   - **DEVELOPER**: Azure-hosted SHARED infrastructure -- free, no
//     dedicated subnet, no public IP; the host simply attaches to a
//     virtual network (virtual_network_id). One connection per user, no
//     feature knobs, offered in a limited set of regions. Dev/test only.
//   - **BASIC** (the default), **STANDARD**, and **PREMIUM**: dedicated
//     infrastructure deployed into the network's "AzureBastionSubnet"
//     with a Standard-SKU static public IP (ip_configuration). STANDARD
//     unlocks scaling (2-50 scale units) and the feature knobs (file
//     copy, native-client tunneling, IP connect, shareable links,
//     Kerberos); PREMIUM adds session recording and private-only
//     deployment (omit the public IP to keep the host off the internet
//     entirely).
//
// **The AzureBastionSubnet contract**: dedicated-infrastructure hosts
// deploy ONLY into a subnet whose ARM name is EXACTLY
// "AzureBastionSubnet", sized /26 or larger. ARM validates the name at
// deploy time (the subnet reference resolves after validation, so it
// cannot be checked here).
//
// **SKU changes**: upgrading (Basic -> Standard -> Premium) is
// in-place; DOWNGRADING replaces the host (the provider forces a new
// resource -- Azure has no downgrade path). Choose the long-term tier
// deliberately.
//
// The host bills hourly per SKU (plus per-scale-unit on
// Standard/Premium) from the moment it provisions; creates take ~10
// minutes.
type AzureBastionHostSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Azure region the host lives in, e.g. "eastus". Must match the
	// virtual network it serves. Changing the region replaces the host.
	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	// The Azure resource group the host is created in. Can be a literal
	// resource-group name or a reference to an AzureResourceGroup's name
	// output. Changing it replaces the host.
	ResourceGroup *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=resource_group,json=resourceGroup,proto3" json:"resource_group,omitempty"`
	// The host's name, unique within the resource group. 3-80
	// characters; starts with a letter or number, ends with a letter,
	// number, or underscore, and may contain letters, numbers,
	// underscores, periods, and hyphens. Changing the name replaces the
	// host.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The host's SKU -- picks the deployment shape, the feature set, and
	// the hourly cost. Unspecified deploys BASIC (dedicated
	// infrastructure at fixed capacity), the provider's own default.
	// Upgrades are in-place; a DOWNGRADE replaces the host.
	Sku AzureBastionHostSku `protobuf:"varint,4,opt,name=sku,proto3,enum=dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSku" json:"sku,omitempty"`
	// The dedicated-infrastructure binding: the "AzureBastionSubnet" the
	// host deploys into and the Standard static public IP sessions enter
	// through. REQUIRED (with its public IP) on BASIC and STANDARD;
	// optional public IP on PREMIUM (omit it for a private-only host);
	// not used by DEVELOPER (shared infrastructure -- set
	// virtual_network_id instead). FIXED AT CREATION -- any change
	// replaces the host.
	IpConfiguration *AzureBastionHostIpConfiguration `protobuf:"bytes,5,opt,name=ip_configuration,json=ipConfiguration,proto3" json:"ip_configuration,omitempty"`
	// DEVELOPER SKU only: the virtual network the shared-infrastructure
	// host attaches to -- references an AzureVirtualNetwork's ARM id. No
	// dedicated subnet or public IP is involved. Required on DEVELOPER;
	// forbidden on every other SKU. Fixed at creation.
	VirtualNetworkId *v1.StringValueOrRef `protobuf:"bytes,6,opt,name=virtual_network_id,json=virtualNetworkId,proto3" json:"virtual_network_id,omitempty"`
	// The host's capacity, 2-50 scale units (each unit carries ~20
	// concurrent sessions). Adjustable only on STANDARD and PREMIUM --
	// BASIC and DEVELOPER are fixed at 2. Unspecified applies 2, the
	// provider's default. Updatable in place.
	ScaleUnits *int32 `protobuf:"varint,7,opt,name=scale_units,json=scaleUnits,proto3,oneof" json:"scale_units,omitempty"`
	// Copy/paste between the local clipboard and the remote session.
	// Available on every SKU. Unspecified applies true, the provider's
	// default (set false to block clipboard exfiltration). Updatable in
	// place.
	CopyPasteEnabled *bool `protobuf:"varint,8,opt,name=copy_paste_enabled,json=copyPasteEnabled,proto3,oneof" json:"copy_paste_enabled,omitempty"`
	// File upload/download through the browser session. STANDARD or
	// PREMIUM only. Updatable in place.
	FileCopyEnabled bool `protobuf:"varint,9,opt,name=file_copy_enabled,json=fileCopyEnabled,proto3" json:"file_copy_enabled,omitempty"`
	// Connect to a VM by its private IP ADDRESS (instead of picking the
	// VM resource) -- reaches machines Bastion cannot enumerate, e.g.
	// across network peerings. STANDARD or PREMIUM only. Updatable in
	// place.
	IpConnectEnabled bool `protobuf:"varint,10,opt,name=ip_connect_enabled,json=ipConnectEnabled,proto3" json:"ip_connect_enabled,omitempty"`
	// Kerberos authentication for sessions (domain-joined VM sign-in
	// against a domain controller reachable from the Bastion subnet).
	// STANDARD or PREMIUM only. The provider applies this at CREATE only
	// -- changing it later is silently ignored (a provider gap): plan
	// Kerberos up front or replace the host to change it.
	KerberosEnabled bool `protobuf:"varint,11,opt,name=kerberos_enabled,json=kerberosEnabled,proto3" json:"kerberos_enabled,omitempty"`
	// Shareable links: time-boxed URLs that open a session to one
	// specific VM without the holder needing Azure RBAC on the host.
	// STANDARD or PREMIUM only. Updatable in place.
	ShareableLinkEnabled bool `protobuf:"varint,12,opt,name=shareable_link_enabled,json=shareableLinkEnabled,proto3" json:"shareable_link_enabled,omitempty"`
	// Native-client tunneling: az network bastion tunnel / ssh / rdp
	// from a local terminal instead of the browser. STANDARD or PREMIUM
	// only. Updatable in place.
	TunnelingEnabled bool `protobuf:"varint,13,opt,name=tunneling_enabled,json=tunnelingEnabled,proto3" json:"tunneling_enabled,omitempty"`
	// Record sessions for compliance/audit review. PREMIUM only.
	// Updatable in place.
	SessionRecordingEnabled bool `protobuf:"varint,14,opt,name=session_recording_enabled,json=sessionRecordingEnabled,proto3" json:"session_recording_enabled,omitempty"`
	// Availability zones the host's instances are pinned to (e.g.
	// ["1","2","3"] for zone redundancy where the region supports it).
	// Empty deploys regionally. FIXED AT CREATION -- any change replaces
	// the host.
	Zones []string `protobuf:"bytes,15,rep,name=zones,proto3" json:"zones,omitempty"`
	// Free-form tags applied to the host, merged over the
	// Planton-derived resource tags (organization, environment, resource
	// id); a user tag with the same key wins.
	Tags          map[string]string `protobuf:"bytes,16,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureBastionHostSpec) Reset() {
	*x = AzureBastionHostSpec{}
	mi := &file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureBastionHostSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureBastionHostSpec) ProtoMessage() {}

func (x *AzureBastionHostSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureBastionHostSpec.ProtoReflect.Descriptor instead.
func (*AzureBastionHostSpec) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AzureBastionHostSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AzureBastionHostSpec) GetResourceGroup() *v1.StringValueOrRef {
	if x != nil {
		return x.ResourceGroup
	}
	return nil
}

func (x *AzureBastionHostSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AzureBastionHostSpec) GetSku() AzureBastionHostSku {
	if x != nil {
		return x.Sku
	}
	return AzureBastionHostSku_azure_bastion_host_sku_unspecified
}

func (x *AzureBastionHostSpec) GetIpConfiguration() *AzureBastionHostIpConfiguration {
	if x != nil {
		return x.IpConfiguration
	}
	return nil
}

func (x *AzureBastionHostSpec) GetVirtualNetworkId() *v1.StringValueOrRef {
	if x != nil {
		return x.VirtualNetworkId
	}
	return nil
}

func (x *AzureBastionHostSpec) GetScaleUnits() int32 {
	if x != nil && x.ScaleUnits != nil {
		return *x.ScaleUnits
	}
	return 0
}

func (x *AzureBastionHostSpec) GetCopyPasteEnabled() bool {
	if x != nil && x.CopyPasteEnabled != nil {
		return *x.CopyPasteEnabled
	}
	return false
}

func (x *AzureBastionHostSpec) GetFileCopyEnabled() bool {
	if x != nil {
		return x.FileCopyEnabled
	}
	return false
}

func (x *AzureBastionHostSpec) GetIpConnectEnabled() bool {
	if x != nil {
		return x.IpConnectEnabled
	}
	return false
}

func (x *AzureBastionHostSpec) GetKerberosEnabled() bool {
	if x != nil {
		return x.KerberosEnabled
	}
	return false
}

func (x *AzureBastionHostSpec) GetShareableLinkEnabled() bool {
	if x != nil {
		return x.ShareableLinkEnabled
	}
	return false
}

func (x *AzureBastionHostSpec) GetTunnelingEnabled() bool {
	if x != nil {
		return x.TunnelingEnabled
	}
	return false
}

func (x *AzureBastionHostSpec) GetSessionRecordingEnabled() bool {
	if x != nil {
		return x.SessionRecordingEnabled
	}
	return false
}

func (x *AzureBastionHostSpec) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *AzureBastionHostSpec) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// The dedicated-infrastructure binding: subnet plus (usually) a public
// IP. Every field is FIXED AT CREATION.
type AzureBastionHostIpConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The configuration's name (e.g. "bastion-ip-config"), unique on the
	// host. Same character rules as the host name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The subnet the host deploys into -- references an AzureSubnet's
	// ARM id. ARM requires the subnet's name to be EXACTLY
	// "AzureBastionSubnet" and its prefix /26 or larger; the subnet
	// carries nothing but the Bastion host. (The name lives on the
	// referenced subnet, so it is validated at deploy time, not here.)
	SubnetId *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	// The public IP sessions enter through -- references an
	// AzurePublicIp's ARM id (Standard SKU, static allocation; the host
	// binds it exclusively). REQUIRED on BASIC and STANDARD. On PREMIUM,
	// omit it to deploy the host PRIVATE-ONLY (reachable only from
	// connected networks; surfaced in the private_only_enabled output).
	PublicIpAddressId *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=public_ip_address_id,json=publicIpAddressId,proto3" json:"public_ip_address_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AzureBastionHostIpConfiguration) Reset() {
	*x = AzureBastionHostIpConfiguration{}
	mi := &file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureBastionHostIpConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureBastionHostIpConfiguration) ProtoMessage() {}

func (x *AzureBastionHostIpConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureBastionHostIpConfiguration.ProtoReflect.Descriptor instead.
func (*AzureBastionHostIpConfiguration) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *AzureBastionHostIpConfiguration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AzureBastionHostIpConfiguration) GetSubnetId() *v1.StringValueOrRef {
	if x != nil {
		return x.SubnetId
	}
	return nil
}

func (x *AzureBastionHostIpConfiguration) GetPublicIpAddressId() *v1.StringValueOrRef {
	if x != nil {
		return x.PublicIpAddressId
	}
	return nil
}

var File_catalog_azure_azurebastionhost_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"2catalog/azure/azurebastionhost/v1alpha1/spec.proto\x12+dev.planton.azure.azurebastionhost.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\x1a\x1cshared/options/options.proto\"\x8f\x1a\n" +
	"\x14AzureBastionHostSpec\x12\"\n" +
	"\x06region\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06region\x12\x8c\x01\n" +
	"\x0eresource_group\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB1\xbaH\x03\xc8\x01\x01\x88\xd4a\xd0\x0f\x92\xd4a\"status.outputs.resource_group_nameR\rresourceGroup\x12\xb2\x02\n" +
	"\x04name\x18\x03 \x01(\tB\x9d\x02\xbaH\x99\x02\xba\x01\x8e\x02\n" +
	"\x13bastion_name_format\x12\xae\x01Bastion host names start with a letter or number, end with a letter, number, or underscore, and may contain alphanumerics, underscores, periods, and hyphens (3-80 characters)\x1aFthis == '' || this.matches('^[A-Za-z0-9][a-zA-Z0-9_.-]+[a-zA-Z0-9_]$')\xc8\x01\x01r\x02\x18PR\x04name\x12\\\n" +
	"\x03sku\x18\x04 \x01(\x0e2@.dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSkuB\b\xbaH\x05\x82\x01\x02\x10\x01R\x03sku\x12w\n" +
	"\x10ip_configuration\x18\x05 \x01(\v2L.dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostIpConfigurationR\x0fipConfiguration\x12\x8c\x01\n" +
	"\x12virtual_network_id\x18\x06 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB*\x88\xd4a\xd6\x0f\x92\xd4a!status.outputs.virtual_network_idR\x10virtualNetworkId\x124\n" +
	"\vscale_units\x18\a \x01(\x05B\x0e\xbaH\x06\x1a\x04\x182(\x02\x8a\xa6\x1d\x012H\x00R\n" +
	"scaleUnits\x88\x01\x01\x12;\n" +
	"\x12copy_paste_enabled\x18\b \x01(\bB\b\x8a\xa6\x1d\x04trueH\x01R\x10copyPasteEnabled\x88\x01\x01\x12*\n" +
	"\x11file_copy_enabled\x18\t \x01(\bR\x0ffileCopyEnabled\x12,\n" +
	"\x12ip_connect_enabled\x18\n" +
	" \x01(\bR\x10ipConnectEnabled\x12)\n" +
	"\x10kerberos_enabled\x18\v \x01(\bR\x0fkerberosEnabled\x124\n" +
	"\x16shareable_link_enabled\x18\f \x01(\bR\x14shareableLinkEnabled\x12+\n" +
	"\x11tunneling_enabled\x18\r \x01(\bR\x10tunnelingEnabled\x12:\n" +
	"\x19session_recording_enabled\x18\x0e \x01(\bR\x17sessionRecordingEnabled\x12\"\n" +
	"\x05zones\x18\x0f \x03(\tB\f\xbaH\t\x92\x01\x06\"\x04r\x02\x10\x01R\x05zones\x12_\n" +
	"\x04tags\x18\x10 \x03(\v2K.dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\xac\x0e\xbaH\xa8\x0e\x1a\xb3\x02\n" +
	"'basic_standard_require_ip_configuration\x12\x9a\x01BASIC and STANDARD hosts deploy dedicated infrastructure: set ip_configuration with its subnet (named exactly AzureBastionSubnet) AND public_ip_address_id\x1ak!(this.sku in [0, 2, 3]) || (has(this.ip_configuration) && has(this.ip_configuration.public_ip_address_id))\x1a\xbd\x01\n" +
	"\"developer_requires_virtual_network\x12hDEVELOPER hosts attach to a virtual network: set virtual_network_id (no subnet or public IP is involved)\x1a-this.sku != 1 || has(this.virtual_network_id)\x1a\xe1\x01\n" +
	"!virtual_network_is_developer_only\x12\x8b\x01virtual_network_id applies only to the DEVELOPER SKU -- dedicated-infrastructure hosts bind their network through ip_configuration's subnet\x1a.this.sku == 1 || !has(this.virtual_network_id)\x1a\xd5\x01\n" +
	"'scale_units_require_standard_or_premium\x12ascale_units is adjustable only on STANDARD or PREMIUM -- BASIC and DEVELOPER hosts are fixed at 2\x1aG!(has(this.scale_units) && this.scale_units != 2) || this.sku in [3, 4]\x1a\x8f\x01\n" +
	"&file_copy_requires_standard_or_premium\x126file_copy_enabled requires the STANDARD or PREMIUM SKU\x1a-!this.file_copy_enabled || this.sku in [3, 4]\x1a\x92\x01\n" +
	"'ip_connect_requires_standard_or_premium\x127ip_connect_enabled requires the STANDARD or PREMIUM SKU\x1a.!this.ip_connect_enabled || this.sku in [3, 4]\x1a\x8c\x01\n" +
	"%kerberos_requires_standard_or_premium\x125kerberos_enabled requires the STANDARD or PREMIUM SKU\x1a,!this.kerberos_enabled || this.sku in [3, 4]\x1a\x9e\x01\n" +
	"+shareable_link_requires_standard_or_premium\x12;shareable_link_enabled requires the STANDARD or PREMIUM SKU\x1a2!this.shareable_link_enabled || this.sku in [3, 4]\x1a\x8f\x01\n" +
	"&tunneling_requires_standard_or_premium\x126tunneling_enabled requires the STANDARD or PREMIUM SKU\x1a-!this.tunneling_enabled || this.sku in [3, 4]\x1a\x8a\x01\n" +
	"\"session_recording_requires_premium\x122session_recording_enabled requires the PREMIUM SKU\x1a0!this.session_recording_enabled || this.sku == 4B\x0e\n" +
	"\f_scale_unitsB\x15\n" +
	"\x13_copy_paste_enabled\"\xea\x04\n" +
	"\x1fAzureBastionHostIpConfiguration\x12\xc0\x02\n" +
	"\x04name\x18\x01 \x01(\tB\xab\x02\xbaH\xa7\x02\xba\x01\x9c\x02\n" +
	"\x1dbastion_ip_config_name_format\x12\xb2\x01IP configuration names start with a letter or number, end with a letter, number, or underscore, and may contain alphanumerics, underscores, periods, and hyphens (3-80 characters)\x1aFthis == '' || this.matches('^[A-Za-z0-9][a-zA-Z0-9_.-]+[a-zA-Z0-9_]$')\xc8\x01\x01r\x02\x18PR\x04name\x12x\n" +
	"\tsubnet_id\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB'\xbaH\x03\xc8\x01\x01\x88\xd4a\xdb\x0f\x92\xd4a\x18status.outputs.subnet_idR\bsubnetId\x12\x89\x01\n" +
	"\x14public_ip_address_id\x18\x03 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB$\x88\xd4a\xdd\x0f\x92\xd4a\x1bstatus.outputs.public_ip_idR\x11publicIpAddressId*r\n" +
	"\x13AzureBastionHostSku\x12&\n" +
	"\"azure_bastion_host_sku_unspecified\x10\x00\x12\r\n" +
	"\tDEVELOPER\x10\x01\x12\t\n" +
	"\x05BASIC\x10\x02\x12\f\n" +
	"\bSTANDARD\x10\x03\x12\v\n" +
	"\aPREMIUM\x10\x04B\xec\x02\n" +
	"/com.dev.planton.azure.azurebastionhost.v1alpha1B\tSpecProtoP\x01Z]github.com/plantonhq/planton/catalog/azure/azurebastionhost/v1alpha1;azurebastionhostv1alpha1\xa2\x02\x04DPAA\xaa\x02+Dev.Planton.Azure.Azurebastionhost.V1alpha1\xca\x02+Dev\\Planton\\Azure\\Azurebastionhost\\V1alpha1\xe2\x027Dev\\Planton\\Azure\\Azurebastionhost\\V1alpha1\\GPBMetadata\xea\x02/Dev::Planton::Azure::Azurebastionhost::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDesc), len(file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDescData
}

var file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_goTypes = []any{
	(AzureBastionHostSku)(0),                // 0: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSku
	(*AzureBastionHostSpec)(nil),            // 1: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec
	(*AzureBastionHostIpConfiguration)(nil), // 2: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostIpConfiguration
	nil,                                     // 3: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.TagsEntry
	(*v1.StringValueOrRef)(nil),             // 4: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_depIdxs = []int32{
	4, // 0: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.resource_group:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	0, // 1: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.sku:type_name -> dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSku
	2, // 2: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.ip_configuration:type_name -> dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostIpConfiguration
	4, // 3: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.virtual_network_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	3, // 4: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.tags:type_name -> dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostSpec.TagsEntry
	4, // 5: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostIpConfiguration.subnet_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	4, // 6: dev.planton.azure.azurebastionhost.v1alpha1.AzureBastionHostIpConfiguration.public_ip_address_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_init() }
func file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_init() {
	if File_catalog_azure_azurebastionhost_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDesc), len(file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_depIdxs,
		EnumInfos:         file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_enumTypes,
		MessageInfos:      file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_azure_azurebastionhost_v1alpha1_spec_proto = out.File
	file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_goTypes = nil
	file_catalog_azure_azurebastionhost_v1alpha1_spec_proto_depIdxs = nil
}
