apiVersion: aws.planton.dev/v1alpha1
kind: AwsRestApiDomain
metadata:
  name: my-api-domain
spec:
  region: <aws-region>
  domainName: api.example.com
  certificateArn:
    valueFrom:
      kind: AwsCertManagerCert
      name: <acm-certificate>
      fieldPath: status.outputs.certificate_arn
  endpointConfiguration:
    type: REGIONAL
  basePathMappings:
    - restApiId:
        valueFrom:
          kind: AwsRestApiGateway
          name: <rest-api>
          fieldPath: status.outputs.rest_api_id
      stageName:
        value: prod
