load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "protoc-gen-catalog-schema_lib",
    srcs = ["main.go"],
    importpath = "github.com/plantonhq/planton/pkg/catalogschema/protoc-gen-catalog-schema",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/catalogschema",
        "@org_golang_google_protobuf//compiler/protogen",
        "@org_golang_google_protobuf//types/pluginpb",
    ],
)

go_binary(
    name = "protoc-gen-catalog-schema",
    embed = [":protoc-gen-catalog-schema_lib"],
    visibility = ["//visibility:public"],
)
