// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/kubernetes/kubernetesdaemonset/v1alpha1/stack_outputs.proto

package kubernetesdaemonsetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// **KubernetesDaemonSetStackOutputs** captures the observable handles of a deployed
// node agent. DaemonSets have no Service or ingress, so the composition surface is
// the object identity and its selector labels.
type KubernetesDaemonSetStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The namespace the workload was deployed into.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The name of the DaemonSet object as created in the cluster.
	DaemonSetName string `protobuf:"bytes,2,opt,name=daemon_set_name,json=daemonSetName,proto3" json:"daemon_set_name,omitempty"`
	// *
	// The pod selector labels as a "k=v,k=v" string — the exact labels the DaemonSet
	// selects on, ready for NetworkPolicy podSelectors, `kubectl get pods -l`, and
	// pod-affinity terms in sibling workloads.
	SelectorLabels string `protobuf:"bytes,3,opt,name=selector_labels,json=selectorLabels,proto3" json:"selector_labels,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KubernetesDaemonSetStackOutputs) Reset() {
	*x = KubernetesDaemonSetStackOutputs{}
	mi := &file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesDaemonSetStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesDaemonSetStackOutputs) ProtoMessage() {}

func (x *KubernetesDaemonSetStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesDaemonSetStackOutputs.ProtoReflect.Descriptor instead.
func (*KubernetesDaemonSetStackOutputs) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesDaemonSetStackOutputs) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesDaemonSetStackOutputs) GetDaemonSetName() string {
	if x != nil {
		return x.DaemonSetName
	}
	return ""
}

func (x *KubernetesDaemonSetStackOutputs) GetSelectorLabels() string {
	if x != nil {
		return x.SelectorLabels
	}
	return ""
}

var File_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto protoreflect.FileDescriptor

const file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"Pdev/planton/provider/kubernetes/kubernetesdaemonset/v1alpha1/stack_outputs.proto\x12<dev.planton.provider.kubernetes.kubernetesdaemonset.v1alpha1\"\x90\x01\n" +
	"\x1fKubernetesDaemonSetStackOutputs\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12&\n" +
	"\x0fdaemon_set_name\x18\x02 \x01(\tR\rdaemonSetName\x12'\n" +
	"\x0fselector_labels\x18\x03 \x01(\tR\x0eselectorLabelsB\xe8\x03\n" +
	"@com.dev.planton.provider.kubernetes.kubernetesdaemonset.v1alpha1B\x11StackOutputsProtoP\x01Zzgithub.com/plantonhq/planton/apis/dev/planton/provider/kubernetes/kubernetesdaemonset/v1alpha1;kubernetesdaemonsetv1alpha1\xa2\x02\x05DPPKK\xaa\x02<Dev.Planton.Provider.Kubernetes.Kubernetesdaemonset.V1alpha1\xca\x02<Dev\\Planton\\Provider\\Kubernetes\\Kubernetesdaemonset\\V1alpha1\xe2\x02HDev\\Planton\\Provider\\Kubernetes\\Kubernetesdaemonset\\V1alpha1\\GPBMetadata\xea\x02ADev::Planton::Provider::Kubernetes::Kubernetesdaemonset::V1alpha1b\x06proto3"

var (
	file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDescOnce sync.Once
	file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDescData []byte
)

func file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDesc)))
	})
	return file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDescData
}

var file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_goTypes = []any{
	(*KubernetesDaemonSetStackOutputs)(nil), // 0: dev.planton.provider.kubernetes.kubernetesdaemonset.v1alpha1.KubernetesDaemonSetStackOutputs
}
var file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_init()
}
func file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_init() {
	if File_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDesc), len(file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto = out.File
	file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_goTypes = nil
	file_dev_planton_provider_kubernetes_kubernetesdaemonset_v1alpha1_stack_outputs_proto_depIdxs = nil
}
