apiVersion: aws.planton.dev/v1alpha1
kind: AwsNlb
metadata:
  name: <nlb-name>
spec:
  region: <aws-region>
  internal: true
  subnetMappings:
    - subnetId:
        value: <private-subnet-id-az1>
    - subnetId:
        value: <private-subnet-id-az2>
  securityGroups:
    - valueFrom:
        kind: AwsSecurityGroup
        name: <nlb-security-group-resource-name>
        fieldPath: status.outputs.security_group_id
  enforceSecurityGroupInboundRulesOnPrivateLinkTraffic: "on"
  deleteProtectionEnabled: true
  accessLogs:
    bucket:
      value: <access-logs-bucket-name>
    prefix: <log-prefix>
