apiVersion: kubernetes.planton.dev/v1alpha1
kind: KubernetesService
metadata:
  name: e2e-svc-extname
spec:
  namespace:
    value: default
  name: e2e-svc-extname
  type: external_name
  external_dns_name: "api.example.com"
