syntax = "proto3";

package dev.planton.alicloud.alicloudrampolicy.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/alicloud/alicloudrampolicy/v1alpha1/outputs.proto";
import "catalog/alicloud/alicloudrampolicy/v1alpha1/spec.proto";
import "shared/metadata.proto";

// alicloud-ram-policy
message AliCloudRamPolicy {
  // api-version
  string api_version = 1 [(buf.validate.field).string.const = 'alicloud.planton.dev/v1alpha1'];

  // resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AliCloudRamPolicy'];

  // metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  // spec
  AliCloudRamPolicySpec spec = 4 [(buf.validate.field).required = true];

  // status
  AliCloudRamPolicyStatus status = 5;
}

// alicloud-ram-policy status
message AliCloudRamPolicyStatus {
  // stack-outputs
  AliCloudRamPolicyStackOutputs outputs = 1;
}
