// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/gcp/gcpprojectiammember/v1/stack_outputs.proto

package gcpprojectiammemberv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outputs produced after applying a project-level IAM member grant.
// The grant itself has no server-generated identity beyond its inputs; the
// outputs echo the fully-resolved grant tuple so downstream tooling and audits
// can see exactly what was applied without re-resolving references.
type GcpProjectIamMemberStackOutputs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The project ID whose IAM policy received the grant (after reference
	// resolution and any provider-default fallback).
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The role that was granted (predefined name or fully-qualified custom
	// role name), after reference resolution.
	Role string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// The member the role was granted to, in IAM member format, after
	// reference resolution.
	Member string `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	// The etag of the project IAM policy after this grant was applied — a
	// fingerprint of the policy version, useful for audit correlation.
	Etag          string `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpProjectIamMemberStackOutputs) Reset() {
	*x = GcpProjectIamMemberStackOutputs{}
	mi := &file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpProjectIamMemberStackOutputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpProjectIamMemberStackOutputs) ProtoMessage() {}

func (x *GcpProjectIamMemberStackOutputs) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpProjectIamMemberStackOutputs.ProtoReflect.Descriptor instead.
func (*GcpProjectIamMemberStackOutputs) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDescGZIP(), []int{0}
}

func (x *GcpProjectIamMemberStackOutputs) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GcpProjectIamMemberStackOutputs) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *GcpProjectIamMemberStackOutputs) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *GcpProjectIamMemberStackOutputs) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

var File_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto protoreflect.FileDescriptor

const file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDesc = "" +
	"\n" +
	"Cdev/planton/provider/gcp/gcpprojectiammember/v1/stack_outputs.proto\x12/dev.planton.provider.gcp.gcpprojectiammember.v1\"\x80\x01\n" +
	"\x1fGcpProjectIamMemberStackOutputs\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x16\n" +
	"\x06member\x18\x03 \x01(\tR\x06member\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etagB\x94\x03\n" +
	"3com.dev.planton.provider.gcp.gcpprojectiammember.v1B\x11StackOutputsProtoP\x01Zggithub.com/plantonhq/planton/apis/dev/planton/provider/gcp/gcpprojectiammember/v1;gcpprojectiammemberv1\xa2\x02\x05DPPGG\xaa\x02/Dev.Planton.Provider.Gcp.Gcpprojectiammember.V1\xca\x02/Dev\\Planton\\Provider\\Gcp\\Gcpprojectiammember\\V1\xe2\x02;Dev\\Planton\\Provider\\Gcp\\Gcpprojectiammember\\V1\\GPBMetadata\xea\x024Dev::Planton::Provider::Gcp::Gcpprojectiammember::V1b\x06proto3"

var (
	file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDescOnce sync.Once
	file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDescData []byte
)

func file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDesc), len(file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDesc)))
	})
	return file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDescData
}

var file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_goTypes = []any{
	(*GcpProjectIamMemberStackOutputs)(nil), // 0: dev.planton.provider.gcp.gcpprojectiammember.v1.GcpProjectIamMemberStackOutputs
}
var file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_init() }
func file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_init() {
	if File_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDesc), len(file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto = out.File
	file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_goTypes = nil
	file_dev_planton_provider_gcp_gcpprojectiammember_v1_stack_outputs_proto_depIdxs = nil
}
