// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/digitalocean/digitaloceancertificate/v1alpha1/api.proto

package digitaloceancertificatev1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/apis/dev/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// digital-ocean-certificate
type DigitalOceanCertificate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *DigitalOceanCertificateSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *DigitalOceanCertificateStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalOceanCertificate) Reset() {
	*x = DigitalOceanCertificate{}
	mi := &file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalOceanCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalOceanCertificate) ProtoMessage() {}

func (x *DigitalOceanCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalOceanCertificate.ProtoReflect.Descriptor instead.
func (*DigitalOceanCertificate) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *DigitalOceanCertificate) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *DigitalOceanCertificate) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DigitalOceanCertificate) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DigitalOceanCertificate) GetSpec() *DigitalOceanCertificateSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DigitalOceanCertificate) GetStatus() *DigitalOceanCertificateStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// digital-ocean-certificate status
type DigitalOceanCertificateStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	//
	//	digital-ocean-certificate stack-outputs
	Outputs       *DigitalOceanCertificateStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalOceanCertificateStatus) Reset() {
	*x = DigitalOceanCertificateStatus{}
	mi := &file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalOceanCertificateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalOceanCertificateStatus) ProtoMessage() {}

func (x *DigitalOceanCertificateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalOceanCertificateStatus.ProtoReflect.Descriptor instead.
func (*DigitalOceanCertificateStatus) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *DigitalOceanCertificateStatus) GetOutputs() *DigitalOceanCertificateStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto protoreflect.FileDescriptor

const file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"Ldev/planton/provider/digitalocean/digitaloceancertificate/v1alpha1/api.proto\x12Bdev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1aMdev/planton/provider/digitalocean/digitaloceancertificate/v1alpha1/spec.proto\x1aVdev/planton/provider/digitalocean/digitaloceancertificate/v1alpha1/stack_outputs.proto\x1a!dev/planton/shared/metadata.proto\"\xe0\x03\n" +
	"\x17DigitalOceanCertificate\x12J\n" +
	"\vapi_version\x18\x01 \x01(\tB)\xbaH&r$\n" +
	"\"digital-ocean.planton.dev/v1alpha1R\n" +
	"apiVersion\x122\n" +
	"\x04kind\x18\x02 \x01(\tB\x1e\xbaH\x1br\x19\n" +
	"\x17DigitalOceanCertificateR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12{\n" +
	"\x04spec\x18\x04 \x01(\v2_.dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12y\n" +
	"\x06status\x18\x05 \x01(\v2a.dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateStatusR\x06status\"\xa3\x01\n" +
	"\x1dDigitalOceanCertificateStatus\x12\x81\x01\n" +
	"\aoutputs\x18\x01 \x01(\v2g.dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateStackOutputsR\aoutputsB\x88\x04\n" +
	"Fcom.dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1B\bApiProtoP\x01Z\x84\x01github.com/plantonhq/planton/apis/dev/planton/provider/digitalocean/digitaloceancertificate/v1alpha1;digitaloceancertificatev1alpha1\xa2\x02\x05DPPDD\xaa\x02BDev.Planton.Provider.Digitalocean.Digitaloceancertificate.V1alpha1\xca\x02BDev\\Planton\\Provider\\Digitalocean\\Digitaloceancertificate\\V1alpha1\xe2\x02NDev\\Planton\\Provider\\Digitalocean\\Digitaloceancertificate\\V1alpha1\\GPBMetadata\xea\x02GDev::Planton::Provider::Digitalocean::Digitaloceancertificate::V1alpha1b\x06proto3"

var (
	file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescOnce sync.Once
	file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescData []byte
)

func file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDesc), len(file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDesc)))
	})
	return file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDescData
}

var file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_goTypes = []any{
	(*DigitalOceanCertificate)(nil),             // 0: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificate
	(*DigitalOceanCertificateStatus)(nil),       // 1: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateStatus
	(*shared.CloudResourceMetadata)(nil),        // 2: dev.planton.shared.CloudResourceMetadata
	(*DigitalOceanCertificateSpec)(nil),         // 3: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateSpec
	(*DigitalOceanCertificateStackOutputs)(nil), // 4: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateStackOutputs
}
var file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificate.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificate.spec:type_name -> dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateSpec
	1, // 2: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificate.status:type_name -> dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateStatus
	4, // 3: dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateStatus.outputs:type_name -> dev.planton.provider.digitalocean.digitaloceancertificate.v1alpha1.DigitalOceanCertificateStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_init() }
func file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_init() {
	if File_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto != nil {
		return
	}
	file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_spec_proto_init()
	file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_stack_outputs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDesc), len(file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto = out.File
	file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_goTypes = nil
	file_dev_planton_provider_digitalocean_digitaloceancertificate_v1alpha1_api_proto_depIdxs = nil
}
