apiVersion: aws.planton.dev/v1
kind: AwsNlb
metadata:
  name: <nlb-name>
spec:
  region: <aws-region>
  subnetMappings:
    - subnetId:
        value: <public-subnet-id-az1>
      allocationId:
        valueFrom:
          kind: AwsElasticIp
          name: <elastic-ip-resource-name-az1>
          fieldPath: status.outputs.allocation_id
    - subnetId:
        value: <public-subnet-id-az2>
      allocationId:
        valueFrom:
          kind: AwsElasticIp
          name: <elastic-ip-resource-name-az2>
          fieldPath: status.outputs.allocation_id
  deleteProtectionEnabled: true
