package module

const (
	OpStorageAccountId              = "storage_account_id"
	OpStorageAccountName            = "storage_account_name"
	OpResourceGroupName             = "resource_group_name"
	OpPrimaryBlobEndpoint           = "primary_blob_endpoint"
	OpPrimaryBlobHost               = "primary_blob_host"
	OpPrimaryQueueEndpoint          = "primary_queue_endpoint"
	OpPrimaryTableEndpoint          = "primary_table_endpoint"
	OpPrimaryFileEndpoint           = "primary_file_endpoint"
	OpPrimaryDfsEndpoint            = "primary_dfs_endpoint"
	OpPrimaryWebEndpoint            = "primary_web_endpoint"
	OpPrimaryWebHost                = "primary_web_host"
	OpSecondaryBlobEndpoint         = "secondary_blob_endpoint"
	OpSecondaryQueueEndpoint        = "secondary_queue_endpoint"
	OpSecondaryTableEndpoint        = "secondary_table_endpoint"
	OpSecondaryFileEndpoint         = "secondary_file_endpoint"
	OpSecondaryDfsEndpoint          = "secondary_dfs_endpoint"
	OpSecondaryWebEndpoint          = "secondary_web_endpoint"
	OpPrimaryAccessKey              = "primary_access_key"
	OpSecondaryAccessKey            = "secondary_access_key"
	OpPrimaryConnectionString       = "primary_connection_string"
	OpSecondaryConnectionString     = "secondary_connection_string"
	OpPrimaryBlobConnectionString   = "primary_blob_connection_string"
	OpSecondaryBlobConnectionString = "secondary_blob_connection_string"
	OpIdentityPrincipalId           = "identity_principal_id"
	OpBlobServiceId                 = "blob_service_id"
	OpFileServiceId                 = "file_service_id"
	OpQueueServiceId                = "queue_service_id"
	OpTableServiceId                = "table_service_id"
)
