variable "metadata" {
  description = "Cloud resource metadata"
  type = object({
    name = string
    id = optional(string, "")
    org = optional(string, "")
    env = optional(string, "")
    labels = optional(map(string), {})
    annotations = optional(map(string), {})
    tags = optional(list(string), [])
  })
}

variable "spec" {
  description = "AwsRdsInstance specification"
  type = object({
    region = string
    subnet_ids = optional(list(string), [])
    db_subnet_group_name = optional(string, "")
    security_group_ids = optional(list(string), [])
    engine = optional(string, "")
    engine_version = optional(string, "")
    instance_class = string
    allocated_storage_gb = optional(number, 0)
    max_allocated_storage_gb = optional(number, 0)
    storage_type = optional(string, "")
    iops = optional(number, 0)
    storage_throughput = optional(number, 0)
    dedicated_log_volume = optional(bool, false)
    storage_encrypted = optional(bool, false)
    kms_key_id = optional(string, "")
    db_name = optional(string, "")
    username = optional(string, "")
    manage_master_user_password = optional(bool, false)
    master_user_secret_kms_key_id = optional(string, "")
    password = optional(string, "")
    port = optional(number, 0)
    multi_az = optional(bool, false)
    availability_zone = optional(string, "")
    publicly_accessible = optional(bool, false)
    network_type = optional(string, "")
    replicate_source_db = optional(string, "")
    replica_mode = optional(string, "")
    snapshot_identifier = optional(string, "")
    restore_to_point_in_time = optional(object({
      source_db_instance_identifier = optional(string, "")
      source_dbi_resource_id = optional(string, "")
      source_db_instance_automated_backups_arn = optional(string, "")
      restore_time = optional(string, "")
      use_latest_restorable_time = optional(bool, false)
    }))
    backup_retention_period = optional(number, 0)
    backup_window = optional(string, "")
    maintenance_window = optional(string, "")
    copy_tags_to_snapshot = optional(bool, false)
    delete_automated_backups = optional(bool)
    skip_final_snapshot = optional(bool, false)
    final_snapshot_identifier = optional(string, "")
    deletion_protection = optional(bool, false)
    iam_database_authentication_enabled = optional(bool, false)
    enabled_cloudwatch_logs_exports = optional(list(string), [])
    performance_insights_enabled = optional(bool, false)
    performance_insights_kms_key_id = optional(string, "")
    performance_insights_retention_period = optional(number, 0)
    monitoring_interval = optional(number, 0)
    monitoring_role_arn = optional(string, "")
    database_insights_mode = optional(string, "")
    parameter_group_name = optional(string, "")
    option_group_name = optional(string, "")
    active_directory = optional(object({
      domain = optional(string, "")
      domain_iam_role_name = optional(string, "")
      domain_fqdn = optional(string, "")
      domain_ou = optional(string, "")
      domain_auth_secret_arn = optional(string, "")
      domain_dns_ips = optional(list(string), [])
    }))
    license_model = optional(string, "")
    character_set_name = optional(string, "")
    nchar_character_set_name = optional(string, "")
    timezone = optional(string, "")
    ca_cert_identifier = optional(string, "")
    blue_green_update_enabled = optional(bool, false)
    auto_minor_version_upgrade = optional(bool)
    allow_major_version_upgrade = optional(bool, false)
    apply_immediately = optional(bool, false)
  })
}
