// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dev/planton/provider/azure/azureservicebusdisasterrecoveryconfig/v1/spec.proto

package azureservicebusdisasterrecoveryconfigv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/apis/dev/planton/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// **AzureServiceBusDisasterRecoveryConfigSpec** defines a geo-disaster-
// recovery pairing between two PREMIUM Service Bus namespaces: metadata
// (queues, topics, subscriptions, rules, SAS rules -- not message data)
// continuously replicates from the primary to the partner, and a
// failover-stable ALIAS DNS name fronts whichever namespace is currently
// primary.
//
// Clients connect through the alias (`{alias_name}.servicebus.windows.net`)
// instead of either namespace, so a failover needs no client
// reconfiguration. The alias's connection strings come from the paired
// authorization rule -- see alias_authorization_rule_id and the
// `*_connection_string_alias` outputs on AzureServiceBusAuthorizationRule.
//
// **Azure's pairing contracts** (apply-time -- they involve both live
// namespaces): both namespaces must be PREMIUM, in DIFFERENT regions, and
// the partner must be empty (no entities) when pairing is created.
// Changing partner_namespace_id breaks the existing pairing and re-pairs.
//
// **Failover is an operational action, not a config change**: triggered
// from the SECONDARY side (portal/CLI/SDK) during a regional incident.
// Deleting this resource breaks the pairing gracefully (both namespaces
// keep running independently; the alias name is released after deletion).
//
// **ForceNew fields**: `alias_name`, `primary_namespace_id`.
type AzureServiceBusDisasterRecoveryConfigSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The alias name -- becomes the failover-stable DNS name
	// `{alias_name}.servicebus.windows.net`, so it shares the namespace
	// name rules and uniqueness scope (globally unique; it cannot collide
	// with any existing namespace name either).
	//
	// **ForceNew**: changing the alias replaces the pairing.
	AliasName string `protobuf:"bytes,1,opt,name=alias_name,json=aliasName,proto3" json:"alias_name,omitempty"`
	// The PRIMARY namespace -- the one clients actively use, by ARM ID.
	// References an AzureServiceBusNamespace's namespace_id output. Must be
	// PREMIUM. Fixed at creation.
	PrimaryNamespaceId *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=primary_namespace_id,json=primaryNamespaceId,proto3" json:"primary_namespace_id,omitempty"`
	// The PARTNER (secondary) namespace metadata replicates to, by ARM ID.
	// Must be PREMIUM, in a DIFFERENT region than the primary, and empty
	// (no queues/topics) at pairing time. Changing it breaks the current
	// pairing and re-pairs to the new partner.
	PartnerNamespaceId *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=partner_namespace_id,json=partnerNamespaceId,proto3" json:"partner_namespace_id,omitempty"`
	// The authorization rule whose keys the alias connection strings carry,
	// by ARM ID. References an AzureServiceBusAuthorizationRule's
	// authorization_rule_id output (a NAMESPACE-scoped rule on the
	// primary). Unset defaults to the namespace's built-in root rule
	// (RootManageSharedAccessKey) -- prefer a scoped rule for
	// least-privilege alias credentials.
	AliasAuthorizationRuleId *v1.StringValueOrRef `protobuf:"bytes,4,opt,name=alias_authorization_rule_id,json=aliasAuthorizationRuleId,proto3" json:"alias_authorization_rule_id,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AzureServiceBusDisasterRecoveryConfigSpec) Reset() {
	*x = AzureServiceBusDisasterRecoveryConfigSpec{}
	mi := &file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureServiceBusDisasterRecoveryConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureServiceBusDisasterRecoveryConfigSpec) ProtoMessage() {}

func (x *AzureServiceBusDisasterRecoveryConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureServiceBusDisasterRecoveryConfigSpec.ProtoReflect.Descriptor instead.
func (*AzureServiceBusDisasterRecoveryConfigSpec) Descriptor() ([]byte, []int) {
	return file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AzureServiceBusDisasterRecoveryConfigSpec) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *AzureServiceBusDisasterRecoveryConfigSpec) GetPrimaryNamespaceId() *v1.StringValueOrRef {
	if x != nil {
		return x.PrimaryNamespaceId
	}
	return nil
}

func (x *AzureServiceBusDisasterRecoveryConfigSpec) GetPartnerNamespaceId() *v1.StringValueOrRef {
	if x != nil {
		return x.PartnerNamespaceId
	}
	return nil
}

func (x *AzureServiceBusDisasterRecoveryConfigSpec) GetAliasAuthorizationRuleId() *v1.StringValueOrRef {
	if x != nil {
		return x.AliasAuthorizationRuleId
	}
	return nil
}

var File_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto protoreflect.FileDescriptor

const file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDesc = "" +
	"\n" +
	"Ndev/planton/provider/azure/azureservicebusdisasterrecoveryconfig/v1/spec.proto\x12Cdev.planton.provider.azure.azureservicebusdisasterrecoveryconfig.v1\x1a\x1bbuf/validate/validate.proto\x1a2dev/planton/shared/foreignkey/v1/foreign_key.proto\"\xa5\x04\n" +
	")AzureServiceBusDisasterRecoveryConfigSpec\x12+\n" +
	"\n" +
	"alias_name\x18\x01 \x01(\tB\f\xbaH\t\xc8\x01\x01r\x04\x10\x01\x182R\taliasName\x12\x90\x01\n" +
	"\x14primary_namespace_id\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB*\xbaH\x03\xc8\x01\x01\x88\xd4a\x96\x10\x92\xd4a\x1bstatus.outputs.namespace_idR\x12primaryNamespaceId\x12\x94\x01\n" +
	"\x14partner_namespace_id\x18\x03 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB.\xbaH\x03\xc8\x01\x01\x88\xd4a\x96\x10\x92\xd4a\x1bstatus.outputs.namespace_id\x98\xd4a\x01R\x12partnerNamespaceId\x12\xa0\x01\n" +
	"\x1balias_authorization_rule_id\x18\x04 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB-\x88\xd4a\x9b\x10\x92\xd4a$status.outputs.authorization_rule_idR\x18aliasAuthorizationRuleIdB\x97\x04\n" +
	"Gcom.dev.planton.provider.azure.azureservicebusdisasterrecoveryconfig.v1B\tSpecProtoP\x01Z\x8d\x01github.com/plantonhq/planton/apis/dev/planton/provider/azure/azureservicebusdisasterrecoveryconfig/v1;azureservicebusdisasterrecoveryconfigv1\xa2\x02\x05DPPAA\xaa\x02CDev.Planton.Provider.Azure.Azureservicebusdisasterrecoveryconfig.V1\xca\x02CDev\\Planton\\Provider\\Azure\\Azureservicebusdisasterrecoveryconfig\\V1\xe2\x02ODev\\Planton\\Provider\\Azure\\Azureservicebusdisasterrecoveryconfig\\V1\\GPBMetadata\xea\x02HDev::Planton::Provider::Azure::Azureservicebusdisasterrecoveryconfig::V1b\x06proto3"

var (
	file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDescOnce sync.Once
	file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDescData []byte
)

func file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDescGZIP() []byte {
	file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDescOnce.Do(func() {
		file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDesc), len(file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDesc)))
	})
	return file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDescData
}

var file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_goTypes = []any{
	(*AzureServiceBusDisasterRecoveryConfigSpec)(nil), // 0: dev.planton.provider.azure.azureservicebusdisasterrecoveryconfig.v1.AzureServiceBusDisasterRecoveryConfigSpec
	(*v1.StringValueOrRef)(nil),                       // 1: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_depIdxs = []int32{
	1, // 0: dev.planton.provider.azure.azureservicebusdisasterrecoveryconfig.v1.AzureServiceBusDisasterRecoveryConfigSpec.primary_namespace_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 1: dev.planton.provider.azure.azureservicebusdisasterrecoveryconfig.v1.AzureServiceBusDisasterRecoveryConfigSpec.partner_namespace_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 2: dev.planton.provider.azure.azureservicebusdisasterrecoveryconfig.v1.AzureServiceBusDisasterRecoveryConfigSpec.alias_authorization_rule_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_init()
}
func file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_init() {
	if File_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDesc), len(file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_goTypes,
		DependencyIndexes: file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_depIdxs,
		MessageInfos:      file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_msgTypes,
	}.Build()
	File_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto = out.File
	file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_goTypes = nil
	file_dev_planton_provider_azure_azureservicebusdisasterrecoveryconfig_v1_spec_proto_depIdxs = nil
}
