syntax = "proto3";

package dev.planton.civo.civofirewall.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/civo/civofirewall/v1alpha1/outputs.proto";
import "catalog/civo/civofirewall/v1alpha1/spec.proto";
import "shared/metadata.proto";

// civo-firewall
message CivoFirewall {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'civo.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'CivoFirewall'];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  CivoFirewallSpec spec = 4 [(buf.validate.field).required = true];

  //status
  CivoFirewallStatus status = 5;
}

// civo-firewall status
message CivoFirewallStatus {
  //stack-outputs
  //  civo-firewall stack-outputs
  CivoFirewallStackOutputs outputs = 1;
}
