# Example manifest with Pulumi backend configuration in labels
# This manifest can be deployed without specifying --stack flag
apiVersion: code2ai.planton.cloud/v1
kind: MicroserviceKubernetes
metadata:
  id: order-service
  name: Order Service
  labels:
    # Pulumi backend configuration using stack FQDN (preferred)
    pulumi.openmcf.org/stack.fqdn: "myorg/order-service/production"
    
    # Alternative: Individual components (used when stack.fqdn is not present)
    # pulumi.openmcf.org/organization: "myorg"
    # pulumi.openmcf.org/project: "order-service"
    # pulumi.openmcf.org/stack.name: "production"
spec:
  environmentInfo:
    envId: prod-env
    envName: Production
  container:
    app:
      image:
        repo: myorg/order-service
        tag: v1.0.0
      ports:
        - containerPort: 8080
          networkProtocol: TCP
          appProtocol: http
          servicePort: 80
  ingress:
    isEnabled: true
    rules:
      - host: order.example.com
        path: /
        pathType: Prefix
