apiVersion: aws.planton.dev/v1alpha1
kind: AwsLbListenerRule
metadata:
  name: <service-name>-route
spec:
  region: <aws-region>
  listenerArn:
    valueFrom:
      kind: AwsLbListener
      name: <listener-resource-name>
      fieldPath: status.outputs.listener_arn
  priority: 10
  conditions:
    - pathPattern:
        values:
          - /api/*
  actions:
    - type: forward
      forward:
        targetGroups:
          - arn:
              valueFrom:
                kind: AwsLbTargetGroup
                name: <target-group-resource-name>
                fieldPath: status.outputs.target_group_arn
