apiVersion: aws.planton.dev/v1alpha1
kind: AwsTransitGatewayRouteTable
metadata:
  org: example-org
  env: prod
  name: prod-domain
  id: prod-domain-id
spec:
  region: <aws-region>
  transitGatewayId:
    valueFrom:
      kind: AwsTransitGateway
      name: segmented-hub
      fieldPath: status.outputs.transit_gateway_id
  associations:
    - valueFrom:
        kind: AwsTransitGatewayVpcAttachment
        name: prod-vpc-attachment
        fieldPath: status.outputs.attachment_id
  propagations:
    - valueFrom:
        kind: AwsTransitGatewayVpcAttachment
        name: shared-services-attachment
        fieldPath: status.outputs.attachment_id
  routes:
    - destinationCidrBlock: 10.200.0.0/16
      blackhole: true
