syntax = "proto3";

package dev.planton.provider.gcp.gcpcomputedisk.v1;

import "buf/validate/validate.proto";
import "dev/planton/provider/gcp/gcpcomputedisk/v1/spec.proto";
import "dev/planton/provider/gcp/gcpcomputedisk/v1/stack_outputs.proto";
import "dev/planton/shared/metadata.proto";

//gcp-compute-disk
message GcpComputeDisk {
  string api_version = 1 [(buf.validate.field).string.const = 'gcp.planton.dev/v1'];
  string kind = 2 [(buf.validate.field).string.const = 'GcpComputeDisk'];
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];
  GcpComputeDiskSpec spec = 4 [(buf.validate.field).required = true];
  GcpComputeDiskStatus status = 5;
}

message GcpComputeDiskStatus {
  GcpComputeDiskStackOutputs outputs = 1;
}
