syntax = "proto3";

package dev.planton.provider.kubernetes.kubernetesrabbitmqoperator.v1alpha1;

import "dev/planton/provider/kubernetes/kubernetesrabbitmqoperator/v1alpha1/api.proto";
import "dev/planton/provider/kubernetes/provider.proto";

// kubernetes-rabbit-mq-operator stack-input
message KubernetesRabbitMqOperatorStackInput {
  // target cloud-resource
  KubernetesRabbitMqOperator target = 1;
  // provider-credential
  dev.planton.provider.kubernetes.KubernetesProviderConfig provider_config = 2;
  // kubernetes namespace
  string kubernetes_namespace = 3;
}
