load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "module",
    srcs = [
        "locals.go",
        "main.go",
        "nosql_table.go",
        "outputs.go",
    ],
    importpath = "github.com/plantonhq/planton/catalog/oci/ocinosqltable/iac/pulumi/module",
    visibility = ["//visibility:public"],
    deps = [
        "//catalog/oci/ocinosqltable/v1alpha1",
        "//pkg/iac/pulumi/pulumimodule/provider/oci/pulumiociprovider",
        "//shared/cloudresourcekind",
        "@com_github_pkg_errors//:errors",
        "@com_github_pulumi_pulumi_oci_sdk_v4//go/oci",
        "@com_github_pulumi_pulumi_oci_sdk_v4//go/oci/nosql",
        "@com_github_pulumi_pulumi_sdk_v3//go/pulumi",
    ],
)
