syntax = "proto3";

package dev.planton.provider.aws.awsapprunnerobservabilityconfiguration.v1alpha1;

import "dev/planton/provider/aws/awsapprunnerobservabilityconfiguration/v1alpha1/api.proto";
import "dev/planton/provider/aws/provider.proto";

// AwsAppRunnerObservabilityConfigurationStackInput is the input for the
// aws-app-runner-observability-configuration IaC modules.
message AwsAppRunnerObservabilityConfigurationStackInput {
  // target cloud-resource
  AwsAppRunnerObservabilityConfiguration target = 1;

  // provider-config
  dev.planton.provider.aws.AwsProviderConfig provider_config = 2;
}
