// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/azure/azuredatafactorypipeline/v1alpha1/spec.proto

package azuredatafactorypipelinev1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// **AzureDataFactoryPipelineSpec** defines an Azure Data Factory
// pipeline -- one unit of work inside a factory
// (AzureDataFactory): an ordered set of activities (copy data, run a
// data flow, call a stored procedure, wait, branch) that executes as
// a whole when triggered.
//
// The pipeline's activities travel as raw JSON (activities_json) --
// the same "activities" array the Data Factory Studio's Code view
// shows. Azure owns that schema (dozens of activity types, each with
// its own shape); the catalog deliberately does not re-model it.
type AzureDataFactoryPipelineSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Data Factory the pipeline lives in, by ARM ID. Can be a
	// literal string or a reference to an AzureDataFactory output.
	//
	// **ForceNew**: changing this destroys and recreates the pipeline.
	DataFactoryId *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=data_factory_id,json=dataFactoryId,proto3" json:"data_factory_id,omitempty"`
	// The pipeline's name -- unique within the factory. Must start with
	// a letter, number, or underscore, and must not contain any of
	// < > * # . % & : \ + ? / (Azure's pipeline naming rules).
	//
	// **ForceNew**: changing this destroys and recreates the pipeline.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// A human-readable description of what the pipeline does.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The pipeline's run-time parameters and their DEFAULT values --
	// callers override them per run. Azure types every parameter
	// declared here as String (declare other-typed parameters inside
	// activities_json if you need them; the provider round-trips only
	// string-typed entries).
	Parameters map[string]string `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The pipeline's variables and their default values -- mutable
	// state activities read and set during a run. The same
	// String-typing note as parameters applies.
	Variables map[string]string `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The pipeline's activities as a raw JSON ARRAY -- exactly the
	// "activities" array from the Data Factory Studio's Code view, e.g.
	// [{"name": "wait", "type": "Wait", "typeProperties":
	// {"waitTimeInSeconds": 10}}]. Azure owns the activity schema;
	// invalid JSON or unknown activity shapes fail at deploy time.
	// Key ordering inside the JSON is not meaningful (both engines
	// normalize it when diffing).
	ActivitiesJson string `protobuf:"bytes,6,opt,name=activities_json,json=activitiesJson,proto3" json:"activities_json,omitempty"`
	// Free-form annotation strings stored on the pipeline.
	Annotations []string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty"`
	// The maximum number of concurrent runs of this pipeline, 1-50.
	// Omit for Azure's unlimited default.
	Concurrency *int32 `protobuf:"varint,8,opt,name=concurrency,proto3,oneof" json:"concurrency,omitempty"`
	// The folder the pipeline appears under in the Data Factory
	// Studio, e.g. "ingest/daily". Omit for the root.
	Folder string `protobuf:"bytes,9,opt,name=folder,proto3" json:"folder,omitempty"`
	// How long the pipeline may run before its elapsed-time metric
	// fires, as a Data Factory TimeSpan string (e.g. "0.00:30:00" for
	// 30 minutes). Omit to skip the metric.
	MonitorMetricsAfterDuration string `protobuf:"bytes,10,opt,name=monitor_metrics_after_duration,json=monitorMetricsAfterDuration,proto3" json:"monitor_metrics_after_duration,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AzureDataFactoryPipelineSpec) Reset() {
	*x = AzureDataFactoryPipelineSpec{}
	mi := &file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureDataFactoryPipelineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureDataFactoryPipelineSpec) ProtoMessage() {}

func (x *AzureDataFactoryPipelineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureDataFactoryPipelineSpec.ProtoReflect.Descriptor instead.
func (*AzureDataFactoryPipelineSpec) Descriptor() ([]byte, []int) {
	return file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AzureDataFactoryPipelineSpec) GetDataFactoryId() *v1.StringValueOrRef {
	if x != nil {
		return x.DataFactoryId
	}
	return nil
}

func (x *AzureDataFactoryPipelineSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AzureDataFactoryPipelineSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AzureDataFactoryPipelineSpec) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *AzureDataFactoryPipelineSpec) GetVariables() map[string]string {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *AzureDataFactoryPipelineSpec) GetActivitiesJson() string {
	if x != nil {
		return x.ActivitiesJson
	}
	return ""
}

func (x *AzureDataFactoryPipelineSpec) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *AzureDataFactoryPipelineSpec) GetConcurrency() int32 {
	if x != nil && x.Concurrency != nil {
		return *x.Concurrency
	}
	return 0
}

func (x *AzureDataFactoryPipelineSpec) GetFolder() string {
	if x != nil {
		return x.Folder
	}
	return ""
}

func (x *AzureDataFactoryPipelineSpec) GetMonitorMetricsAfterDuration() string {
	if x != nil {
		return x.MonitorMetricsAfterDuration
	}
	return ""
}

var File_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	":catalog/azure/azuredatafactorypipeline/v1alpha1/spec.proto\x123dev.planton.azure.azuredatafactorypipeline.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\"\x9d\b\n" +
	"\x1cAzureDataFactoryPipelineSpec\x12\x89\x01\n" +
	"\x0fdata_factory_id\x18\x01 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB-\xbaH\x03\xc8\x01\x01\x88\xd4a\x96\x11\x92\xd4a\x1estatus.outputs.data_factory_idR\rdataFactoryId\x12\xe3\x01\n" +
	"\x04name\x18\x02 \x01(\tB\xce\x01\xbaH\xca\x01\xba\x01\xc3\x01\n" +
	"!data_factory_pipeline_name_format\x12kPipeline names must start with a letter, number, or underscore and must not contain < > * # . % & : \\ + ? /\x1a1this.matches('^[A-Za-z0-9_][^<>*#.%&:\\\\\\\\+?/]*$')\xc8\x01\x01R\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x81\x01\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2a.dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.ParametersEntryR\n" +
	"parameters\x12~\n" +
	"\tvariables\x18\x05 \x03(\v2`.dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.VariablesEntryR\tvariables\x12'\n" +
	"\x0factivities_json\x18\x06 \x01(\tR\x0eactivitiesJson\x12 \n" +
	"\vannotations\x18\a \x03(\tR\vannotations\x120\n" +
	"\vconcurrency\x18\b \x01(\x05B\t\xbaH\x06\x1a\x04\x182(\x01H\x00R\vconcurrency\x88\x01\x01\x12\x16\n" +
	"\x06folder\x18\t \x01(\tR\x06folder\x12C\n" +
	"\x1emonitor_metrics_after_duration\x18\n" +
	" \x01(\tR\x1bmonitorMetricsAfterDuration\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_concurrencyB\xa4\x03\n" +
	"7com.dev.planton.azure.azuredatafactorypipeline.v1alpha1B\tSpecProtoP\x01Zmgithub.com/plantonhq/planton/catalog/azure/azuredatafactorypipeline/v1alpha1;azuredatafactorypipelinev1alpha1\xa2\x02\x04DPAA\xaa\x023Dev.Planton.Azure.Azuredatafactorypipeline.V1alpha1\xca\x023Dev\\Planton\\Azure\\Azuredatafactorypipeline\\V1alpha1\xe2\x02?Dev\\Planton\\Azure\\Azuredatafactorypipeline\\V1alpha1\\GPBMetadata\xea\x027Dev::Planton::Azure::Azuredatafactorypipeline::V1alpha1b\x06proto3"

var (
	file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDesc), len(file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDescData
}

var file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_goTypes = []any{
	(*AzureDataFactoryPipelineSpec)(nil), // 0: dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec
	nil,                                  // 1: dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.ParametersEntry
	nil,                                  // 2: dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.VariablesEntry
	(*v1.StringValueOrRef)(nil),          // 3: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_depIdxs = []int32{
	3, // 0: dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.data_factory_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 1: dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.parameters:type_name -> dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.ParametersEntry
	2, // 2: dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.variables:type_name -> dev.planton.azure.azuredatafactorypipeline.v1alpha1.AzureDataFactoryPipelineSpec.VariablesEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_init() }
func file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_init() {
	if File_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDesc), len(file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto = out.File
	file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_goTypes = nil
	file_catalog_azure_azuredatafactorypipeline_v1alpha1_spec_proto_depIdxs = nil
}
