load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tfbackend",
    srcs = ["tf_backend.go"],
    importpath = "github.com/plantonhq/planton/pkg/iac/tofu/tfbackend",
    visibility = ["//visibility:public"],
    deps = [
        "//shared/iac/terraform",
        "@com_github_pkg_errors//:errors",
    ],
)

go_test(
    name = "tfbackend_test",
    srcs = ["tf_backend_test.go"],
    embed = [":tfbackend"],
    deps = ["//shared/iac/terraform"],
)
