apiVersion: gcp.planton.dev/v1
kind: GcpServerlessVpcConnector
metadata:
  name: svc-egress-shared
spec:
  region: us-central1
  subnet:
    name:
      value: connector-subnet # a dedicated /28 subnetwork, or reference a GcpSubnetwork
    projectId: shared-vpc-host-project # the Shared VPC host project that owns the subnet
  machineType: e2-micro
  minInstances: 2
  maxInstances: 4
