apiVersion: gcp.planton.dev/v1
kind: GcpCloudSqlDatabase
metadata:
  name: my-orders-database
spec:
  projectId:
    value: my-gcp-project-123 # replace with your project ID
  instance:
    valueFrom:
      kind: GcpCloudSql
      name: my-postgres-prod # replace with your instance's resource name
      fieldPath: status.outputs.instance_name
  databaseName: orders
