// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/hetznercloud/hetznercloudfirewall/v1alpha1/api.proto

package hetznercloudfirewallv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	shared "github.com/plantonhq/planton/shared"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// hetznercloud-firewall
type HetznerCloudFirewall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// api-version
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// resource-kind
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// metadata
	Metadata *shared.CloudResourceMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// spec
	Spec *HetznerCloudFirewallSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// status
	Status        *HetznerCloudFirewallStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HetznerCloudFirewall) Reset() {
	*x = HetznerCloudFirewall{}
	mi := &file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HetznerCloudFirewall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HetznerCloudFirewall) ProtoMessage() {}

func (x *HetznerCloudFirewall) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HetznerCloudFirewall.ProtoReflect.Descriptor instead.
func (*HetznerCloudFirewall) Descriptor() ([]byte, []int) {
	return file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *HetznerCloudFirewall) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *HetznerCloudFirewall) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HetznerCloudFirewall) GetMetadata() *shared.CloudResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HetznerCloudFirewall) GetSpec() *HetznerCloudFirewallSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *HetznerCloudFirewall) GetStatus() *HetznerCloudFirewallStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// hetznercloud-firewall status
type HetznerCloudFirewallStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stack-outputs
	//
	//	hetznercloud-firewall stack-outputs
	Outputs       *HetznerCloudFirewallStackOutputs `protobuf:"bytes,1,opt,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HetznerCloudFirewallStatus) Reset() {
	*x = HetznerCloudFirewallStatus{}
	mi := &file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HetznerCloudFirewallStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HetznerCloudFirewallStatus) ProtoMessage() {}

func (x *HetznerCloudFirewallStatus) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HetznerCloudFirewallStatus.ProtoReflect.Descriptor instead.
func (*HetznerCloudFirewallStatus) Descriptor() ([]byte, []int) {
	return file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *HetznerCloudFirewallStatus) GetOutputs() *HetznerCloudFirewallStackOutputs {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto protoreflect.FileDescriptor

const file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"<catalog/hetznercloud/hetznercloudfirewall/v1alpha1/api.proto\x126dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a@catalog/hetznercloud/hetznercloudfirewall/v1alpha1/outputs.proto\x1a=catalog/hetznercloud/hetznercloudfirewall/v1alpha1/spec.proto\x1a\x15shared/metadata.proto\"\xbc\x03\n" +
	"\x14HetznerCloudFirewall\x12J\n" +
	"\vapi_version\x18\x01 \x01(\tB)\xbaH&r$\n" +
	"\"hetzner-cloud.planton.dev/v1alpha1R\n" +
	"apiVersion\x12/\n" +
	"\x04kind\x18\x02 \x01(\tB\x1b\xbaH\x18r\x16\n" +
	"\x14HetznerCloudFirewallR\x04kind\x12M\n" +
	"\bmetadata\x18\x03 \x01(\v2).dev.planton.shared.CloudResourceMetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x12l\n" +
	"\x04spec\x18\x04 \x01(\v2P.dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallSpecB\x06\xbaH\x03\xc8\x01\x01R\x04spec\x12j\n" +
	"\x06status\x18\x05 \x01(\v2R.dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallStatusR\x06status\"\x90\x01\n" +
	"\x1aHetznerCloudFirewallStatus\x12r\n" +
	"\aoutputs\x18\x01 \x01(\v2X.dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallStackOutputsR\aoutputsB\xb1\x03\n" +
	":com.dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1B\bApiProtoP\x01Zlgithub.com/plantonhq/planton/catalog/hetznercloud/hetznercloudfirewall/v1alpha1;hetznercloudfirewallv1alpha1\xa2\x02\x04DPHH\xaa\x026Dev.Planton.Hetznercloud.Hetznercloudfirewall.V1alpha1\xca\x026Dev\\Planton\\Hetznercloud\\Hetznercloudfirewall\\V1alpha1\xe2\x02BDev\\Planton\\Hetznercloud\\Hetznercloudfirewall\\V1alpha1\\GPBMetadata\xea\x02:Dev::Planton::Hetznercloud::Hetznercloudfirewall::V1alpha1b\x06proto3"

var (
	file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescOnce sync.Once
	file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescData []byte
)

func file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDesc), len(file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDesc)))
	})
	return file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDescData
}

var file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_goTypes = []any{
	(*HetznerCloudFirewall)(nil),             // 0: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewall
	(*HetznerCloudFirewallStatus)(nil),       // 1: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallStatus
	(*shared.CloudResourceMetadata)(nil),     // 2: dev.planton.shared.CloudResourceMetadata
	(*HetznerCloudFirewallSpec)(nil),         // 3: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallSpec
	(*HetznerCloudFirewallStackOutputs)(nil), // 4: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallStackOutputs
}
var file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewall.metadata:type_name -> dev.planton.shared.CloudResourceMetadata
	3, // 1: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewall.spec:type_name -> dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallSpec
	1, // 2: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewall.status:type_name -> dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallStatus
	4, // 3: dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallStatus.outputs:type_name -> dev.planton.hetznercloud.hetznercloudfirewall.v1alpha1.HetznerCloudFirewallStackOutputs
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_init() }
func file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_init() {
	if File_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto != nil {
		return
	}
	file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_outputs_proto_init()
	file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_spec_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDesc), len(file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto = out.File
	file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_goTypes = nil
	file_catalog_hetznercloud_hetznercloudfirewall_v1alpha1_api_proto_depIdxs = nil
}
