syntax = "proto3";

package dev.planton.alicloud.alicloudceninstance.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/alicloud/alicloudceninstance/v1alpha1/spec.proto";
import "catalog/alicloud/alicloudceninstance/v1alpha1/stack_outputs.proto";
import "shared/metadata.proto";

// alicloud-cen-instance
message AliCloudCenInstance {
  // api-version
  string api_version = 1 [(buf.validate.field).string.const = 'alicloud.planton.dev/v1alpha1'];

  // resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'AliCloudCenInstance'];

  // metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  // spec
  AliCloudCenInstanceSpec spec = 4 [(buf.validate.field).required = true];

  // status
  AliCloudCenInstanceStatus status = 5;
}

// alicloud-cen-instance status
message AliCloudCenInstanceStatus {
  // stack-outputs
  AliCloudCenInstanceStackOutputs outputs = 1;
}
