load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cloudresourcekind",
    srcs = [
        "cloud_provider_service_group.pb.go",
        "cloud_resource_kind.pb.go",
        "cloud_resource_provider.pb.go",
        "kubernetes.pb.go",
    ],
    importpath = "github.com/plantonhq/planton/shared/cloudresourcekind",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
        "@org_golang_google_protobuf//types/descriptorpb",
    ],
)

go_test(
    name = "cloudresourcekind_test",
    srcs = ["containment_decisions_test.go"],
    data = glob(["testdata/**"]),
    deps = [
        ":cloudresourcekind",
        "//pkg/crkreflect",
        "//shared/foreignkey/v1:foreignkey",
        "//shared/options",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//reflect/protoregistry",
    ],
)
