load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "componentcapacityderivation",
    srcs = [
        "api.pb.go",
        "spec.pb.go",
    ],
    importpath = "github.com/plantonhq/planton/finops/componentcapacityderivation/v1",
    visibility = ["//visibility:public"],
    deps = [
        "//finops/componentcostderivation/v1:componentcostderivation",
        "//shared",
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
