apiVersion: kubernetes.planton.dev/v1alpha1
kind: KubernetesClusterIssuer
metadata:
  name: vault-pki
spec:
  certManagerNamespace:
    value: cert-manager
  config:
    vault:
      server: "https://<vault-host>:8200"
      path: "<pki-mount>/sign/<role-name>"
      kubernetesAuth:
        role: "<vault-role-bound-to-cert-manager>"
        serviceAccountName:
          value: "<service-account-name>"
