apiVersion: azure.planton.dev/v1alpha1
kind: AzurePrivateDnsZone
metadata:
  name: corp-internal-zone
spec:
  resourceGroup:
    value: <resource-group-name>
  # Replace with your internal domain (a valid DNS name).
  name: corp.internal
  soaRecord:
    email: <dns-admin-email-soa-format>
    minimumTtl: 30
  tags:
    cost-center: <cost-center>
