load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "chart-validator_lib",
    srcs = ["main.go"],
    importpath = "github.com/plantonhq/planton/cmd/chart-validator",
    visibility = ["//visibility:private"],
    deps = ["//pkg/infrachart/validatecmd"],
)

go_binary(
    name = "chart-validator",
    embed = [":chart-validator_lib"],
    visibility = ["//visibility:public"],
)
