apiVersion: kubernetes.planton.dev/v1
kind: KubernetesResourceQuota
metadata:
  name: object-count-caps
spec:
  name: object-count-caps
  namespace:
    value: "<your-namespace>"
  hard:
    pods: "100"
    services: "20"
    persistentvolumeclaims: "10"
