apiVersion: aws.openmcf.org/v1
kind: AwsRoute53DnsRecord
metadata:
  name: test-dns-record
spec:
  zone_id:
    value: Z0123456789ABCDEFGHIJ
  name: test.example.com
  type: A
  ttl: 300
  values:
    - 192.0.2.1
