// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1alpha1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ClusterPushSecretList is a list of ClusterPushSecret
type ClusterPushSecretList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of clusterpushsecrets. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items ClusterPushSecretTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewClusterPushSecretList registers a new resource with the given unique name, arguments, and options.
func NewClusterPushSecretList(ctx *pulumi.Context,
	name string, args *ClusterPushSecretListArgs, opts ...pulumi.ResourceOption) (*ClusterPushSecretList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("external-secrets.io/v1alpha1")
	args.Kind = pulumi.StringPtr("ClusterPushSecretList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource ClusterPushSecretList
	err := ctx.RegisterResource("kubernetes:external-secrets.io/v1alpha1:ClusterPushSecretList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetClusterPushSecretList gets an existing ClusterPushSecretList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetClusterPushSecretList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClusterPushSecretListState, opts ...pulumi.ResourceOption) (*ClusterPushSecretList, error) {
	var resource ClusterPushSecretList
	err := ctx.ReadResource("kubernetes:external-secrets.io/v1alpha1:ClusterPushSecretList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ClusterPushSecretList resources.
type clusterPushSecretListState struct {
}

type ClusterPushSecretListState struct {
}

func (ClusterPushSecretListState) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterPushSecretListState)(nil)).Elem()
}

type clusterPushSecretListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of clusterpushsecrets. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []ClusterPushSecretType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a ClusterPushSecretList resource.
type ClusterPushSecretListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of clusterpushsecrets. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items ClusterPushSecretTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (ClusterPushSecretListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterPushSecretListArgs)(nil)).Elem()
}

type ClusterPushSecretListInput interface {
	pulumi.Input

	ToClusterPushSecretListOutput() ClusterPushSecretListOutput
	ToClusterPushSecretListOutputWithContext(ctx context.Context) ClusterPushSecretListOutput
}

func (*ClusterPushSecretList) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterPushSecretList)(nil)).Elem()
}

func (i *ClusterPushSecretList) ToClusterPushSecretListOutput() ClusterPushSecretListOutput {
	return i.ToClusterPushSecretListOutputWithContext(context.Background())
}

func (i *ClusterPushSecretList) ToClusterPushSecretListOutputWithContext(ctx context.Context) ClusterPushSecretListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterPushSecretListOutput)
}

// ClusterPushSecretListArrayInput is an input type that accepts ClusterPushSecretListArray and ClusterPushSecretListArrayOutput values.
// You can construct a concrete instance of `ClusterPushSecretListArrayInput` via:
//
//	ClusterPushSecretListArray{ ClusterPushSecretListArgs{...} }
type ClusterPushSecretListArrayInput interface {
	pulumi.Input

	ToClusterPushSecretListArrayOutput() ClusterPushSecretListArrayOutput
	ToClusterPushSecretListArrayOutputWithContext(context.Context) ClusterPushSecretListArrayOutput
}

type ClusterPushSecretListArray []ClusterPushSecretListInput

func (ClusterPushSecretListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClusterPushSecretList)(nil)).Elem()
}

func (i ClusterPushSecretListArray) ToClusterPushSecretListArrayOutput() ClusterPushSecretListArrayOutput {
	return i.ToClusterPushSecretListArrayOutputWithContext(context.Background())
}

func (i ClusterPushSecretListArray) ToClusterPushSecretListArrayOutputWithContext(ctx context.Context) ClusterPushSecretListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterPushSecretListArrayOutput)
}

// ClusterPushSecretListMapInput is an input type that accepts ClusterPushSecretListMap and ClusterPushSecretListMapOutput values.
// You can construct a concrete instance of `ClusterPushSecretListMapInput` via:
//
//	ClusterPushSecretListMap{ "key": ClusterPushSecretListArgs{...} }
type ClusterPushSecretListMapInput interface {
	pulumi.Input

	ToClusterPushSecretListMapOutput() ClusterPushSecretListMapOutput
	ToClusterPushSecretListMapOutputWithContext(context.Context) ClusterPushSecretListMapOutput
}

type ClusterPushSecretListMap map[string]ClusterPushSecretListInput

func (ClusterPushSecretListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClusterPushSecretList)(nil)).Elem()
}

func (i ClusterPushSecretListMap) ToClusterPushSecretListMapOutput() ClusterPushSecretListMapOutput {
	return i.ToClusterPushSecretListMapOutputWithContext(context.Background())
}

func (i ClusterPushSecretListMap) ToClusterPushSecretListMapOutputWithContext(ctx context.Context) ClusterPushSecretListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterPushSecretListMapOutput)
}

type ClusterPushSecretListOutput struct{ *pulumi.OutputState }

func (ClusterPushSecretListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterPushSecretList)(nil)).Elem()
}

func (o ClusterPushSecretListOutput) ToClusterPushSecretListOutput() ClusterPushSecretListOutput {
	return o
}

func (o ClusterPushSecretListOutput) ToClusterPushSecretListOutputWithContext(ctx context.Context) ClusterPushSecretListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o ClusterPushSecretListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterPushSecretList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of clusterpushsecrets. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o ClusterPushSecretListOutput) Items() ClusterPushSecretTypeArrayOutput {
	return o.ApplyT(func(v *ClusterPushSecretList) ClusterPushSecretTypeArrayOutput { return v.Items }).(ClusterPushSecretTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ClusterPushSecretListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterPushSecretList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o ClusterPushSecretListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *ClusterPushSecretList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type ClusterPushSecretListArrayOutput struct{ *pulumi.OutputState }

func (ClusterPushSecretListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClusterPushSecretList)(nil)).Elem()
}

func (o ClusterPushSecretListArrayOutput) ToClusterPushSecretListArrayOutput() ClusterPushSecretListArrayOutput {
	return o
}

func (o ClusterPushSecretListArrayOutput) ToClusterPushSecretListArrayOutputWithContext(ctx context.Context) ClusterPushSecretListArrayOutput {
	return o
}

func (o ClusterPushSecretListArrayOutput) Index(i pulumi.IntInput) ClusterPushSecretListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ClusterPushSecretList {
		return vs[0].([]*ClusterPushSecretList)[vs[1].(int)]
	}).(ClusterPushSecretListOutput)
}

type ClusterPushSecretListMapOutput struct{ *pulumi.OutputState }

func (ClusterPushSecretListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClusterPushSecretList)(nil)).Elem()
}

func (o ClusterPushSecretListMapOutput) ToClusterPushSecretListMapOutput() ClusterPushSecretListMapOutput {
	return o
}

func (o ClusterPushSecretListMapOutput) ToClusterPushSecretListMapOutputWithContext(ctx context.Context) ClusterPushSecretListMapOutput {
	return o
}

func (o ClusterPushSecretListMapOutput) MapIndex(k pulumi.StringInput) ClusterPushSecretListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ClusterPushSecretList {
		return vs[0].(map[string]*ClusterPushSecretList)[vs[1].(string)]
	}).(ClusterPushSecretListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterPushSecretListInput)(nil)).Elem(), &ClusterPushSecretList{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterPushSecretListArrayInput)(nil)).Elem(), ClusterPushSecretListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterPushSecretListMapInput)(nil)).Elem(), ClusterPushSecretListMap{})
	pulumi.RegisterOutputType(ClusterPushSecretListOutput{})
	pulumi.RegisterOutputType(ClusterPushSecretListArrayOutput{})
	pulumi.RegisterOutputType(ClusterPushSecretListMapOutput{})
}
