load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "verify",
    srcs = [
        "aks_cluster.go",
        "aks_node_pool.go",
        "application_gateway.go",
        "container_registry.go",
        "federated_identity_credential.go",
        "key_vault.go",
        "key_vault_certificate.go",
        "key_vault_key.go",
        "load_balancer.go",
        "managed_disk.go",
        "nat_gateway.go",
        "network_interface.go",
        "network_security_group.go",
        "postgresql_flexible_server.go",
        "private_dns_zone.go",
        "private_dns_zone_virtual_network_link.go",
        "public_ip.go",
        "public_ip_prefix.go",
        "resource_group.go",
        "role_assignment.go",
        "role_definition.go",
        "route_table.go",
        "subnet.go",
        "user_assigned_identity.go",
        "verifier.go",
        "virtual_machine.go",
        "virtual_machine_scale_set.go",
        "virtual_network.go",
        "virtual_network_peering.go",
        "web_application_firewall_policy.go",
    ],
    importpath = "github.com/plantonhq/planton/apis/dev/planton/provider/azure/aa_e2e/verify",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_azure_azure_sdk_for_go_sdk_azcore//:azcore",
        "@com_github_azure_azure_sdk_for_go_sdk_resourcemanager_authorization_armauthorization_v2//:armauthorization",
        "@com_github_azure_azure_sdk_for_go_sdk_resourcemanager_resources_armresources//:armresources",
        "@com_github_azure_azure_sdk_for_go_sdk_security_keyvault_azcertificates//:azcertificates",
        "@com_github_pkg_errors//:errors",
    ],
)
