load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "cli_lib",
    srcs = ["main.go"],
    importpath = "github.com/plantonhq/planton/pkg/catalogschema/cli",
    visibility = ["//visibility:private"],
    deps = ["//pkg/catalogschema"],
)

go_binary(
    name = "cli",
    embed = [":cli_lib"],
    visibility = ["//visibility:public"],
)
