{% if values.certManagerEnabled | bool %}
---
apiVersion: kubernetes.planton.dev/v1
kind: KubernetesCertManager
metadata:
  name: {{ values.cluster_name }}-cert-manager
  relationships:
    - kind: GcpGkeNodePool
      name: "{{ values.node_pool_name }}"
      type: runs_on
spec:
  namespace:
    value: cert-manager
  createNamespace: true
{% endif %}

