{% if values.externalDnsEnabled | bool %}
---
apiVersion: kubernetes.planton.dev/v1
kind: KubernetesExternalDns
metadata:
  name: {{ values.cluster_name }}-external-dns
  relationships:
    - kind: GcpGkeNodePool
      name: "{{ values.node_pool_name }}"
      type: runs_on
spec:
  namespace:
    value: external-dns
  createNamespace: true
{% endif %}

