syntax = "proto3";

package dev.planton.digitalocean.digitaloceandatabasedb.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/digitalocean/digitaloceandatabasedb/v1alpha1/outputs.proto";
import "catalog/digitalocean/digitaloceandatabasedb/v1alpha1/spec.proto";
import "shared/metadata.proto";

// digital-ocean-database-db
message DigitalOceanDatabaseDb {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = 'digital-ocean.planton.dev/v1alpha1'];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = 'DigitalOceanDatabaseDb'];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  DigitalOceanDatabaseDbSpec spec = 4 [(buf.validate.field).required = true];

  //status
  DigitalOceanDatabaseDbStatus status = 5;
}

// digital-ocean-database-db status
message DigitalOceanDatabaseDbStatus {
  //stack-outputs
  //  digital-ocean-database-db stack-outputs
  DigitalOceanDatabaseDbStackOutputs outputs = 1;
}
