syntax = "proto3";

package dev.planton.provider.azure.azurepublicipprefix.v1;

import "dev/planton/provider/azure/azurepublicipprefix/v1/api.proto";
import "dev/planton/provider/azure/provider.proto";

// AzurePublicIpPrefixStackInput is the input to the IaC modules
// (Pulumi/Terraform). It contains the target resource definition and Azure
// provider credentials.
message AzurePublicIpPrefixStackInput {
  // The public IP prefix resource to deploy.
  AzurePublicIpPrefix target = 1;

  // Azure provider configuration (credentials).
  dev.planton.provider.azure.AzureProviderConfig provider_config = 2;
}
