apiVersion: aws.planton.dev/v1
kind: AwsMemorydbAcl
metadata:
  name: payments-env-acl
  id: test-memorydb-acl
  org: test-org
  env: dev
spec:
  region: us-west-2
  userNames:
    - value: orders-service
    - value: analytics-service
