apiVersion: aws.planton.dev/v1alpha1
kind: AwsRestApiGateway
metadata:
  name: my-health-api
spec:
  region: <aws-region>
  routes:
    - path: /health
      method: GET
      integration:
        type: MOCK
        requestTemplates:
          application/json: '{"statusCode":200}'
      responses:
        - statusCode: "200"
          integrationResponseTemplates:
            application/json: '{"ok":true}'
