apiVersion: aws.planton.dev/v1alpha1
kind: AwsSnsSubscription
metadata:
  name: test-sqs-subscription
spec:
  region: us-west-2
  topicArn:
    value: "arn:aws:sns:us-west-2:123456789012:order-events"
  protocol: sqs
  endpoint:
    value: "arn:aws:sqs:us-west-2:123456789012:order-processor"
  rawMessageDelivery: true
