apiVersion: azure.planton.dev/v1
kind: AzureRouteTable
metadata:
  name: egress-via-firewall
spec:
  region: eastus
  resourceGroup:
    value: <resource-group-name>
  name: egress-via-firewall
  routes:
    - name: default-via-firewall
      addressPrefix: "0.0.0.0/0"
      nextHopType: VIRTUAL_APPLIANCE
      nextHopInIpAddress: <firewall-private-ip>
  bgpRoutePropagationEnabled: false
  tags:
    cost-center: <cost-center>
