apiVersion: cloudflare.planton.dev/v1alpha1
kind: CloudflareR2Bucket
metadata:
  name: my-public-cdn-bucket
spec:
  bucketName: replace-with-your-bucket-name
  accountId: "0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d" # replace with your account id
  location: auto
  publicAccess: true
  customDomains:
    - enabled: true
      zoneId:
        value: <cloudflare-zone-id>
      domain: <cdn-subdomain>.<your-domain.com>
      minTls: "1.2"
  cors:
    rules:
      - allowed:
          methods: [GET, HEAD]
          origins:
            - "*"
        maxAgeSeconds: 3600
