syntax = "proto3";

package dev.planton.hetznercloud.hetznercloudsnapshot.v1alpha1;

import "buf/validate/validate.proto";
import "catalog/hetznercloud/hetznercloudsnapshot/v1alpha1/spec.proto";
import "catalog/hetznercloud/hetznercloudsnapshot/v1alpha1/stack_outputs.proto";
import "shared/metadata.proto";

// hetznercloud-snapshot
message HetznerCloudSnapshot {
  //api-version
  string api_version = 1 [(buf.validate.field).string.const = "hetzner-cloud.planton.dev/v1alpha1"];

  //resource-kind
  string kind = 2 [(buf.validate.field).string.const = "HetznerCloudSnapshot"];

  //metadata
  dev.planton.shared.CloudResourceMetadata metadata = 3 [(buf.validate.field).required = true];

  //spec
  HetznerCloudSnapshotSpec spec = 4 [(buf.validate.field).required = true];

  //status
  HetznerCloudSnapshotStatus status = 5;
}

// hetznercloud-snapshot status
message HetznerCloudSnapshotStatus {
  //stack-outputs
  //  hetznercloud-snapshot stack-outputs
  HetznerCloudSnapshotStackOutputs outputs = 1;
}
