apiVersion: digitalocean.openmcf.org/v1
kind: DigitalOceanDnsRecord
metadata:
  name: test-dns-record
spec:
  domain:
    value: "example.com"
  name: "www"
  type: A
  value:
    value: "192.0.2.1"
  ttl_seconds: 3600
