syntax = "proto3";

package dev.planton.provider.kubernetes.kuberneteskyverno.v1alpha1;

import "dev/planton/provider/kubernetes/kuberneteskyverno/v1alpha1/api.proto";
import "dev/planton/provider/kubernetes/provider.proto";

// KubernetesKyvernoStackInput defines the inputs required for the IaC modules.
message KubernetesKyvernoStackInput {
  // target cloud-resource
  KubernetesKyverno target = 1;
  // provider-config for Kubernetes
  dev.planton.provider.kubernetes.KubernetesProviderConfig provider_config = 2;
}
