apiVersion: aws.planton.dev/v1alpha1
kind: AwsTransitGatewayRouteTable
metadata:
  org: example-org
  env: prod
  name: managed-default-domain
  id: managed-default-domain-id
spec:
  region: <aws-region>
  transitGatewayId:
    valueFrom:
      kind: AwsTransitGateway
      name: flat-hub
      fieldPath: status.outputs.transit_gateway_id
  associations:
    - attachmentId:
        valueFrom:
          kind: AwsTransitGatewayVpcAttachment
          name: legacy-vpc-attachment
          fieldPath: status.outputs.attachment_id
      replaceExistingAssociation: true
  propagations:
    - valueFrom:
        kind: AwsTransitGatewayVpcAttachment
        name: shared-services-attachment
        fieldPath: status.outputs.attachment_id
  routes:
    - destinationCidrBlock: 10.200.0.0/16
      blackhole: true
  setAsDefaultAssociationTable: true
  setAsDefaultPropagationTable: true
