// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/digitalocean/digitaloceancdn/v1alpha1/spec.proto

package digitaloceancdnv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DigitalOceanCdnSpec models the full digitalocean_cdn resource surface: a
// CDN endpoint that serves a Spaces bucket's content from DigitalOcean's
// global edge network, optionally under a custom subdomain with a managed
// TLS certificate.
//
// Certificates are referenced BY NAME, never by UUID: a Let's Encrypt
// certificate's UUID rotates on every auto-renewal while its name stays
// stable, so DigitalOcean addresses CDN certificates by name (the provider's
// numeric certificate_id argument is deprecated for exactly this reason and
// is deliberately not modeled here -- its update path can silently detach
// the certificate when the custom domain changes).
type DigitalOceanCdnSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The origin server -- the fully-qualified domain name of the Space whose
	// content the CDN serves (for example
	// "my-bucket.nyc3.digitaloceanspaces.com"). Use a literal FQDN or a
	// reference to a DigitalOceanBucket resource. Changing it replaces the
	// CDN endpoint.
	Origin *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	// (Optional) How long, in seconds, the edge caches content before
	// revalidating against the origin. When unset, DigitalOcean applies its
	// default of 3600 (one hour) and reports it back. The floor is 1 because
	// an explicit zero can never reach the API -- the provider drops zero
	// values on the way out, making "ttl = 0" indistinguishable from unset.
	Ttl *int32 `protobuf:"varint,2,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`
	// (Optional) The DigitalOcean-managed TLS certificate for the custom
	// domain, referenced by its stable NAME (which is also what
	// DigitalOceanCertificate exports as certificate_id). The literal value
	// "needs-cloudflare-cert" is a DigitalOcean sentinel that requests an
	// edge-provisioned certificate instead of an account-managed one.
	Certificate *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// (Optional) A fully-qualified custom subdomain to serve the CDN content
	// from (for example "assets.example.com"). Requires certificate: serving
	// a custom domain without TLS is not supported by DigitalOcean, and the
	// provider only surfaces the failure at apply time -- it is rejected at
	// validation time here instead.
	CustomDomain  string `protobuf:"bytes,4,opt,name=custom_domain,json=customDomain,proto3" json:"custom_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalOceanCdnSpec) Reset() {
	*x = DigitalOceanCdnSpec{}
	mi := &file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalOceanCdnSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalOceanCdnSpec) ProtoMessage() {}

func (x *DigitalOceanCdnSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalOceanCdnSpec.ProtoReflect.Descriptor instead.
func (*DigitalOceanCdnSpec) Descriptor() ([]byte, []int) {
	return file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *DigitalOceanCdnSpec) GetOrigin() *v1.StringValueOrRef {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *DigitalOceanCdnSpec) GetTtl() int32 {
	if x != nil && x.Ttl != nil {
		return *x.Ttl
	}
	return 0
}

func (x *DigitalOceanCdnSpec) GetCertificate() *v1.StringValueOrRef {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *DigitalOceanCdnSpec) GetCustomDomain() string {
	if x != nil {
		return x.CustomDomain
	}
	return ""
}

var File_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"8catalog/digitalocean/digitaloceancdn/v1alpha1/spec.proto\x121dev.planton.digitalocean.digitaloceancdn.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\"\xae\x05\n" +
	"\x13DigitalOceanCdnSpec\x12|\n" +
	"\x06origin\x18\x01 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB0\xbaH\x03\xc8\x01\x01\x88\xd4a\x89'\x92\xd4a!status.outputs.bucket_domain_nameR\x06origin\x12\x1e\n" +
	"\x03ttl\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x01H\x00R\x03ttl\x88\x01\x01\x12|\n" +
	"\vcertificate\x18\x03 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB&\x88\xd4a\x95'\x92\xd4a\x1dstatus.outputs.certificate_idR\vcertificate\x12\xbf\x01\n" +
	"\rcustom_domain\x18\x04 \x01(\tB\x99\x01\xbaH\x95\x01\xba\x01\x91\x01\n" +
	"\x17spec.custom_domain_fqdn\x123custom_domain must be a fully-qualified domain name\x1aAthis == '' || this.matches('^[A-Za-z0-9\\\\-\\\\.]+\\\\.[A-Za-z]{2,}$')R\fcustomDomain:\xb0\x01\xbaH\xac\x01\x1a\xa9\x01\n" +
	"'spec.custom_domain_requires_certificate\x12Kcustom_domain requires certificate (the TLS certificate that will serve it)\x1a1this.custom_domain == '' || has(this.certificate)B\x06\n" +
	"\x04_ttlB\x8f\x03\n" +
	"5com.dev.planton.digitalocean.digitaloceancdn.v1alpha1B\tSpecProtoP\x01Zbgithub.com/plantonhq/planton/catalog/digitalocean/digitaloceancdn/v1alpha1;digitaloceancdnv1alpha1\xa2\x02\x04DPDD\xaa\x021Dev.Planton.Digitalocean.Digitaloceancdn.V1alpha1\xca\x021Dev\\Planton\\Digitalocean\\Digitaloceancdn\\V1alpha1\xe2\x02=Dev\\Planton\\Digitalocean\\Digitaloceancdn\\V1alpha1\\GPBMetadata\xea\x025Dev::Planton::Digitalocean::Digitaloceancdn::V1alpha1b\x06proto3"

var (
	file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDesc), len(file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDescData
}

var file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_goTypes = []any{
	(*DigitalOceanCdnSpec)(nil), // 0: dev.planton.digitalocean.digitaloceancdn.v1alpha1.DigitalOceanCdnSpec
	(*v1.StringValueOrRef)(nil), // 1: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_depIdxs = []int32{
	1, // 0: dev.planton.digitalocean.digitaloceancdn.v1alpha1.DigitalOceanCdnSpec.origin:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 1: dev.planton.digitalocean.digitaloceancdn.v1alpha1.DigitalOceanCdnSpec.certificate:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_init() }
func file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_init() {
	if File_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto != nil {
		return
	}
	file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDesc), len(file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto = out.File
	file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_goTypes = nil
	file_catalog_digitalocean_digitaloceancdn_v1alpha1_spec_proto_depIdxs = nil
}
