apiVersion: gcp.planton.dev/v1
kind: GcpRegionNetworkEndpointGroup
metadata:
  name: psc-neg
spec:
  projectId:
    value: "my-gcp-project-123" # replace: your GCP project id
  region: us-central1 # replace: your region
  networkEndpointType: PRIVATE_SERVICE_CONNECT
  # The published service-attachment URL or a Google API bundle.
  pscTargetService: "asia-northeast3-cloudkms.googleapis.com" # replace: your PSC target
  network:
    value: "projects/my-gcp-project-123/global/networks/default" # replace: your VPC self-link
  subnetwork:
    value: "projects/my-gcp-project-123/regions/us-central1/subnetworks/default" # replace: your subnet self-link
