apiVersion: kubernetes.planton.dev/v1alpha1
kind: KubernetesGatekeeper
metadata:
  name: gatekeeper
spec:
  namespace:
    value: gatekeeper-system
  createNamespace: true
  replicas: 3
  externalCert:
    secretName:
      valueFrom:
        kind: KubernetesCertificate
        name: gatekeeper-webhook-cert
        fieldPath: spec.secretName
