// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: catalog/gcp/gcpprojectiammember/v1alpha1/spec.proto

package gcpprojectiammemberv1alpha1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/plantonhq/planton/shared/foreignkey/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GcpProjectIamMemberSpec defines a single ADDITIVE project-level IAM grant:
// one role, to one member, on one project — the safe, composable unit of GCP
// access control.
//
// Additive semantics: this grant merges into the project's IAM policy without
// touching any other member's bindings on the same role, and removal subtracts
// only this exact (role, member) pair. Multiple grants — from different charts,
// teams, or tools — never fight over the policy. (Authoritative binding/policy
// management, which clobbers everything not listed, is deliberately not modeled.)
//
// Every field is immutable, mirroring the underlying API: an IAM grant has no
// update — changing role, member, or condition replaces the grant atomically.
type GcpProjectIamMemberSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The GCP project whose IAM policy receives this grant.
	// Can be a literal project ID or a reference to a GcpProject resource.
	// If omitted, the provider's default project is used.
	ProjectId *v1.StringValueOrRef `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// The role to grant. Either a predefined role ("roles/storage.objectViewer")
	// or a custom role's fully-qualified name ("projects/<project>/roles/<role_id>").
	// Reference a GcpIamCustomRole resource to grant a custom role — its `name`
	// output is exactly this value.
	Role *v1.StringValueOrRef `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// The identity receiving the grant, in GCP IAM member format:
	//
	//	serviceAccount:<email>       — a service account (the most common in IaC;
	//	                               reference a GcpServiceAccount resource —
	//	                               its `member` output is exactly this value)
	//	user:<email>                 — a Google account
	//	group:<email>                — a Google group
	//	domain:<domain>              — everyone in a Workspace/Cloud Identity domain
	//	principal:// / principalSet:// — workload identity federation principals
	//	allUsers / allAuthenticatedUsers — public access (grant with extreme care)
	//
	// Grants to deleted principals ("deleted:...") are not supported.
	// Format validation happens at deploy time in the modules rather than here,
	// because the value usually arrives through a reference that is only
	// resolved at deploy time.
	Member *v1.StringValueOrRef `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	// Optional IAM Condition restricting when this grant applies (e.g. only on
	// resources with a given prefix, or before an expiry date). The condition is
	// part of the grant's identity: the same role with and without a condition
	// are two independent grants that do not interfere.
	Condition     *GcpProjectIamMemberCondition `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpProjectIamMemberSpec) Reset() {
	*x = GcpProjectIamMemberSpec{}
	mi := &file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpProjectIamMemberSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpProjectIamMemberSpec) ProtoMessage() {}

func (x *GcpProjectIamMemberSpec) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpProjectIamMemberSpec.ProtoReflect.Descriptor instead.
func (*GcpProjectIamMemberSpec) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescGZIP(), []int{0}
}

func (x *GcpProjectIamMemberSpec) GetProjectId() *v1.StringValueOrRef {
	if x != nil {
		return x.ProjectId
	}
	return nil
}

func (x *GcpProjectIamMemberSpec) GetRole() *v1.StringValueOrRef {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *GcpProjectIamMemberSpec) GetMember() *v1.StringValueOrRef {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *GcpProjectIamMemberSpec) GetCondition() *GcpProjectIamMemberCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

// An IAM Condition — a CEL expression that must evaluate true for the grant
// to apply. See https://cloud.google.com/iam/docs/conditions-overview for the
// attribute reference and expression language.
type GcpProjectIamMemberCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short human-readable title identifying the condition's intent,
	// e.g. "expires-2026-12-31" or "prod-buckets-only".
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// The CEL condition expression, e.g.
	// request.time < timestamp("2027-01-01T00:00:00Z") or
	// resource.name.startsWith("projects/_/buckets/prod-").
	Expression string `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	// Optional longer explanation of what the condition does and why it exists.
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GcpProjectIamMemberCondition) Reset() {
	*x = GcpProjectIamMemberCondition{}
	mi := &file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GcpProjectIamMemberCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GcpProjectIamMemberCondition) ProtoMessage() {}

func (x *GcpProjectIamMemberCondition) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GcpProjectIamMemberCondition.ProtoReflect.Descriptor instead.
func (*GcpProjectIamMemberCondition) Descriptor() ([]byte, []int) {
	return file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescGZIP(), []int{1}
}

func (x *GcpProjectIamMemberCondition) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GcpProjectIamMemberCondition) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *GcpProjectIamMemberCondition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto protoreflect.FileDescriptor

const file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDesc = "" +
	"\n" +
	"3catalog/gcp/gcpprojectiammember/v1alpha1/spec.proto\x12,dev.planton.gcp.gcpprojectiammember.v1alpha1\x1a\x1bbuf/validate/validate.proto\x1a&shared/foreignkey/v1/foreign_key.proto\"\xd8\x03\n" +
	"\x17GcpProjectIamMemberSpec\x12u\n" +
	"\n" +
	"project_id\x18\x01 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\"\x88\xd4a\xc1\x17\x92\xd4a\x19status.outputs.project_idR\tprojectId\x12j\n" +
	"\x04role\x18\x02 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB\"\xbaH\x03\xc8\x01\x01\x88\xd4a\xc0\x17\x92\xd4a\x13status.outputs.nameR\x04role\x12p\n" +
	"\x06member\x18\x03 \x01(\v22.dev.planton.shared.foreignkey.v1.StringValueOrRefB$\xbaH\x03\xc8\x01\x01\x88\xd4a\xc6\x17\x92\xd4a\x15status.outputs.memberR\x06member\x12h\n" +
	"\tcondition\x18\x04 \x01(\v2J.dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberConditionR\tcondition\"\x94\x01\n" +
	"\x1cGcpProjectIamMemberCondition\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x18dR\x05title\x12&\n" +
	"\n" +
	"expression\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"expression\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vdescriptionB\xf5\x02\n" +
	"0com.dev.planton.gcp.gcpprojectiammember.v1alpha1B\tSpecProtoP\x01Zagithub.com/plantonhq/planton/catalog/gcp/gcpprojectiammember/v1alpha1;gcpprojectiammemberv1alpha1\xa2\x02\x04DPGG\xaa\x02,Dev.Planton.Gcp.Gcpprojectiammember.V1alpha1\xca\x02,Dev\\Planton\\Gcp\\Gcpprojectiammember\\V1alpha1\xe2\x028Dev\\Planton\\Gcp\\Gcpprojectiammember\\V1alpha1\\GPBMetadata\xea\x020Dev::Planton::Gcp::Gcpprojectiammember::V1alpha1b\x06proto3"

var (
	file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescOnce sync.Once
	file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescData []byte
)

func file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescGZIP() []byte {
	file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescOnce.Do(func() {
		file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDesc), len(file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDesc)))
	})
	return file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDescData
}

var file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_goTypes = []any{
	(*GcpProjectIamMemberSpec)(nil),      // 0: dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberSpec
	(*GcpProjectIamMemberCondition)(nil), // 1: dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberCondition
	(*v1.StringValueOrRef)(nil),          // 2: dev.planton.shared.foreignkey.v1.StringValueOrRef
}
var file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_depIdxs = []int32{
	2, // 0: dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberSpec.project_id:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // 1: dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberSpec.role:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	2, // 2: dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberSpec.member:type_name -> dev.planton.shared.foreignkey.v1.StringValueOrRef
	1, // 3: dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberSpec.condition:type_name -> dev.planton.gcp.gcpprojectiammember.v1alpha1.GcpProjectIamMemberCondition
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_init() }
func file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_init() {
	if File_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDesc), len(file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_goTypes,
		DependencyIndexes: file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_depIdxs,
		MessageInfos:      file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_msgTypes,
	}.Build()
	File_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto = out.File
	file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_goTypes = nil
	file_catalog_gcp_gcpprojectiammember_v1alpha1_spec_proto_depIdxs = nil
}
